---
title: "893A.Kennet.2007"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 10
thisTS <- TS[which(udsn[i] == dsn)]
```
#893A.Kennet.2007

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](893A.Kennet.2007.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/893A.Kennet.2007.lpd)
            

[Download paleoData only (csv)](893A.Kennet.2007.csv)
            

[Download chronData only (csv)](893A.Kennet.2007-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Kennett, Douglas J."), list(name = "Kennett, James P."), list(name = "Erlandson, Jon M."), list(name = "Cannariato, Kevin G."))
<p style="margin-left: 10px"><strong>citeKey: </strong>cannariato2005structureofthepenultimate
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>26
<p style="margin-left: 10px"><strong>pages: </strong>351-367
<p style="margin-left: 10px"><strong>title: </strong>Human responses to Middle Holocene climate change on California's Channel Islands
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>34.2875
<p style="margin-left: 0px"><strong>longitude: </strong>-120.036
<p style="margin-left: 0px"><strong>elevation: </strong>-588
<p style="margin-left: 0px"><strong>siteName: </strong>893A
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB9d68afed
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB4215db65
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) yr BP
</details>
<details style="margin-left: 10px">
<summary>hole (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5769e44e
<p style="margin-left: 10px"><strong>variableName: </strong>hole
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>section (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe51c2779dp
<p style="margin-left: 10px"><strong>variableName: </strong>section
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>interval (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD292174f8dp
<p style="margin-left: 10px"><strong>variableName: </strong>interval
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>varveCountedAgeKa (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7e8e8eaadp
<p style="margin-left: 10px"><strong>variableName: </strong>varveCountedAgeKa
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>varveCountedAgeAD0x2FBC (AD) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD0779737ddp
<p style="margin-left: 10px"><strong>variableName: </strong>varveCountedAgeAD0x2FBC
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>radiocarbonDatesAD0x2FBC (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD02c025e9dp
<p style="margin-left: 10px"><strong>variableName: </strong>radiocarbonDatesAD0x2FBC
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD05340dbbdp
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDcb260002dp
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD28794972dp
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1028d531dp
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>year (AD) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB10f223b2
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB5da1fb6e
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) yr BP
</details>
<details style="margin-left: 10px">
<summary>bulloidesTemp (degC) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf4934b2cdp
<p style="margin-left: 10px"><strong>variableName: </strong>bulloidesTemp
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>age (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1fa4d0be
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy2 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9b7b0312
<p style="margin-left: 10px"><strong>variableName: </strong>dummy2
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy3 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDfd2a0239
<p style="margin-left: 10px"><strong>variableName: </strong>dummy3
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy4 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDdd8c4ff1
<p style="margin-left: 10px"><strong>variableName: </strong>dummy4
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy5 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD543c622e
<p style="margin-left: 10px"><strong>variableName: </strong>dummy5
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy6 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf8072f4e
<p style="margin-left: 10px"><strong>variableName: </strong>dummy6
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy7 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDece0f148
<p style="margin-left: 10px"><strong>variableName: </strong>dummy7
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy8 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf7422476
<p style="margin-left: 10px"><strong>variableName: </strong>dummy8
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy9 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD797006f7
<p style="margin-left: 10px"><strong>variableName: </strong>dummy9
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy10 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe54dc6d7
<p style="margin-left: 10px"><strong>variableName: </strong>dummy10
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy11 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD777a1b28
<p style="margin-left: 10px"><strong>variableName: </strong>dummy11
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy12 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD493f1394
<p style="margin-left: 10px"><strong>variableName: </strong>dummy12
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### hole (missing) [1-1]
```{r}
plotCol(thisTS,ind = 1)
```

### section (missing) [1-1]
```{r}
plotCol(thisTS,ind = 4)
```

### interval (missing) [1-1]
```{r}
plotCol(thisTS,ind = 5)
```

### varveCountedAgeKa (missing) [1-1]
```{r}
plotCol(thisTS,ind = 6)
```

### varveCountedAgeAD0x2FBC (AD) [1-1]
```{r}
plotCol(thisTS,ind = 7)
```

### radiocarbonDatesAD0x2FBC (missing) [1-1]
```{r}
plotCol(thisTS,ind = 8)
```

### d18O (missing) [1-1]
```{r}
plotCol(thisTS,ind = 9)
```

### d18O (missing) [1-1]
```{r}
plotCol(thisTS,ind = 10)
```

### d18O (missing) [1-1]
```{r}
plotCol(thisTS,ind = 11)
```

### d18O (missing) [1-1]
```{r}
plotCol(thisTS,ind = 12)
```

### bulloidesTemp (degC) [2-1]
```{r}
plotCol(thisTS,ind = 13)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### age (unitless)
```{r}
plotCol(chronTS,ind = 1)
```

### dummy2 (unitless)
```{r}
plotCol(chronTS,ind = 2)
```

### dummy3 (unitless)
```{r}
plotCol(chronTS,ind = 3)
```

### dummy4 (unitless)
```{r}
plotCol(chronTS,ind = 4)
```

### dummy5 (unitless)
```{r}
plotCol(chronTS,ind = 5)
```

### dummy6 (unitless)
```{r}
plotCol(chronTS,ind = 6)
```

### dummy7 (unitless)
```{r}
plotCol(chronTS,ind = 7)
```

### dummy8 (unitless)
```{r}
plotCol(chronTS,ind = 8)
```

### dummy9 (unitless)
```{r}
plotCol(chronTS,ind = 9)
```

### dummy10 (unitless)
```{r}
plotCol(chronTS,ind = 10)
```

### dummy11 (unitless)
```{r}
plotCol(chronTS,ind = 11)
```

### dummy12 (unitless)
```{r}
plotCol(chronTS,ind = 12)
```
