---
title: "fauske.Linge.2009"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 201
thisTS <- TS[which(udsn[i] == dsn)]
```
#fauske.Linge.2009

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](fauske.Linge.2009.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/fauske.Linge.2009.lpd)
            

[Download paleoData only (csv)](fauske.Linge.2009.csv)
            

[Download chronData only (csv)](fauske.Linge.2009-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>Speleothem
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo-search/study/15444
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Linge, H."), list(name = "Lauritzen, S.-E."), list(name = "Andersson, C."), list(name = "Hansen, J. K."), list(name = "Skoglund, R. OE."), list(name = "Sundqvist, H. S."))
<p style="margin-left: 10px"><strong>journal: </strong>Climate of the Past
<p style="margin-left: 10px"><strong>volume: </strong>5
<p style="margin-left: 10px"><strong>title: </strong>Stable isotope records for the last 10 000 years from Okshola cave (Fauske, northern Norway) and regional comparisons
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>67.22
<p style="margin-left: 0px"><strong>longitude: </strong>15.81
<p style="margin-left: 0px"><strong>elevation: </strong>160
<p style="margin-left: 0px"><strong>siteName: </strong>fauske
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT088NTB6X
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTHOVR5CBH
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT0JA5R7NU
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT0UICY9DO
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>-1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT5WVGSSXZ
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT06D8GDPC
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>lab_id ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTSDU4CPF3
<p style="margin-left: 10px"><strong>variableName: </strong>lab_id
</details>
<details style="margin-left: 10px">
<summary>depth_error (1s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTDO1L8VNQ
<p style="margin-left: 10px"><strong>variableName: </strong>depth_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>U238 (ng/g)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT1FQEHSNX
<p style="margin-left: 10px"><strong>variableName: </strong>U238
<p style="margin-left: 10px"><strong>units: </strong>ng/g
</details>
<details style="margin-left: 10px">
<summary>U238_error (1s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT9RRY2X88
<p style="margin-left: 10px"><strong>variableName: </strong>U238_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>Th232 (ng/g)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTKO2IW2A4
<p style="margin-left: 10px"><strong>variableName: </strong>Th232
<p style="margin-left: 10px"><strong>units: </strong>ng/g
</details>
<details style="margin-left: 10px">
<summary>U234/U238 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTTXWUZFSL
<p style="margin-left: 10px"><strong>variableName: </strong>U234/U238
</details>
<details style="margin-left: 10px">
<summary>U234/U238_error (1s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT4PLLILSY
<p style="margin-left: 10px"><strong>variableName: </strong>U234/U238_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>Th230/U234 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT0WKIF7SU
<p style="margin-left: 10px"><strong>variableName: </strong>Th230/U234
</details>
<details style="margin-left: 10px">
<summary>Th230/U234_error (1s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTB5A79A0P
<p style="margin-left: 10px"><strong>variableName: </strong>Th230/U234_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>Th230/Th232 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT9Y9KGNBK
<p style="margin-left: 10px"><strong>variableName: </strong>Th230/Th232
</details>
<details style="margin-left: 10px">
<summary>Th230/Th232_error (1s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT9A1ED46Y
<p style="margin-left: 10px"><strong>variableName: </strong>Th230/Th232_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>U234/Th232 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTMQK0FYBK
<p style="margin-left: 10px"><strong>variableName: </strong>U234/Th232
</details>
<details style="margin-left: 10px">
<summary>U234/Th232_error (1s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTDGMKA27G
<p style="margin-left: 10px"><strong>variableName: </strong>U234/Th232_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>age_alt (bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTILRLKWJ4
<p style="margin-left: 10px"><strong>variableName: </strong>age_alt
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>age_alt_error (2s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTW4OWD4C9
<p style="margin-left: 10px"><strong>variableName: </strong>age_alt_error
<p style="margin-left: 10px"><strong>units: </strong>2s
</details>
<details style="margin-left: 10px">
<summary>age_error (2s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTS48XLI1Z
<p style="margin-left: 10px"><strong>variableName: </strong>age_error
<p style="margin-left: 10px"><strong>units: </strong>2s
</details>
<details style="margin-left: 10px">
<summary>U/Th ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT5OBOKF03
<p style="margin-left: 10px"><strong>variableName: </strong>U/Th
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O (permil)
```{r}
plotCol(thisTS,ind = 4)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### age (bp)
```{r}
plotCol(chronTS,ind = 17)
```

### lab_id ()
```{r}
plotCol(chronTS,ind = 1)
```

### depth_error (1s)
```{r}
plotCol(chronTS,ind = 3)
```

### U238 (ng/g)
```{r}
plotCol(chronTS,ind = 4)
```

### U238_error (1s)
```{r}
plotCol(chronTS,ind = 5)
```

### Th232 (ng/g)
```{r}
plotCol(chronTS,ind = 6)
```

### U234/U238 ()
```{r}
plotCol(chronTS,ind = 7)
```

### U234/U238_error (1s)
```{r}
plotCol(chronTS,ind = 8)
```

### Th230/U234 ()
```{r}
plotCol(chronTS,ind = 9)
```

### Th230/U234_error (1s)
```{r}
plotCol(chronTS,ind = 10)
```

### Th230/Th232 ()
```{r}
plotCol(chronTS,ind = 11)
```

### Th230/Th232_error (1s)
```{r}
plotCol(chronTS,ind = 12)
```

### U234/Th232 ()
```{r}
plotCol(chronTS,ind = 13)
```

### U234/Th232_error (1s)
```{r}
plotCol(chronTS,ind = 14)
```

### age_alt (bp)
```{r}
plotCol(chronTS,ind = 15)
```

### age_alt_error (2s)
```{r}
plotCol(chronTS,ind = 16)
```

### age_error (2s)
```{r}
plotCol(chronTS,ind = 18)
```

### U/Th ()
```{r}
plotCol(chronTS,ind = 19)
```
