---
title: "GeoB7702-3.Castaneda.2016"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 245
thisTS <- TS[which(udsn[i] == dsn)]
```
#GeoB7702-3.Castaneda.2016

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](GeoB7702-3.Castaneda.2016.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/GeoB7702-3.Castaneda.2016.lpd)
            

[Download paleoData only (csv)](GeoB7702-3.Castaneda.2016.csv)
            

[Download chronData only (csv)](GeoB7702-3.Castaneda.2016-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://doi.org/10.1594/PANGAEA.858559
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Castaneda, Isla S."), list(name = "Schouten, Stefan"), list(name = "Paetzold, Juergen"), list(name = "Lucassen, Friedrich"), list(name = "Kasemann, Simone"), list(name = "Kuhlmann, Holger"), list(name = "SchefuSS, Enno"))
<p style="margin-left: 10px"><strong>citeKey: </strong>needs0needsatitle
<p style="margin-left: 10px"><strong>journal: </strong>Earth and Planetary Science Letters
<p style="margin-left: 10px"><strong>volume: </strong>438
<p style="margin-left: 10px"><strong>title: </strong>Hydroclimate variability in the Nile River Basin during the past 28,000 years
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>31.6517
<p style="margin-left: 0px"><strong>longitude: </strong>34.0667
<p style="margin-left: 0px"><strong>elevation: </strong>-562
<p style="margin-left: 0px"><strong>siteName: </strong>GeoB7702-3
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RQtIL8JzjpP
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RM6vnGWCDqU
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>REpcleODBtH
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>C31dDSmow-ice (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf79af672
<p style="margin-left: 10px"><strong>variableName: </strong>C31dDSmow-ice
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>n-Alkane C31, dD [per mil SMOW] (C31 dD) * PI: Casta    eda, Isla S (isla@geo.umass.edu) * METHOD: Thermo Trace GC - Thermo Fischer MAT 253 (GC/IR-MS) * COMMENT: Leaf wax deuterium isotopes, with respect to VSMOW, ice volume corrected
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>monsoon
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MAAT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD6a7b432f
<p style="margin-left: 10px"><strong>variableName: </strong>MAAT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, air, annual mean [   C] (MAAT) * PI: Casta    eda, Isla S (isla@geo.umass.edu) * COMMENT: MBT', Branched GDGTs
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>MAAT
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>C31dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD36e20a5f
<p style="margin-left: 10px"><strong>variableName: </strong>C31dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>n-Alkane C31, dD [per mil SMOW] (C31 dD) * PI: Casta    eda, Isla S (isla@geo.umass.edu) * METHOD: Thermo Trace GC - Thermo Fischer MAT 253 (GC/IR-MS) * COMMENT: Leaf wax deuterium isotopes, with respect to VSMOW
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C31dDsd (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD3798724b
<p style="margin-left: 10px"><strong>variableName: </strong>C31dDsd
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>n-Alkane C31, dD, standard deviation COMMENT: Leaf wax deuterium isotopes
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C31d13C_PDB (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD17ad91b2
<p style="margin-left: 10px"><strong>variableName: </strong>C31d13C_PDB
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>n-Alkane C31, d13C [per mil PDB] (C31 d13C) * PI: Casta    eda, Isla S (isla@geo.umass.edu) * METHOD: Thermo Trace GC - Finnigan MAT 252 (GC/IR-MS) * COMMENT: Leaf wax carbon isotopes, with respect to VPDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C31d13Csd (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD10136429
<p style="margin-left: 10px"><strong>variableName: </strong>C31d13Csd
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>n-Alkane C31, d13C, standard deviation [   ] (C31 d13C std dev) * PI: Casta    eda, Isla S (isla@geo.umass.edu) * COMMENT: Leaf wax carbon isotopes
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MBT (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1be767d8
<p style="margin-left: 10px"><strong>variableName: </strong>MBT
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>Methylation index of dominant branched tetraethers (MBT') * PI: Casta    eda, Isla S (isla@geo.umass.edu) * COMMENT: Branched GDGTs
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MBTsd (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2326672b
<p style="margin-left: 10px"><strong>variableName: </strong>MBTsd
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>Standard deviation COMMENT: MBT', Branched GDGTs
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>CBT (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDfe736bed
<p style="margin-left: 10px"><strong>variableName: </strong>CBT
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>Cyclization ratio of branched tetraethers (CBT) * PI: Castaneda, Isla S (isla@geo.umass.edu) * COMMENT: Branched GDGTs
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>CBTsd (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf2234b39
<p style="margin-left: 10px"><strong>variableName: </strong>CBTsd
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>Standard deviation COMMENT: CBT, Branched GDGTs
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>pH (pH)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD277e0621
<p style="margin-left: 10px"><strong>variableName: </strong>pH
<p style="margin-left: 10px"><strong>units: </strong>pH
<p style="margin-left: 10px"><strong>description: </strong>pH (pH)  * COMMENT: CBT, Branched GDGTs
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>age (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe7719690
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy2 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD07ca7390
<p style="margin-left: 10px"><strong>variableName: </strong>dummy2
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy3 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDb78ebfb7
<p style="margin-left: 10px"><strong>variableName: </strong>dummy3
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy4 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD78372860
<p style="margin-left: 10px"><strong>variableName: </strong>dummy4
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy5 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD619375bc
<p style="margin-left: 10px"><strong>variableName: </strong>dummy5
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy6 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD272183b0
<p style="margin-left: 10px"><strong>variableName: </strong>dummy6
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy7 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2dd3873e
<p style="margin-left: 10px"><strong>variableName: </strong>dummy7
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy8 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD4fa97c31
<p style="margin-left: 10px"><strong>variableName: </strong>dummy8
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy9 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD616f9777
<p style="margin-left: 10px"><strong>variableName: </strong>dummy9
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy10 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD6e7a0312
<p style="margin-left: 10px"><strong>variableName: </strong>dummy10
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy11 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD3728adbf
<p style="margin-left: 10px"><strong>variableName: </strong>dummy11
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy12 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD32ee6220
<p style="margin-left: 10px"><strong>variableName: </strong>dummy12
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>dummy13 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDcde579af
<p style="margin-left: 10px"><strong>variableName: </strong>dummy13
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### C31dDSmow-ice (permil)
```{r}
plotCol(thisTS,ind = 6)
```

### MAAT (degC)
```{r}
plotCol(thisTS,ind = 11)
```

### C31dD (permil)
```{r}
plotCol(thisTS,ind = 1)
```

### C31dDsd (unitless)
```{r}
plotCol(thisTS,ind = 5)
```

### C31d13C_PDB (permil)
```{r}
plotCol(thisTS,ind = 7)
```

### C31d13Csd (unitless)
```{r}
plotCol(thisTS,ind = 8)
```

### MBT (unitless)
```{r}
plotCol(thisTS,ind = 9)
```

### MBTsd (unitless)
```{r}
plotCol(thisTS,ind = 10)
```

### CBT (unitless)
```{r}
plotCol(thisTS,ind = 12)
```

### CBTsd (unitless)
```{r}
plotCol(thisTS,ind = 13)
```

### pH (pH)
```{r}
plotCol(thisTS,ind = 14)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### age (unitless)
```{r}
plotCol(chronTS,ind = 1)
```

### dummy2 (unitless)
```{r}
plotCol(chronTS,ind = 2)
```

### dummy3 (unitless)
```{r}
plotCol(chronTS,ind = 3)
```

### dummy4 (unitless)
```{r}
plotCol(chronTS,ind = 4)
```

### dummy5 (unitless)
```{r}
plotCol(chronTS,ind = 5)
```

### dummy6 (unitless)
```{r}
plotCol(chronTS,ind = 6)
```

### dummy7 (unitless)
```{r}
plotCol(chronTS,ind = 7)
```

### dummy8 (unitless)
```{r}
plotCol(chronTS,ind = 8)
```

### dummy9 (unitless)
```{r}
plotCol(chronTS,ind = 9)
```

### dummy10 (unitless)
```{r}
plotCol(chronTS,ind = 10)
```

### dummy11 (unitless)
```{r}
plotCol(chronTS,ind = 11)
```

### dummy12 (unitless)
```{r}
plotCol(chronTS,ind = 12)
```

### dummy13 (unitless)
```{r}
plotCol(chronTS,ind = 13)
```
