---
title: "GGC19.Farmer.2011"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 255
thisTS <- TS[which(udsn[i] == dsn)]
```
#GGC19.Farmer.2011

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](GGC19.Farmer.2011.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/GGC19.Farmer.2011.lpd)
            

[Download paleoData only (csv)](GGC19.Farmer.2011.csv)
            

[Download chronData only (csv)](GGC19.Farmer.2011-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo-search/study/15444
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Farmer, Jesse R."), list(name = "Cronin, Thomas M."), list(name = "de Vernal, Anne"), list(name = "Dwyer, Gary S."), list(name = "Keigwin, Lloyd D."), list(name = "Thunell, Robert C."))
<p style="margin-left: 10px"><strong>journal: </strong>Geophysical Research Letters
<p style="margin-left: 10px"><strong>volume: </strong>38
<p style="margin-left: 10px"><strong>title: </strong>Western Arctic Ocean temperature variability during the last 8000 years
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>72.16
<p style="margin-left: 0px"><strong>longitude: </strong>-155.51
<p style="margin-left: 0px"><strong>elevation: </strong>-369
<p style="margin-left: 0px"><strong>siteName: </strong>GGC19
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT3T9SV5YD
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT5833R3C6
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT0ZB7WHKL
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>SBT
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT5MM3IOKT
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTKHVIUKB7
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTJD2ZXYMK
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>SBT (degC) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTX9J4H9KP
<p style="margin-left: 10px"><strong>variableName: </strong>SBT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>SBT
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTU87CJ8I6
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [3-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTMEW5KQ13
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP) [3-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTS0XJ338R
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>Sea_Ice_months (months/year) [3-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT25EF3AP3
<p style="margin-left: 10px"><strong>variableName: </strong>Sea_Ice_months
<p style="margin-left: 10px"><strong>units: </strong>months/year
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>ice
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>age (BP) [4-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTGPDC4B67
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [4-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTS1RYEDDW
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [4-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTLU4EW21I
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>salinity (psu) [4-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTWP0AC2XZ
<p style="margin-left: 10px"><strong>variableName: </strong>salinity
<p style="margin-left: 10px"><strong>units: </strong>psu
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>S
<p style="margin-left: 20px"><strong>variableDetail: </strong>SSS
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sea_Ice_months (months/year) [4-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT4DJUFWUA
<p style="margin-left: 10px"><strong>variableName: </strong>Sea_Ice_months
<p style="margin-left: 10px"><strong>units: </strong>months/year
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>ICE
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sea_Ice_conc (0-10) [4-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTX7JOGE9T
<p style="margin-left: 10px"><strong>variableName: </strong>Sea_Ice_conc
<p style="margin-left: 10px"><strong>units: </strong>0-10
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>ICE
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>productivity (gcm2) [4-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTK7V865MD
<p style="margin-left: 10px"><strong>variableName: </strong>productivity
<p style="margin-left: 10px"><strong>units: </strong>gcm2
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>age (BP) [4-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT8RP47HBV
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [4-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT6D3JR7SB
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter+summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT4NKDYMCG
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age14C (bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT7N0O5S87
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>age_error (1s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT1XT616DH
<p style="margin-left: 10px"><strong>variableName: </strong>age_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>cal_age_range_young (bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTT07MZF6X
<p style="margin-left: 10px"><strong>variableName: </strong>cal_age_range_young
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>cal_age_range_old (bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTYVLHODCW
<p style="margin-left: 10px"><strong>variableName: </strong>cal_age_range_old
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>age_type (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTWDTVIP43
<p style="margin-left: 10px"><strong>variableName: </strong>age_type
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>lab_id (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTYNUHGQNE
<p style="margin-left: 10px"><strong>variableName: </strong>lab_id
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>note (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTDABWNK39
<p style="margin-left: 10px"><strong>variableName: </strong>note
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC) [1-1]
```{r}
plotCol(thisTS,ind = 4)
```

### d18O (permil) [1-1]
```{r}
plotCol(thisTS,ind = 3)
```

### SBT (degC) [2-1]
```{r}
plotCol(thisTS,ind = 8)
```

### d18O (permil) [2-1]
```{r}
plotCol(thisTS,ind = 7)
```

### Sea_Ice_months (months/year) [3-1]
```{r}
plotCol(thisTS,ind = 11)
```

### temperature (degC) [4-1]
```{r}
plotCol(thisTS,ind = 14)
```

### salinity (psu) [4-1]
```{r}
plotCol(thisTS,ind = 15)
```

### Sea_Ice_months (months/year) [4-1]
```{r}
plotCol(thisTS,ind = 16)
```

### Sea_Ice_conc (0-10) [4-1]
```{r}
plotCol(thisTS,ind = 17)
```

### productivity (gcm2) [4-1]
```{r}
plotCol(thisTS,ind = 18)
```

### temperature (degC) [4-2]
```{r}
plotCol(thisTS,ind = 19)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 1)
```

### age14C (bp)
```{r}
plotCol(chronTS,ind = 2)
```

### age_error (1s)
```{r}
plotCol(chronTS,ind = 3)
```

### cal_age_range_young (bp)
```{r}
plotCol(chronTS,ind = 4)
```

### cal_age_range_old (bp)
```{r}
plotCol(chronTS,ind = 5)
```

### age_type (unitless)
```{r}
plotCol(chronTS,ind = 6)
```

### lab_id (unitless)
```{r}
plotCol(chronTS,ind = 7)
```

### note (unitless)
```{r}
plotCol(chronTS,ind = 8)
```
