---
title: "GIK17940_2"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 259
thisTS <- TS[which(udsn[i] == dsn)]
```
#GIK17940_2

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](GIK17940_2.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/GIK17940_2.lpd)
            

[Download paleoData only (csv)](GIK17940_2.csv)
            

[Download chronData only (csv)](GIK17940_2-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>c("https://doi.pangaea.de/10.1594/PANGAEA.55575", "https://doi.pangaea.de/10.1594/PANGAEA.794489", "https://doi.pangaea.de/10.1594/PANGAEA.55901", "https://doi.pangaea.de/10.1594/PANGAEA.736636", "https://doi.pangaea.de/10.1594/PANGAEA.113006", "https://doi.pangaea.de/10.1594/PANGAEA.812103")
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Wang, L"), list(name = "Sarnthein, M"), list(name = "Erlenkeuser, H"), list(name = "Grimalt, J"), list(name = "Grootes, P"), list(name = "Heilig, S"), list(name = "Ivanova, E"), list(name = "Kienast, M"), list(name = "Pelejero, C"), list(name = "Pflaumann, U"))
<p style="margin-left: 10px"><strong>journal: </strong>Marine Geology
<p style="margin-left: 10px"><strong>volume: </strong>156
<p style="margin-left: 10px"><strong>title: </strong>East Asian monsoon climate during the Late Pleistocene: high-resolution sediment records from the South China Sea
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Pelejero, Carles"), list(name = "Grimalt, Joan O."), list(name = "Heilig, Stephanie"), list(name = "Kienast, Markus"), list(name = "Wang, Luejiang"))
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>14
<p style="margin-left: 10px"><strong>title: </strong>High-resolution UK37temperature reconstructions in the South China Sea over the past 220 kyr
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Wang, Luejiang"), list(name = "Sarnthein, Michael"), list(name = "Grootes, Pieter M."), list(name = "Erlenkeuser, Helmut"))
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>14
<p style="margin-left: 10px"><strong>title: </strong>Millennial reoccurrence of century-scale abrupt events of East Asian Monsoon: A possible heat conveyor for the global deglaciation
</details>
<details style="margin-left: 10px">
<summary>pub4</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Jian, Zhimin"), list(name = "Wang, Luejiang"), list(name = "Kienast, Markus"), list(name = "Sarnthein, Michael"), list(name = "Kuhnt, Wolfgang"), list(name = "Lin, Huiling"), list(name = "Wang, Pinxian"))
<p style="margin-left: 10px"><strong>journal: </strong>Marine Geology
<p style="margin-left: 10px"><strong>volume: </strong>156
<p style="margin-left: 10px"><strong>title: </strong>Benthic foraminiferal paleoceanography of the South China Sea over the last 40,000 years
</details>
<details style="margin-left: 10px">
<summary>pub5</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Hu, Dengke"), list(name = "Böning, Philipp"), list(name = "Köhler, Cornelia M."), list(name = "Hillier, Stephen"), list(name = "Pressling, Nicola"), list(name = "Wan, Shiming"), list(name = "Brumsack, Hans J."), list(name = "Clift, Peter D."))
<p style="margin-left: 10px"><strong>journal: </strong>Chemical Geology
<p style="margin-left: 10px"><strong>volume: </strong>326-327
<p style="margin-left: 10px"><strong>title: </strong>Deep sea records of the continental weathering and erosion response to East Asian monsoon intensification since 14ka in the South China Sea
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>20.1167
<p style="margin-left: 0px"><strong>longitude: </strong>117.3833
<p style="margin-left: 0px"><strong>elevation: </strong>-1727
<p style="margin-left: 0px"><strong>siteName: </strong>GIK17940_2
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RsC23VwETf1
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>TOC (percent) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RjpQ1r40oqw
<p style="margin-left: 10px"><strong>variableName: </strong>TOC
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>TOC_percent
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>CaCO3 (percent) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RR9D1ETZL3e
<p style="margin-left: 10px"><strong>variableName: </strong>CaCO3
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>CaCO3_percent
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RpmTcQV6o04
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RmK0PazBsA1
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>C_wuellerstorfi_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R16jY64Vqnz
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>C_wuellerstorfi_d13C_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ro03jWPC8Y6
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>C_kullenbergi_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RCjXArpeCGj
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>C_kullenbergi_d13C_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rm5KwPljTfh
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>Cibicidoides_sp_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rj8FAQKXwjX
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>Cibicidoides_sp_d13C_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R8bDSWAPKZv
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>merged benthic d18O
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RL3GHm3XDPA
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rk2KnhNAFpX
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G_ruber_w_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.d13C (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rj6tVqmZ48g
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G_ruber_w_d13C_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RRwxEoMT8lw
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R855rnsySpx
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_dated_ka_Age_14C_milieu_reservoir_cor
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1mFBGI9YKK
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G_crassaf_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rs9wcG3FPfG
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R48R7F9UWfx
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R0Cd5zCrTJs
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_degC_Calculated_from_UK37_Pelejer
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE-1
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RFOJiSb8IVR
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_degC_Calculated_from_UK'37_Mueller
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE-2
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperatureComposite (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R7TSduJL8rZ
<p style="margin-left: 10px"><strong>variableName: </strong>temperatureComposite
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_degC_Calculated_from_UK37_Pelejer; SST_degC_Calculated_from_UK'37_Mueller
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Uk37 (missing) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RHzA12eFfAx
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>UK37
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-6]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RZ7L7Z7259K
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>DBD (g_cm3) [1-6]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RqJFkkzwhqV
<p style="margin-left: 10px"><strong>variableName: </strong>DBD
<p style="margin-left: 10px"><strong>units: </strong>g_cm3
<p style="margin-left: 10px"><strong>description: </strong>DBD_g_cm3
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rj6hD6OlnBL
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>dateType ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rgwu4USGtEp
<p style="margin-left: 10px"><strong>variableName: </strong>dateType
</details>
<details style="margin-left: 10px">
<summary>measurementMaterial ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R6qzF0yD6JU
<p style="margin-left: 10px"><strong>variableName: </strong>measurementMaterial
</details>
<details style="margin-left: 10px">
<summary>sensorSpecies ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ro84INeOPQU
<p style="margin-left: 10px"><strong>variableName: </strong>sensorSpecies
</details>
<details style="margin-left: 10px">
<summary>age14C (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R4Y0JiTH8kD
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CHi (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R3Mq1y1FYns
<p style="margin-left: 10px"><strong>variableName: </strong>age14CHi
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CLow (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RoDnouKzMjD
<p style="margin-left: 10px"><strong>variableName: </strong>age14CLow
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>reservoirAge (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rukycd2S5W1
<p style="margin-left: 10px"><strong>variableName: </strong>reservoirAge
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### TOC (percent)
```{r}
plotCol(thisTS,ind = 2)
```

### CaCO3 (percent)
```{r}
plotCol(thisTS,ind = 3)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 5)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 6)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 7)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 8)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 9)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 10)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 11)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 13)
```

### planktic.d13C (permil)
```{r}
plotCol(thisTS,ind = 14)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 17)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 21)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 22)
```

### temperatureComposite (degC)
```{r}
plotCol(thisTS,ind = 23)
```

### Uk37 (missing)
```{r}
plotCol(thisTS,ind = 20)
```

### DBD (g_cm3)
```{r}
plotCol(thisTS,ind = 25)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### dateType ()
```{r}
plotCol(chronTS,ind = 1)
```

### measurementMaterial ()
```{r}
plotCol(chronTS,ind = 3)
```

### sensorSpecies ()
```{r}
plotCol(chronTS,ind = 4)
```

### age14C (kyr)
```{r}
plotCol(chronTS,ind = 5)
```

### age14CHi (kyr)
```{r}
plotCol(chronTS,ind = 6)
```

### age14CLow (kyr)
```{r}
plotCol(chronTS,ind = 7)
```

### reservoirAge (kyr)
```{r}
plotCol(chronTS,ind = 8)
```
