---
title: "HU84.deVernal.2013"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 326
thisTS <- TS[which(udsn[i] == dsn)]
```
#HU84.deVernal.2013

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](HU84.deVernal.2013.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/HU84.deVernal.2013.lpd)
            

[Download paleoData only (csv)](HU84.deVernal.2013.csv)
            

[Download chronData only (csv)](HU84.deVernal.2013-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo-search/study/15444
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "de Vernal, Anne"), list(name = "Hillaire-Marcel, Claude"), list(name = "Rochon, Andre"), list(name = "Frechette, Bianca"), list(name = "Henry, Maryse"), list(name = "Solignac, Sandrine"), list(name = "Bonnet, Sophie"))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>79
<p style="margin-left: 10px"><strong>title: </strong>Dinocyst-based reconstructions of sea ice cover concentration during the Holocene in the Arctic Ocean, the northern North Atlantic Ocean and its adjacent seas
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>58.3677
<p style="margin-left: 0px"><strong>longitude: </strong>-57.507
<p style="margin-left: 0px"><strong>elevation: </strong>-2853
<p style="margin-left: 0px"><strong>siteName: </strong>HU84
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTNXKYT4R3
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTQAMZI8ZL
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTT4U7T413
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>salinity (psu) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTCXVB1G0W
<p style="margin-left: 10px"><strong>variableName: </strong>salinity
<p style="margin-left: 10px"><strong>units: </strong>psu
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>S
<p style="margin-left: 20px"><strong>variableDetail: </strong>SSS
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sea_Ice_months (months/year) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT4N3LKU0B
<p style="margin-left: 10px"><strong>variableName: </strong>Sea_Ice_months
<p style="margin-left: 10px"><strong>units: </strong>months/year
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>ICE
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sea_Ice_conc (0-10) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTEQGFAHNH
<p style="margin-left: 10px"><strong>variableName: </strong>Sea_Ice_conc
<p style="margin-left: 10px"><strong>units: </strong>0-10
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>ICE
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>productivity (gcm2) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTOR1TJJ2L
<p style="margin-left: 10px"><strong>variableName: </strong>productivity
<p style="margin-left: 10px"><strong>units: </strong>gcm2
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTK0OF9YQ5
<p style="margin-left: 10px"><strong>variableName: </strong>C
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT1Z9O0TZD
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTHNY32G95
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter+summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTA0KIQNTM
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>depth_top (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTDR3WHVMG
<p style="margin-left: 10px"><strong>variableName: </strong>depth_top
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>depth_bot (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT4NLNSRF9
<p style="margin-left: 10px"><strong>variableName: </strong>depth_bot
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>mass dry (mg)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTBASI31LB
<p style="margin-left: 10px"><strong>variableName: </strong>mass dry
<p style="margin-left: 10px"><strong>units: </strong>mg
</details>
<details style="margin-left: 10px">
<summary>age14C (bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTQ1LADF6J
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>age_error (1_s)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTLWWE342D
<p style="margin-left: 10px"><strong>variableName: </strong>age_error
<p style="margin-left: 10px"><strong>units: </strong>1_s
</details>
<details style="margin-left: 10px">
<summary>deltaR (years)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTBU859OX2
<p style="margin-left: 10px"><strong>variableName: </strong>deltaR
<p style="margin-left: 10px"><strong>units: </strong>years
</details>
<details style="margin-left: 10px">
<summary>depth_mid (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTCA3WGD2D
<p style="margin-left: 10px"><strong>variableName: </strong>depth_mid
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>thickness (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTRET8XYKJ
<p style="margin-left: 10px"><strong>variableName: </strong>thickness
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>age_type ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT8KF4TOII
<p style="margin-left: 10px"><strong>variableName: </strong>age_type
</details>
<details style="margin-left: 10px">
<summary>core_name ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTO96B34SM
<p style="margin-left: 10px"><strong>variableName: </strong>core_name
</details>
<details style="margin-left: 10px">
<summary>lab_id ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTBEHNX6SS
<p style="margin-left: 10px"><strong>variableName: </strong>lab_id
</details>
<details style="margin-left: 10px">
<summary>material_dated ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTRRCFNAS6
<p style="margin-left: 10px"><strong>variableName: </strong>material_dated
</details>
<details style="margin-left: 10px">
<summary>original_reference ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTC6528DX9
<p style="margin-left: 10px"><strong>variableName: </strong>original_reference
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 3)
```

### salinity (psu)
```{r}
plotCol(thisTS,ind = 4)
```

### Sea_Ice_months (months/year)
```{r}
plotCol(thisTS,ind = 5)
```

### Sea_Ice_conc (0-10)
```{r}
plotCol(thisTS,ind = 6)
```

### productivity (gcm2)
```{r}
plotCol(thisTS,ind = 7)
```

### C (missing)
```{r}
plotCol(thisTS,ind = 8)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 9)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 3)
```

### depth_top (mm)
```{r}
plotCol(chronTS,ind = 1)
```

### depth_bot (mm)
```{r}
plotCol(chronTS,ind = 2)
```

### mass dry (mg)
```{r}
plotCol(chronTS,ind = 4)
```

### age14C (bp)
```{r}
plotCol(chronTS,ind = 5)
```

### age_error (1_s)
```{r}
plotCol(chronTS,ind = 6)
```

### deltaR (years)
```{r}
plotCol(chronTS,ind = 7)
```

### depth_mid (mm)
```{r}
plotCol(chronTS,ind = 8)
```

### thickness (mm)
```{r}
plotCol(chronTS,ind = 9)
```

### age_type ()
```{r}
plotCol(chronTS,ind = 10)
```

### core_name ()
```{r}
plotCol(chronTS,ind = 11)
```

### lab_id ()
```{r}
plotCol(chronTS,ind = 12)
```

### material_dated ()
```{r}
plotCol(chronTS,ind = 13)
```

### original_reference ()
```{r}
plotCol(chronTS,ind = 14)
```
