---
title: "JamesRossIsland.Mulvaney.2012"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 351
thisTS <- TS[which(udsn[i] == dsn)]
```
#JamesRossIsland.Mulvaney.2012

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](JamesRossIsland.Mulvaney.2012.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/JamesRossIsland.Mulvaney.2012.lpd)
            

[Download paleoData only (csv)](JamesRossIsland.Mulvaney.2012.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>GlacierIce
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Mulvaney, Robert"), list(name = "Abram, Nerilie J."), list(name = "Hindmarsh, Richard C. A."), list(name = "Arrowsmith, Carol"), list(name = "Fleet, Louise"), list(name = "Triest, Jack"), list(name = "Sime, Louise C."), list(name = "Alemany, Olivier"), list(name = "Foord, Susan"))
<p style="margin-left: 10px"><strong>journal: </strong>Nature
<p style="margin-left: 10px"><strong>volume: </strong>489
<p style="margin-left: 10px"><strong>pages: </strong>141-144
<p style="margin-left: 10px"><strong>title: </strong>Recent Antarctic Peninsula warming relative to Holocene climate and ice-shelf history
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-64.2017
<p style="margin-left: 0px"><strong>longitude: </strong>-57.685
<p style="margin-left: 0px"><strong>elevation: </strong>1542
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBb72433b0
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
<p style="margin-left: 10px"><strong>description: </strong>raw data. Snow depth
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB6607f37f
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>raw data JRI-1 age
</details>
<details style="margin-left: 10px">
<summary>dD (permil) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB54d1b98b
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>raw data. dD
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBed57e0c6
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3c95e135
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>ageMin (BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd4d9c643
<p style="margin-left: 10px"><strong>variableName: </strong>ageMin
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>ageMax (BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3b35cfd0
<p style="margin-left: 10px"><strong>variableName: </strong>ageMax
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>dD (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB4799a11b
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>tempErrorUpper (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3c678323
<p style="margin-left: 10px"><strong>variableName: </strong>tempErrorUpper
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>tempErrorLower (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB30522278
<p style="margin-left: 10px"><strong>variableName: </strong>tempErrorLower
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB6a2da494
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB03081f2f
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>ageMin (BP) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa475c836
<p style="margin-left: 10px"><strong>variableName: </strong>ageMin
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>ageMax (BP) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB60a4406e
<p style="margin-left: 10px"><strong>variableName: </strong>ageMax
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>dD (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB6bebc6fe
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>tempErrorUpper (degC) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd58ca44e
<p style="margin-left: 10px"><strong>variableName: </strong>tempErrorUpper
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>tempErrorLower (degC) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB367095cc
<p style="margin-left: 10px"><strong>variableName: </strong>tempErrorLower
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD (permil) [1-1]
```{r}
plotCol(thisTS,ind = 3)
```

### temperature (degC) [1-2]
```{r}
plotCol(thisTS,ind = 8)
```

### ageMin (BP) [1-2]
```{r}
plotCol(thisTS,ind = 5)
```

### ageMax (BP) [1-2]
```{r}
plotCol(thisTS,ind = 6)
```

### dD (permil) [1-2]
```{r}
plotCol(thisTS,ind = 7)
```

### tempErrorUpper (degC) [1-2]
```{r}
plotCol(thisTS,ind = 9)
```

### tempErrorLower (degC) [1-2]
```{r}
plotCol(thisTS,ind = 10)
```

### temperature (degC) [1-3]
```{r}
plotCol(thisTS,ind = 15)
```

### ageMin (BP) [1-3]
```{r}
plotCol(thisTS,ind = 12)
```

### ageMax (BP) [1-3]
```{r}
plotCol(thisTS,ind = 13)
```

### dD (permil) [1-3]
```{r}
plotCol(thisTS,ind = 14)
```

### tempErrorUpper (degC) [1-3]
```{r}
plotCol(thisTS,ind = 16)
```

### tempErrorLower (degC) [1-3]
```{r}
plotCol(thisTS,ind = 17)
```
