---
title: "Jenny.Larson.2016"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 356
thisTS <- TS[which(udsn[i] == dsn)]
```
#Jenny.Larson.2016

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](Jenny.Larson.2016.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/Jenny.Larson.2016.lpd)
            

[Download paleoData only (csv)](Jenny.Larson.2016.csv)
            

[Download chronData only (csv)](Jenny.Larson.2016-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>LakeSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/20128
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Larsen, Darren J."), list(name = "Finkenbinder, Matthew S."), list(name = "Abbott, Mark B."), list(name = "Ofstun, Adam R."))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>138
<p style="margin-left: 10px"><strong>pages: </strong>62-75
<p style="margin-left: 10px"><strong>title: </strong>Deglaciation and postglacial environmental changes in the Teton Mountain Range recorded at Jenny Lake, Grand Teton National Park, WY
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>43.7505
<p style="margin-left: 0px"><strong>longitude: </strong>-110.7343
<p style="margin-left: 0px"><strong>elevation: </strong>2070
<p style="margin-left: 0px"><strong>siteName: </strong>Jenny Lake
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB9c68af15
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>calendar years before present
</details>
<details style="margin-left: 10px">
<summary>clastic_flux (g/cm2/kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB9887226c
<p style="margin-left: 10px"><strong>variableName: </strong>clastic_flux
<p style="margin-left: 10px"><strong>units: </strong>g/cm2/kyr
<p style="margin-left: 10px"><strong>description: </strong>clasticflux Clastic fraction, , , g/cm2/kyr
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>ELA
<p style="margin-left: 20px"><strong>variableDetail: </strong>Glacier Extent
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dbd (g/cm3)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB501638f3
<p style="margin-left: 10px"><strong>variableName: </strong>dbd
<p style="margin-left: 10px"><strong>units: </strong>g/cm3
<p style="margin-left: 10px"><strong>description: </strong>dry bulk density, , , g/cm3
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>LOI (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB456b60bf
<p style="margin-left: 10px"><strong>variableName: </strong>LOI
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>loss-on-ignition at 550 degrees C
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>BSi (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB8ba728c4
<p style="margin-left: 10px"><strong>variableName: </strong>BSi
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Biogenic silica
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>clastic (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB705f9850
<p style="margin-left: 10px"><strong>variableName: </strong>clastic
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Clastic fraction
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d13C (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB4b5c6fb4
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>d13CVPDB d13C, , , per mil VPDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TOC (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB0e853c9d
<p style="margin-left: 10px"><strong>variableName: </strong>TOC
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Total organic carbon
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d15N (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBda148bc7
<p style="margin-left: 10px"><strong>variableName: </strong>d15N
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>d15N d15N, , , per mil N2
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C/N (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB5f7bbcf1
<p style="margin-left: 10px"><strong>variableName: </strong>C/N
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>c/n carbon/nitrogen ratio
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TOC_flux (g/cm2/kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa32e5310
<p style="margin-left: 10px"><strong>variableName: </strong>TOC_flux
<p style="margin-left: 10px"><strong>units: </strong>g/cm2/kyr
<p style="margin-left: 10px"><strong>description: </strong>Total Organic Carbon flux, , , g/cm2/kyr
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>LOI (g/cm2/kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB25692838
<p style="margin-left: 10px"><strong>variableName: </strong>LOI
<p style="margin-left: 10px"><strong>units: </strong>g/cm2/kyr
<p style="margin-left: 10px"><strong>description: </strong>oss-on-ignition flux, , , g/cm2/kyr
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>BSi (g/cm2/kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB6179cd65
<p style="margin-left: 10px"><strong>variableName: </strong>BSi
<p style="margin-left: 10px"><strong>units: </strong>g/cm2/kyr
<p style="margin-left: 10px"><strong>description: </strong>bio-siflux Biogenic Silica, , , g/cm2/kyr
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB7683dc1f
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (yrBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBaddb5f3a
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yrBP
<p style="margin-left: 10px"><strong>description: </strong>Radiocarbon age uncalibrated
</details>
<details style="margin-left: 10px">
<summary>core (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB05f29a47
<p style="margin-left: 10px"><strong>variableName: </strong>core
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>
<details style="margin-left: 10px">
<summary>material (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB9f553f13
<p style="margin-left: 10px"><strong>variableName: </strong>material
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>
<details style="margin-left: 10px">
<summary>error (yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB02b6b3d0
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>yr
<p style="margin-left: 10px"><strong>description: </strong>uncalibrated radiocarbon age error
</details>
<details style="margin-left: 10px">
<summary>type (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1a914d75
<p style="margin-left: 10px"><strong>variableName: </strong>type
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### clastic_flux (g/cm2/kyr)
```{r}
plotCol(thisTS,ind = 13)
```

### dbd (g/cm3)
```{r}
plotCol(thisTS,ind = 2)
```

### LOI (percent)
```{r}
plotCol(thisTS,ind = 3)
```

### BSi (percent)
```{r}
plotCol(thisTS,ind = 4)
```

### clastic (percent)
```{r}
plotCol(thisTS,ind = 5)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 6)
```

### TOC (percent)
```{r}
plotCol(thisTS,ind = 7)
```

### d15N (permil)
```{r}
plotCol(thisTS,ind = 8)
```

### C/N (missing)
```{r}
plotCol(thisTS,ind = 9)
```

### TOC_flux (g/cm2/kyr)
```{r}
plotCol(thisTS,ind = 10)
```

### LOI (g/cm2/kyr)
```{r}
plotCol(thisTS,ind = 11)
```

### BSi (g/cm2/kyr)
```{r}
plotCol(thisTS,ind = 12)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### age (yrBP)
```{r}
plotCol(chronTS,ind = 4)
```

### core (NA)
```{r}
plotCol(chronTS,ind = 1)
```

### material (NA)
```{r}
plotCol(chronTS,ind = 3)
```

### error (yr)
```{r}
plotCol(chronTS,ind = 5)
```

### type (NA)
```{r}
plotCol(chronTS,ind = 6)
```
