---
title: "JR244_GC528"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 368
thisTS <- TS[which(udsn[i] == dsn)]
```
#JR244_GC528

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](JR244_GC528.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/JR244_GC528.lpd)
            

[Download paleoData only (csv)](JR244_GC528.csv)
            

[Download chronData only (csv)](JR244_GC528-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>c("https://doi.org/10.1594/PANGAEA.878265", "https://doi.org/10.1594/PANGAEA.878266", "https://doi.org/10.1594/PANGAEA.856700", "https://doi.org/10.1594/PANGAEA.856698")
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Roberts, Jenny"), list(name = "Gottschalk, Julia"), list(name = "Skinner, Luke C."), list(name = "Peck, Victoria L."), list(name = "Kender, Sev"), list(name = "Elderfield, Henry"), list(name = "Waelbroeck, Claire"), list(name = "Vazquez Riveiros, Natalia"), list(name = "Hodell, David A."))
<p style="margin-left: 10px"><strong>journal: </strong>Proceedings of the National Academy of Sciences
<p style="margin-left: 10px"><strong>volume: </strong>113
<p style="margin-left: 10px"><strong>title: </strong>Evolution of South Atlantic density and chemical stratification across the last deglaciation
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Roberts, J."), list(name = "McCave, I.N."), list(name = "McClymont, E.L."), list(name = "Kender, S."), list(name = "Hillenbrand, C.-D."), list(name = "Matano, R."), list(name = "Hodell, D.A."), list(name = "Peck, V.L."))
<p style="margin-left: 10px"><strong>journal: </strong>Earth and Planetary Science Letters
<p style="margin-left: 10px"><strong>volume: </strong>474
<p style="margin-left: 10px"><strong>title: </strong>Deglacial changes in flow and frontal structure through the Drake Passage
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-53.01
<p style="margin-left: 0px"><strong>longitude: </strong>-58.04
<p style="margin-left: 0px"><strong>elevation: </strong>598
<p style="margin-left: 0px"><strong>siteName: </strong>JR244_GC528
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>ReqvJEBpgs0
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RHJ0EBiFhDx
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST [C]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>depth_merged (m) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RQHVSyi4JHE
<p style="margin-left: 10px"><strong>variableName: </strong>depth_merged
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>Uk37 (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RvHBFAaCObi
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>UK37
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C37.concentration (microg_g) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ryfbn7mcAuC
<p style="margin-left: 10px"><strong>variableName: </strong>C37.concentration
<p style="margin-left: 10px"><strong>units: </strong>microg_g
<p style="margin-left: 10px"><strong>description: </strong>Alkenone/sed [¬ug/g]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RptSZlFtG7s
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>depth_merged (m) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RTcv9IWPBB5
<p style="margin-left: 10px"><strong>variableName: </strong>depth_merged
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>IRD (no_g) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R6HPpfhnAtj
<p style="margin-left: 10px"><strong>variableName: </strong>IRD
<p style="margin-left: 10px"><strong>units: </strong>no_g
<p style="margin-left: 10px"><strong>description: </strong>IRD [#/g]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth_merged (m) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rf0ElXlACKI
<p style="margin-left: 10px"><strong>variableName: </strong>depth_merged
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RztUJUKSFIJ
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>U. bifurcata Œ¥18O [‚AE∞ PDB]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RZ5mqgIrf5b
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RxRae8If31Y
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>BWT [C]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>BWT
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>depth_merged (m) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RWmXsMyVI4W
<p style="margin-left: 10px"><strong>variableName: </strong>depth_merged
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>Mg/Ca (mmol_mol) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RvNIPNTs3fx
<p style="margin-left: 10px"><strong>variableName: </strong>Mg/Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>U. bifurcata Mg/Ca [mmol/mol]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RSpbVfm80gD
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>dateType (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RRPZnygEd0e
<p style="margin-left: 10px"><strong>variableName: </strong>dateType
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>measurementMaterial (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rlb1tnOpNni
<p style="margin-left: 10px"><strong>variableName: </strong>measurementMaterial
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>sensorSpecies (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rm5HL8kjmao
<p style="margin-left: 10px"><strong>variableName: </strong>sensorSpecies
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>age14C (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RjD415535hU
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>ageerror (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RXwPrpmlKfv
<p style="margin-left: 10px"><strong>variableName: </strong>ageerror
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>reservoirAge (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RAyx9BbjV8h
<p style="margin-left: 10px"><strong>variableName: </strong>reservoirAge
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>reservoirAgeUncertainty (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rc2WcBqNlKY
<p style="margin-left: 10px"><strong>variableName: </strong>reservoirAgeUncertainty
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 5)
```

### depth_merged (m)
```{r}
plotCol(thisTS,ind = 1)
```

### Uk37 (missing)
```{r}
plotCol(thisTS,ind = 3)
```

### C37.concentration (microg_g)
```{r}
plotCol(thisTS,ind = 4)
```

### depth_merged (m)
```{r}
plotCol(thisTS,ind = 6)
```

### IRD (no_g)
```{r}
plotCol(thisTS,ind = 8)
```

### depth_merged (m)
```{r}
plotCol(thisTS,ind = 9)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 10)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 14)
```

### depth_merged (m)
```{r}
plotCol(thisTS,ind = 11)
```

### Mg/Ca (mmol_mol)
```{r}
plotCol(thisTS,ind = 13)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### dateType (unitless)
```{r}
plotCol(chronTS,ind = 1)
```

### measurementMaterial (unitless)
```{r}
plotCol(chronTS,ind = 3)
```

### sensorSpecies (unitless)
```{r}
plotCol(chronTS,ind = 4)
```

### age14C (kyr)
```{r}
plotCol(chronTS,ind = 5)
```

### ageerror (kyr)
```{r}
plotCol(chronTS,ind = 6)
```

### reservoirAge (kyr)
```{r}
plotCol(chronTS,ind = 7)
```

### reservoirAgeUncertainty (kyr)
```{r}
plotCol(chronTS,ind = 8)
```
