---
title: "KF16"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 377
thisTS <- TS[which(udsn[i] == dsn)]
```
#KF16

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](KF16.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/KF16.lpd)
            

[Download paleoData only (csv)](KF16.csv)
            

[Download chronData only (csv)](KF16-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>c("https://doi.org/10.1594/PANGAEA.868107", "https://doi.org/10.1594/PANGAEA.868105", "https://doi.org/10.1594/PANGAEA.892931", "https://doi.org/10.1594/PANGAEA.892929", "https://doi.org/10.1594/PANGAEA.892934")
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Repschlaeger, Janne"), list(name = "Garbe-Schoenberg, Dieter"), list(name = "Weinelt, Mara"), list(name = "Schneider, Ralph"))
<p style="margin-left: 10px"><strong>journal: </strong>Climate of the Past
<p style="margin-left: 10px"><strong>volume: </strong>13
<p style="margin-left: 10px"><strong>title: </strong>Holocene evolution of the North Atlantic subsurface transport
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Repschlaeger, Janne"), list(name = "Weinelt, Mara"), list(name = "Kinkel, Hanno"), list(name = "Andersen, Nils"), list(name = "Garbe-Schoenberg, Dieter"), list(name = "Schwab, Christian"))
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>30
<p style="margin-left: 10px"><strong>title: </strong>Response of the subtropical North Atlantic surface hydrography on deglacial and Holocene AMOC changes
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Repschläger, Janne"), list(name = "Weinelt, Mara"), list(name = "Andersen, Nils"), list(name = "Garbe-Schönberg, Dieter"), list(name = "Schneider, Ralph"))
<p style="margin-left: 10px"><strong>journal: </strong>Earth and Planetary Science Letters
<p style="margin-left: 10px"><strong>volume: </strong>425
<p style="margin-left: 10px"><strong>title: </strong>Northern source for Deglacial and Holocene deepwater composition changes in the Eastern North Atlantic Basin
</details>
<details style="margin-left: 10px">
<summary>pub4</summary>
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>37.999
<p style="margin-left: 0px"><strong>longitude: </strong>-31.1283
<p style="margin-left: 0px"><strong>elevation: </strong>-3050
<p style="margin-left: 0px"><strong>siteName: </strong>KF16
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RXrJGPqff4R
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RX03LtcSUZN
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>planktic.MgCa (mmol_mol) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ru95CWJK5VD
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.MgCa
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>G. truncatulinoides Mg/Ca [mmol/mol]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R7Zxl09wbiJ
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SubT (G. truncatulinoides, calibrat...)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>T
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RhBONSQE6DY
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G. truncatulinoides18O
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rdz7iTSMtxT
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rn0Arg5y0ws
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>planktic.MgCa (mmol_mol) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1mwGXk5VZK
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.MgCa
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>G. ruber w Mg/Ca
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RflFSKclVuu
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST (derived from Mg/Ca G. ruber w...)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>T
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RJ5DhS9AQ4K
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G. ruber w d18O
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RF5h92JzpCv
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R8FuJPuy7Mz
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RHI7VXbp76V
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>M. affinis d13C (250-315¬um)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RexATEd71ax
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>M. affinis d18O [PDB] (250-315¬um)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RQAlhkrOPSw
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rn6iHjf0FUm
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1ZGPZ6TGGz
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>C. wuellerstorfi d13C [PDB] (>315 ¬um)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RsZRpQO7fh7
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>C. wuellerstorfi d18O [PDB] (>315 ¬um)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ry00VZAOqEz
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RCJMnwJLBUJ
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age [ka BP]
</details>
<details style="margin-left: 10px">
<summary>Mg/Ca (mmol_mol) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RlvvNpODxJQ
<p style="margin-left: 10px"><strong>variableName: </strong>Mg/Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>C. wuellerstorfi Mg/Ca [mmol/mol]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>deep.temp (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RC6A6sRIxfz
<p style="margin-left: 10px"><strong>variableName: </strong>deep.temp
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>BWT (C. wuellerstorfi 250-315¬um; H...)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>T
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Mg/Ca (mmol_mol) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rp8UFMoI5XP
<p style="margin-left: 10px"><strong>variableName: </strong>Mg/Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>M. barleeanus Mg/Ca [mmol/mol]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>deep.temp (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RO9YQwL1lTC
<p style="margin-left: 10px"><strong>variableName: </strong>deep.temp
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>BWT (M. barleanum 250-315¬um; Heale...)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Mg/Ca (mmol_mol) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RJW0iao90y0
<p style="margin-left: 10px"><strong>variableName: </strong>Mg/Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>M. affinis Mg/Ca [mmol/mol] (250-315¬um)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>deep.temp (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RoRLVjheZxc
<p style="margin-left: 10px"><strong>variableName: </strong>deep.temp
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>BWT (M. affinis 250-315¬um; Healey ...)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>T
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ri2npuKXkx0
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>dateType ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RhgvvWlAzsW
<p style="margin-left: 10px"><strong>variableName: </strong>dateType
</details>
<details style="margin-left: 10px">
<summary>measurementMaterial ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RhwNqwvKone
<p style="margin-left: 10px"><strong>variableName: </strong>measurementMaterial
</details>
<details style="margin-left: 10px">
<summary>sensorSpecies ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rrd6FImWfui
<p style="margin-left: 10px"><strong>variableName: </strong>sensorSpecies
</details>
<details style="margin-left: 10px">
<summary>age14C (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RnE9AgMCJep
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CUncertainty (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RYIgMqniqti
<p style="margin-left: 10px"><strong>variableName: </strong>age14CUncertainty
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>rejected ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RK0ueRqZOgz
<p style="margin-left: 10px"><strong>variableName: </strong>rejected
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### planktic.MgCa (mmol_mol)
```{r}
plotCol(thisTS,ind = 3)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 4)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 5)
```

### planktic.MgCa (mmol_mol)
```{r}
plotCol(thisTS,ind = 8)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 9)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 10)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 13)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 14)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 17)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 18)
```

### Mg/Ca (mmol_mol)
```{r}
plotCol(thisTS,ind = 21)
```

### deep.temp (degC)
```{r}
plotCol(thisTS,ind = 22)
```

### Mg/Ca (mmol_mol)
```{r}
plotCol(thisTS,ind = 23)
```

### deep.temp (degC)
```{r}
plotCol(thisTS,ind = 24)
```

### Mg/Ca (mmol_mol)
```{r}
plotCol(thisTS,ind = 25)
```

### deep.temp (degC)
```{r}
plotCol(thisTS,ind = 26)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### dateType ()
```{r}
plotCol(chronTS,ind = 1)
```

### measurementMaterial ()
```{r}
plotCol(chronTS,ind = 3)
```

### sensorSpecies ()
```{r}
plotCol(chronTS,ind = 4)
```

### age14C (kyr)
```{r}
plotCol(chronTS,ind = 5)
```

### age14CUncertainty (kyr)
```{r}
plotCol(chronTS,ind = 6)
```

### rejected ()
```{r}
plotCol(chronTS,ind = 7)
```
