---
title: "MD01-2416.Sarnthien.2004"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 517
thisTS <- TS[which(udsn[i] == dsn)]
```
#MD01-2416.Sarnthien.2004

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](MD01-2416.Sarnthien.2004.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/MD01-2416.Sarnthien.2004.lpd)
            

[Download paleoData only (csv)](MD01-2416.Sarnthien.2004.csv)
            

[Download chronData only (csv)](MD01-2416.Sarnthien.2004-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://doi.pangaea.de/10.1594/PANGAEA.738119
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Sarnthein, M."), list(name = "Gebhardt, H."), list(name = "Kiefer, T."), list(name = "Kucera, M."), list(name = "Cook, M."), list(name = "Erlenkeuser, H."))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>23
<p style="margin-left: 10px"><strong>pages: </strong>2089-2099
<p style="margin-left: 10px"><strong>title: </strong>Mid Holocene origin of the sea-surface salinity low in the subarctic North Pacific
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>51.268
<p style="margin-left: 0px"><strong>longitude: </strong>167.725
<p style="margin-left: 0px"><strong>elevation: </strong>-2317
<p style="margin-left: 0px"><strong>siteName: </strong>MD01-2416
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB16e99bf0
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB4e78b807
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB87ba36d7
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5c8693b4
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>core (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDef1e7cbe
<p style="margin-left: 10px"><strong>variableName: </strong>core
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depthComp (cm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7ee9d5c5
<p style="margin-left: 10px"><strong>variableName: </strong>depthComp
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>stdDev (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD48c793a5
<p style="margin-left: 10px"><strong>variableName: </strong>stdDev
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>year (AD) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa76c05c3
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB062a4561
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBafabe535
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2d83141e
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>event (missing) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD3eee458e
<p style="margin-left: 10px"><strong>variableName: </strong>event
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depthComp (cm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD19d1e900
<p style="margin-left: 10px"><strong>variableName: </strong>depthComp
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDace97b46
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5aa43424
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>
<details style="margin-left: 10px">
<summary>event (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD670c858c
<p style="margin-left: 10px"><strong>variableName: </strong>event
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>depth_comp (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDcba637c2
<p style="margin-left: 10px"><strong>variableName: </strong>depth_comp
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>sample (yr BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD0c53c14c
<p style="margin-left: 10px"><strong>variableName: </strong>sample
<p style="margin-left: 10px"><strong>units: </strong>yr BP
</details>
<details style="margin-left: 10px">
<summary>error (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD17a78f3d
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>calibrated (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD59818964
<p style="margin-left: 10px"><strong>variableName: </strong>calibrated
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC) [1-1]
```{r}
plotCol(thisTS,ind = 6)
```

### core (missing) [1-1]
```{r}
plotCol(thisTS,ind = 1)
```

### depthComp (cm) [1-1]
```{r}
plotCol(thisTS,ind = 5)
```

### stdDev (missing) [1-1]
```{r}
plotCol(thisTS,ind = 7)
```

### temperature (degC) [2-1]
```{r}
plotCol(thisTS,ind = 13)
```

### event (missing) [2-1]
```{r}
plotCol(thisTS,ind = 8)
```

### depthComp (cm) [2-1]
```{r}
plotCol(thisTS,ind = 12)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (m)
```{r}
plotCol(chronTS,ind = 2)
```

### age (yr)
```{r}
plotCol(chronTS,ind = 5)
```

### event (unitless)
```{r}
plotCol(chronTS,ind = 1)
```

### depth_comp (m)
```{r}
plotCol(chronTS,ind = 3)
```

### sample (yr BP)
```{r}
plotCol(chronTS,ind = 4)
```

### error (unitless)
```{r}
plotCol(chronTS,ind = 6)
```

### calibrated (unitless)
```{r}
plotCol(chronTS,ind = 7)
```
