---
title: "MD06_3067"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 535
thisTS <- TS[which(udsn[i] == dsn)]
```
#MD06_3067

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](MD06_3067.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/MD06_3067.lpd)
            

[Download paleoData only (csv)](MD06_3067.csv)
            

[Download chronData only (csv)](MD06_3067-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://doi.pangaea.de/10.1594/PANGAEA.770282
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Bolliet, Timothe"), list(name = "Holbourn, Ann"), list(name = "Kuhnt, Wolfgang"), list(name = "Laj, Carlo"), list(name = "Kissel, Catherine"), list(name = "Beaufort, Luc"), list(name = "Kienast, Markus"), list(name = "Andersen, Nils"), list(name = "Garbe-Schoenberg, Dieter"))
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>26
<p style="margin-left: 10px"><strong>title: </strong>Mindanao Dome variability over the last 160 kyr: Episodic glacial cooling of the West Pacific Warm Pool
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>6.5143
<p style="margin-left: 0px"><strong>longitude: </strong>126.4977
<p style="margin-left: 0px"><strong>elevation: </strong>-1575
<p style="margin-left: 0px"><strong>siteName: </strong>MD06_3067
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rnn8Fd0Gxjj
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RykLJnjwx5v
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RyTmrAjXXbI
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_1_12_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RKz0xLW2LFh
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>TT_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RaVVn9kSuFx
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>Foram_bent_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RFT96c8LLtL
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G_ruber_w_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.MgCa (mmol_mol)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R89VJHY12Yf
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.MgCa
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>G_ruber_w_Mg_Ca_mmol_mol
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.MgCa (mmol_mol)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RJS1jFCVr5O
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.MgCa
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>P_obliqu_Mg_Ca_mmol_mol
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Re5WiuBBnzl
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>P_obliqu_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RzMcwdeRreH
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>dateType ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R689rft47sh
<p style="margin-left: 10px"><strong>variableName: </strong>dateType
</details>
<details style="margin-left: 10px">
<summary>thickness (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RwgZhwGR6wH
<p style="margin-left: 10px"><strong>variableName: </strong>thickness
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>measurementMaterial ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RAzrrNDBlMm
<p style="margin-left: 10px"><strong>variableName: </strong>measurementMaterial
</details>
<details style="margin-left: 10px">
<summary>sensorSpecies ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RahTfNFdhMq
<p style="margin-left: 10px"><strong>variableName: </strong>sensorSpecies
</details>
<details style="margin-left: 10px">
<summary>labID ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rsb7bhnG9OL
<p style="margin-left: 10px"><strong>variableName: </strong>labID
</details>
<details style="margin-left: 10px">
<summary>age14C (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rl8SHTeEuEu
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CHi (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R3mgyxjsLct
<p style="margin-left: 10px"><strong>variableName: </strong>age14CHi
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CLow (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RgINTdDuDX3
<p style="margin-left: 10px"><strong>variableName: </strong>age14CLow
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>reservoirAge (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R8nIOS1ko7h
<p style="margin-left: 10px"><strong>variableName: </strong>reservoirAge
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>notes ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RnQjxm2OBqw
<p style="margin-left: 10px"><strong>variableName: </strong>notes
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 5)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 7)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 3)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 4)
```

### planktic.MgCa (mmol_mol)
```{r}
plotCol(thisTS,ind = 6)
```

### planktic.MgCa (mmol_mol)
```{r}
plotCol(thisTS,ind = 8)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 9)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### dateType ()
```{r}
plotCol(chronTS,ind = 1)
```

### thickness (cm)
```{r}
plotCol(chronTS,ind = 3)
```

### measurementMaterial ()
```{r}
plotCol(chronTS,ind = 4)
```

### sensorSpecies ()
```{r}
plotCol(chronTS,ind = 5)
```

### labID ()
```{r}
plotCol(chronTS,ind = 6)
```

### age14C (kyr)
```{r}
plotCol(chronTS,ind = 7)
```

### age14CHi (kyr)
```{r}
plotCol(chronTS,ind = 8)
```

### age14CLow (kyr)
```{r}
plotCol(chronTS,ind = 9)
```

### reservoirAge (kyr)
```{r}
plotCol(chronTS,ind = 10)
```

### notes ()
```{r}
plotCol(chronTS,ind = 11)
```
