---
title: "O2kLR-Tagusmudpatc.Abrantes.2005"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 636
thisTS <- TS[which(udsn[i] == dsn)]
```
#O2kLR-Tagusmudpatc.Abrantes.2005

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](O2kLR-Tagusmudpatc.Abrantes.2005.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/O2kLR-Tagusmudpatc.Abrantes.2005.lpd)
            

[Download paleoData only (csv)](O2kLR-Tagusmudpatc.Abrantes.2005.csv)
            

[Download chronData only (csv)](O2kLR-Tagusmudpatc.Abrantes.2005-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Abrantes, F."), list(name = "Lebreiro, S."), list(name = "Rodrigues, T."), list(name = "Gil, I."), list(name = "Bartels-Jonsdottir, H."), list(name = "Oliveira, P."), list(name = "Kissel, C."), list(name = "Grimalt, J.O."))
<p style="margin-left: 10px"><strong>citeKey: </strong>abrantes2005shallowmarinesedimentcore
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>24
<p style="margin-left: 10px"><strong>pages: </strong>2477-2494
<p style="margin-left: 10px"><strong>title: </strong>Shallow-marine sediment cores record climate variability and earthquake activity off Lisbon (Portugal) for the last 2000 years
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "McGregor, Helen V."), list(name = "Evans, Michael N."), list(name = "Goosse, Hugues"), list(name = "Leduc, Guillaume"), list(name = "Martrat, Belen"), list(name = "Addison, Jason A."), list(name = "Mortyn, P. Graham"), list(name = "Oppo, Delia W."), list(name = "Seidenkrantz, Marit-Solveig"), list(name = "Sicre, Marie-Alexandrine"), list(name = "Phipps, Steven J."), list(name = "Selvaraj, Kandasamy"), list(name = "Thirumalai, Kaustubh"), list(name = "Filipsson, Helena L."), list(
    name = "Ersek, Vasile"))
<p style="margin-left: 10px"><strong>citeKey: </strong>abrantes2005shallowmarinesedimentcore
<p style="margin-left: 10px"><strong>journal: </strong>Nature Geoscience
<p style="margin-left: 10px"><strong>volume: </strong>8
<p style="margin-left: 10px"><strong>pages: </strong>2477-2494
<p style="margin-left: 10px"><strong>title: </strong>Robust global ocean cooling trend for the pre-industrial Common Era
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>EU
<p style="margin-left: 10px"><strong>grant: </strong>HOLSMEER (EVK2-CT-2000-00060) and PACLIVA (EVK2-CT2002-00143)
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>38.556
<p style="margin-left: 0px"><strong>longitude: </strong>-9.3498
<p style="margin-left: 0px"><strong>elevation: </strong>-90
<p style="margin-left: 0px"><strong>siteName: </strong>Tagus mud patch, southern portuguese margin, North Atlantic
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>O2kLR
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rv8I4ktVj1P
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R0zYscwpJD1
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD28794972xxx
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth in corresponding sediment core
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1028d531xxx
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>LOOKUP
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>core (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD05340dbbxxx
<p style="margin-left: 10px"><strong>variableName: </strong>core
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>ID number of sediment core in 3-core splice
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Uk37 (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD637d78bb
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>native data (alkenone ratio) that SST is calculated from
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>notes (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD06e76fcf
<p style="margin-left: 10px"><strong>variableName: </strong>notes
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>All O2K-LR records have been quality-controlled according to protocols published in Nature Geoscience supplement note 3 cores spliced together
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>year (AD) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RxCGWMpCtar
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RaAIkROObAC
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5f055b7e
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH8d2ba08f
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Alkenone calibration to SST
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>core (missing) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD947b76ac
<p style="margin-left: 10px"><strong>variableName: </strong>core
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Uk37 (missing) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH1b998771
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>native data (alkenone ratio) used for calculating SST
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>notes (missing) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH479ef1a9
<p style="margin-left: 10px"><strong>variableName: </strong>notes
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>Original dataset from Abrantes et al. (2005) that was used in the O2K-LR analysis NOTE 3 cores spliced together, the three records are presented after each other, order: Core PO287-26G, PO287-26B, D13902
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBe5d31aed
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (yr bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB2134ddcb
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr bp
</details>
<details style="margin-left: 10px">
<summary>error (yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd672bef4
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>
<details style="margin-left: 10px">
<summary>type (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB459c2a60
<p style="margin-left: 10px"><strong>variableName: </strong>type
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>material (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB59870013
<p style="margin-left: 10px"><strong>variableName: </strong>material
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>rejected (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB03064466
<p style="margin-left: 10px"><strong>variableName: </strong>rejected
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC) [1-1]
```{r}
plotCol(thisTS,ind = 5)
```

### core (missing) [1-1]
```{r}
plotCol(thisTS,ind = 1)
```

### Uk37 (missing) [1-1]
```{r}
plotCol(thisTS,ind = 6)
```

### notes (missing) [1-1]
```{r}
plotCol(thisTS,ind = 7)
```

### temperature (degC) [2-1]
```{r}
plotCol(thisTS,ind = 12)
```

### core (missing) [2-1]
```{r}
plotCol(thisTS,ind = 8)
```

### Uk37 (missing) [2-1]
```{r}
plotCol(thisTS,ind = 13)
```

### notes (missing) [2-1]
```{r}
plotCol(thisTS,ind = 14)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 1)
```

### age (yr bp)
```{r}
plotCol(chronTS,ind = 2)
```

### error (yr)
```{r}
plotCol(chronTS,ind = 3)
```

### type (unitless)
```{r}
plotCol(chronTS,ind = 4)
```

### material (unitless)
```{r}
plotCol(chronTS,ind = 5)
```

### rejected (unitless)
```{r}
plotCol(chronTS,ind = 6)
```
