---
title: "SihailongwanMaarLake.Stebich.2015"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 752
thisTS <- TS[which(udsn[i] == dsn)]
```
#SihailongwanMaarLake.Stebich.2015

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SihailongwanMaarLake.Stebich.2015.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/SihailongwanMaarLake.Stebich.2015.lpd)
            

[Download paleoData only (csv)](SihailongwanMaarLake.Stebich.2015.csv)
            

[Download chronData only (csv)](SihailongwanMaarLake.Stebich.2015-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>LakeSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://doi.org/10.1594/PANGAEA.852703
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Stebich, Martina"), list(name = "Rehfeld, Kira"), list(name = "Schluetz, Frank"), list(name = "Tarasov, Pavel E."), list(name = "Liu, Jiaqi"), list(name = "Mingram, Jens"))
<p style="margin-left: 10px"><strong>citeKey: </strong>needs0needsatitle
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>124
<p style="margin-left: 10px"><strong>title: </strong>Holocene vegetation and climate dynamics of NE China based on the pollen record from Sihailongwan Maar Lake
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>42.2833
<p style="margin-left: 0px"><strong>longitude: </strong>126.6
<p style="margin-left: 0px"><strong>elevation: </strong>797
<p style="margin-left: 0px"><strong>siteName: </strong>Sihailongwan Maar
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RthIVSTkLea
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RzJCko0ijyu
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>WMT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD575ea390
<p style="margin-left: 10px"><strong>variableName: </strong>WMT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, warmest month [   C] (WMT) * PI: Rehfeld, Kira (https://orcid.org/0000-0002-9442-5362, kira.rehfeld@awi.de, http://www.awi.de/en/about-us/organisation/staff/kira-rehfeld.html) * METHOD: Calculated
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>warmest
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MAP (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD6fdee25b
<p style="margin-left: 10px"><strong>variableName: </strong>MAP
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean [mm] (MAP) * PI: Rehfeld, Kira (https://orcid.org/0000-0002-9442-5362, kira.rehfeld@awi.de, http://www.awi.de/en/about-us/organisation/staff/kira-rehfeld.html) * METHOD: Calculated
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>monsoon
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>WMT1-sigma (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDc06a0727
<p style="margin-left: 10px"><strong>variableName: </strong>WMT1-sigma
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>WMT2-sigma (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD36d0a4c4
<p style="margin-left: 10px"><strong>variableName: </strong>WMT2-sigma
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MAP1-sigma (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9d3530a4
<p style="margin-left: 10px"><strong>variableName: </strong>MAP1-sigma
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MAP2-sigma (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD041170d1
<p style="margin-left: 10px"><strong>variableName: </strong>MAP2-sigma
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean, standard deviation  COMMENT: 2-sigma
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>BS (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD827daf67
<p style="margin-left: 10px"><strong>variableName: </strong>BS
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>Biome Scores, reconstructed (BS) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Calculated * COMMENT: Temperate deciduous forests (TEDE)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>BS_COMX (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDcea2543a
<p style="margin-left: 10px"><strong>variableName: </strong>BS_COMX
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>iome Scores, reconstructed (BS) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Calculated * COMMENT: Cool mixed forests (COMX)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>BS_Landscape_Openness (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5fd9d599
<p style="margin-left: 10px"><strong>variableName: </strong>BS_Landscape_Openness
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>ome Scores, reconstructed (BS) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Calculated * COMMENT: Landscape Openness
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>age ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD571cda0e
<p style="margin-left: 10px"><strong>variableName: </strong>age
</details>
<details style="margin-left: 10px">
<summary>dummy2 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD04672f2b
<p style="margin-left: 10px"><strong>variableName: </strong>dummy2
</details>
<details style="margin-left: 10px">
<summary>dummy3 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD951fd267
<p style="margin-left: 10px"><strong>variableName: </strong>dummy3
</details>
<details style="margin-left: 10px">
<summary>dummy4 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDbdfb9d6e
<p style="margin-left: 10px"><strong>variableName: </strong>dummy4
</details>
<details style="margin-left: 10px">
<summary>dummy5 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDce71e9b7
<p style="margin-left: 10px"><strong>variableName: </strong>dummy5
</details>
<details style="margin-left: 10px">
<summary>dummy6 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf2b2197c
<p style="margin-left: 10px"><strong>variableName: </strong>dummy6
</details>
<details style="margin-left: 10px">
<summary>dummy7 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD007b3779
<p style="margin-left: 10px"><strong>variableName: </strong>dummy7
</details>
<details style="margin-left: 10px">
<summary>dummy8 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD0438be0d
<p style="margin-left: 10px"><strong>variableName: </strong>dummy8
</details>
<details style="margin-left: 10px">
<summary>dummy9 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd7612a9a
<p style="margin-left: 10px"><strong>variableName: </strong>dummy9
</details>
<details style="margin-left: 10px">
<summary>dummy10 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7c7e19c5
<p style="margin-left: 10px"><strong>variableName: </strong>dummy10
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### WMT (degC)
```{r}
plotCol(thisTS,ind = 1)
```

### MAP (mm)
```{r}
plotCol(thisTS,ind = 6)
```

### WMT1-sigma (missing)
```{r}
plotCol(thisTS,ind = 4)
```

### WMT2-sigma (missing)
```{r}
plotCol(thisTS,ind = 5)
```

### MAP1-sigma (missing)
```{r}
plotCol(thisTS,ind = 7)
```

### MAP2-sigma (missing)
```{r}
plotCol(thisTS,ind = 8)
```

### BS (missing)
```{r}
plotCol(thisTS,ind = 9)
```

### BS_COMX (missing)
```{r}
plotCol(thisTS,ind = 10)
```

### BS_Landscape_Openness (missing)
```{r}
plotCol(thisTS,ind = 11)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### age ()
```{r}
plotCol(chronTS,ind = 1)
```

### dummy2 ()
```{r}
plotCol(chronTS,ind = 2)
```

### dummy3 ()
```{r}
plotCol(chronTS,ind = 3)
```

### dummy4 ()
```{r}
plotCol(chronTS,ind = 4)
```

### dummy5 ()
```{r}
plotCol(chronTS,ind = 5)
```

### dummy6 ()
```{r}
plotCol(chronTS,ind = 6)
```

### dummy7 ()
```{r}
plotCol(chronTS,ind = 7)
```

### dummy8 ()
```{r}
plotCol(chronTS,ind = 8)
```

### dummy9 ()
```{r}
plotCol(chronTS,ind = 9)
```

### dummy10 ()
```{r}
plotCol(chronTS,ind = 10)
```
