---
title: "StaroselskyMoch.Pollen.Russia"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 782
thisTS <- TS[which(udsn[i] == dsn)]
```
#StaroselskyMoch.Pollen.Russia

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](StaroselskyMoch.Pollen.Russia.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/StaroselskyMoch.Pollen.Russia.lpd)
            

[Download paleoData only (csv)](StaroselskyMoch.Pollen.Russia.csv)
            

[Download chronData only (csv)](StaroselskyMoch.Pollen.Russia-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>Peat
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Novenko, E Yu"), list(name = "Tsyganov, A N"), list(name = "Olchev, A V"))
<p style="margin-left: 10px"><strong>journal: </strong>IOP Conference Series: Earth and Environmental Science
<p style="margin-left: 10px"><strong>volume: </strong>107
<p style="margin-left: 10px"><strong>title: </strong>Palaeoecological data as a tool to predict possible future vegetation changes in the boreal forest zone of European Russia: a case study from the Central Forest Biosphere Reserve
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Novenko, E.Yu."), list(name = "Volkova, E.M."), list(name = "Nosova, N.B."), list(name = "Zuganova, I.S."))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary International
<p style="margin-left: 10px"><strong>volume: </strong>207
<p style="margin-left: 10px"><strong>title: </strong>Late Glacial and Holocene landscape dynamics in the southern taiga zone of East European Plain according to pollen and macrofossil records from the Central Forest State Reserve (Valdai Hills, Russia)
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>56.2855
<p style="margin-left: 0px"><strong>longitude: </strong>32.0278
<p style="margin-left: 0px"><strong>elevation: </strong>255
<p style="margin-left: 0px"><strong>siteName: </strong>Staroselsky Moch
<p style="margin-left: 0px"><strong>country: </strong>Russia
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>ROBywlT0RS9
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RCrOKh2Jpoh
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>age (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLucCsGcjsr
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>missing
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R60yDfufGWZ
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE-1
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Tann
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RSkOVUdjmEp
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE-2
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>2
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RWzl4NCma8r
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE-3
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperatureComposite (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RAftFZHtDFF
<p style="margin-left: 10px"><strong>variableName: </strong>temperatureComposite
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Tann; 2
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>OriginalSampleID (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rrn8wdn4aUB
<p style="margin-left: 10px"><strong>variableName: </strong>OriginalSampleID
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>ageMin (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RufLzdKYVdj
<p style="margin-left: 10px"><strong>variableName: </strong>ageMin
<p style="margin-left: 10px"><strong>units: </strong>missing
</details>
<details style="margin-left: 10px">
<summary>uncertainty (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RCs1KA5yQee
<p style="margin-left: 10px"><strong>variableName: </strong>uncertainty
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>uncertainty (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RS1XFxnNT8Z
<p style="margin-left: 10px"><strong>variableName: </strong>uncertainty
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>reliable (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RcsEIxLAXUU
<p style="margin-left: 10px"><strong>variableName: </strong>reliable
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>uncertainty (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rdv8jcWlwA0
<p style="margin-left: 10px"><strong>variableName: </strong>uncertainty
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>uncertainty (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rh9xTY4jOKk
<p style="margin-left: 10px"><strong>variableName: </strong>uncertainty
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>reliable (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RT5Fy3hYuiW
<p style="margin-left: 10px"><strong>variableName: </strong>reliable
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>uncertainty (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RZOr35YNbAb
<p style="margin-left: 10px"><strong>variableName: </strong>uncertainty
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>uncertainty (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RSLxWoNbSxn
<p style="margin-left: 10px"><strong>variableName: </strong>uncertainty
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>reliable (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLL6eHMlmT7
<p style="margin-left: 10px"><strong>variableName: </strong>reliable
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>TopDepthofDate (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RR3VsX1mdCv
<p style="margin-left: 10px"><strong>variableName: </strong>TopDepthofDate
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>BottomDepthofDate (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RlU3Hqdk94K
<p style="margin-left: 10px"><strong>variableName: </strong>BottomDepthofDate
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>DateType ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RZuB7INiqGC
<p style="margin-left: 10px"><strong>variableName: </strong>DateType
</details>
<details style="margin-left: 10px">
<summary>DateBP ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R9G2u3ckvEb
<p style="margin-left: 10px"><strong>variableName: </strong>DateBP
</details>
<details style="margin-left: 10px">
<summary>Uncertaintyplus ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1QCxczVkeJ
<p style="margin-left: 10px"><strong>variableName: </strong>Uncertaintyplus
</details>
<details style="margin-left: 10px">
<summary>Uncertaintyminus ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RYJxqOym9fX
<p style="margin-left: 10px"><strong>variableName: </strong>Uncertaintyminus
</details>
<details style="margin-left: 10px">
<summary>IncludeYN ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RVmJOlAatY9
<p style="margin-left: 10px"><strong>variableName: </strong>IncludeYN
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 6)
```

### temperature (missing)
```{r}
plotCol(thisTS,ind = 10)
```

### temperature (missing)
```{r}
plotCol(thisTS,ind = 14)
```

### temperatureComposite (degC)
```{r}
plotCol(thisTS,ind = 18)
```

### OriginalSampleID (missing)
```{r}
plotCol(thisTS,ind = 1)
```

### ageMin (missing)
```{r}
plotCol(thisTS,ind = 4)
```

### uncertainty (missing)
```{r}
plotCol(thisTS,ind = 7)
```

### uncertainty (missing)
```{r}
plotCol(thisTS,ind = 8)
```

### reliable (missing)
```{r}
plotCol(thisTS,ind = 9)
```

### uncertainty (missing)
```{r}
plotCol(thisTS,ind = 11)
```

### uncertainty (missing)
```{r}
plotCol(thisTS,ind = 12)
```

### reliable (missing)
```{r}
plotCol(thisTS,ind = 13)
```

### uncertainty (missing)
```{r}
plotCol(thisTS,ind = 15)
```

### uncertainty (missing)
```{r}
plotCol(thisTS,ind = 16)
```

### reliable (missing)
```{r}
plotCol(thisTS,ind = 17)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### TopDepthofDate (cm)
```{r}
plotCol(chronTS,ind = 1)
```

### BottomDepthofDate (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### DateType ()
```{r}
plotCol(chronTS,ind = 3)
```

### DateBP ()
```{r}
plotCol(chronTS,ind = 4)
```

### Uncertaintyplus ()
```{r}
plotCol(chronTS,ind = 5)
```

### Uncertaintyminus ()
```{r}
plotCol(chronTS,ind = 6)
```

### IncludeYN ()
```{r}
plotCol(chronTS,ind = 7)
```
