---
title: "TN062-0550.Addison.2018"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 817
thisTS <- TS[which(udsn[i] == dsn)]
```
#TN062-0550.Addison.2018

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](TN062-0550.Addison.2018.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/TN062-0550.Addison.2018.lpd)
            

[Download paleoData only (csv)](TN062-0550.Addison.2018.csv)
            

[Download chronData only (csv)](TN062-0550.Addison.2018-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Addison, Jason A."), list(name = "Barron, John"), list(name = "Finney, Bruce"), list(name = "Kusler, Jennifer"), list(name = "Bukry, David"), list(name = "Heusser, Linda E."), list(name = "Alexander, Clark R."))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary International
<p style="margin-left: 10px"><strong>volume: </strong>469
<p style="margin-left: 10px"><strong>pages: </strong>96-108
<p style="margin-left: 10px"><strong>title: </strong>A Holocene record of ocean productivity and upwelling from the northern California continental slope
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>40.8656
<p style="margin-left: 0px"><strong>longitude: </strong>-124.573
<p style="margin-left: 0px"><strong>elevation: </strong>-569
<p style="margin-left: 0px"><strong>siteName: </strong>TN062-0550
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB781080f6
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB733ba661
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>age_calyrsyr BP_best age,,,cal yrs yr BP,,Paleoceanography,CLAM-derived sample age; best age from model probabilities,,N
</details>
<details style="margin-left: 10px">
<summary>ageMin (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBcc4cbdf0
<p style="margin-left: 10px"><strong>variableName: </strong>ageMin
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>age_calyrsyr BP_min95% age,,lower 95% confidence bound,cal yrs yr BP,,Paleoceanography,CLAM-derived sample age,,N
</details>
<details style="margin-left: 10px">
<summary>max_age_95 (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd7ecd022
<p style="margin-left: 10px"><strong>variableName: </strong>max_age_95
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>age_calyrsyr BP_max95% age,,upper 95% confidence bound,cal yrs yr BP,,Paleoceanography,CLAM-derived sample age,,N
</details>
<details style="margin-left: 10px">
<summary>BSi (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1b8fd351
<p style="margin-left: 10px"><strong>variableName: </strong>BSi
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>opal opal,carbonate-free bulk sediment,,percent by weight,,Paleoceanography,,wet chemical digestion; Mortlock and Froelich (1989),N
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>BSI_regime (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBc019f917
<p style="margin-left: 10px"><strong>variableName: </strong>BSI_regime
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>opal_regime opal,carbonate-free bulk sediment,,percent by weight,,Paleoceanography,regime shift analysis; Rodionov (2004, 2006),,N
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TOC (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3291d830
<p style="margin-left: 10px"><strong>variableName: </strong>TOC
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>TOC total organic carbon,carbonate-free bulk sediment,,percent by weight,,Paleoceanography,,elemental analyzer,N
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TN (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBf0918d86
<p style="margin-left: 10px"><strong>variableName: </strong>TN
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>TN total nitrogen,carbonate-free bulk sediment,,percent by weight,,Paleoceanography,,elemental analyzer,N
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>NC (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBf33edba5
<p style="margin-left: 10px"><strong>variableName: </strong>NC
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>molar_NC Nitrogen/Carbon,carbonate-free bulk sediment,,unitless,,Paleoceanography,molar ratio,elemental analyzer,N
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d13C (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3909c600
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>org_d13C delta 13C,organic matter,,per mil VPDB,,Paleoceanography,,Thermo Delta isotope-ratio mass spectrometer,N
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d15N (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa7114cc3
<p style="margin-left: 10px"><strong>variableName: </strong>d15N
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>sed_d15N delta 15N,carbonate-free bulk sediment,,per mil AIR,,Paleoceanography,,Thermo Delta isotope-ratio mass spectrometer,N
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB7b1a6937
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>composite depth
</details>
<details style="margin-left: 10px">
<summary>age (yrBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB5a9bcce1
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yrBP
<p style="margin-left: 10px"><strong>description: </strong>surface (claibrated)  and radiocarbon ages
</details>
<details style="margin-left: 10px">
<summary>core (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa61f417f
<p style="margin-left: 10px"><strong>variableName: </strong>core
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>
<details style="margin-left: 10px">
<summary>material (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB7ffdf427
<p style="margin-left: 10px"><strong>variableName: </strong>material
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>
<details style="margin-left: 10px">
<summary>top_depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBe8d7d07c
<p style="margin-left: 10px"><strong>variableName: </strong>top_depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>bottom_depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB34691497
<p style="margin-left: 10px"><strong>variableName: </strong>bottom_depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>sampleDepth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB89134d82
<p style="margin-left: 10px"><strong>variableName: </strong>sampleDepth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>youngest14Cage (yrBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB2e197895
<p style="margin-left: 10px"><strong>variableName: </strong>youngest14Cage
<p style="margin-left: 10px"><strong>units: </strong>yrBP
</details>
<details style="margin-left: 10px">
<summary>oldest14Cage (yrBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB230f2c29
<p style="margin-left: 10px"><strong>variableName: </strong>oldest14Cage
<p style="margin-left: 10px"><strong>units: </strong>yrBP
</details>
<details style="margin-left: 10px">
<summary>type (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBab33fe6d
<p style="margin-left: 10px"><strong>variableName: </strong>type
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>
<details style="margin-left: 10px">
<summary>rejected (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBb75826c4
<p style="margin-left: 10px"><strong>variableName: </strong>rejected
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### ageMin (BP)
```{r}
plotCol(thisTS,ind = 2)
```

### max_age_95 (BP)
```{r}
plotCol(thisTS,ind = 3)
```

### BSi (percent)
```{r}
plotCol(thisTS,ind = 5)
```

### BSI_regime (percent)
```{r}
plotCol(thisTS,ind = 6)
```

### TOC (percent)
```{r}
plotCol(thisTS,ind = 7)
```

### TN (percent)
```{r}
plotCol(thisTS,ind = 8)
```

### NC (missing)
```{r}
plotCol(thisTS,ind = 9)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 10)
```

### d15N (permil)
```{r}
plotCol(thisTS,ind = 11)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 6)
```

### age (yrBP)
```{r}
plotCol(chronTS,ind = 7)
```

### core (NA)
```{r}
plotCol(chronTS,ind = 1)
```

### material (NA)
```{r}
plotCol(chronTS,ind = 2)
```

### top_depth (cm)
```{r}
plotCol(chronTS,ind = 3)
```

### bottom_depth (cm)
```{r}
plotCol(chronTS,ind = 4)
```

### sampleDepth (cm)
```{r}
plotCol(chronTS,ind = 5)
```

### youngest14Cage (yrBP)
```{r}
plotCol(chronTS,ind = 8)
```

### oldest14Cage (yrBP)
```{r}
plotCol(chronTS,ind = 9)
```

### type (NA)
```{r}
plotCol(chronTS,ind = 10)
```

### rejected (NA)
```{r}
plotCol(chronTS,ind = 11)
```
