---
title: "GGC19.Farmer.2011"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 35
thisTS <- TS[which(udsn[i] == dsn)]
```
#GGC19.Farmer.2011

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](GGC19.Farmer.2011.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/wNAm0_1_0/GGC19.Farmer.2011.lpd)
            

[Download data only (csv)](GGC19.Farmer.2011.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>marine sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/12362
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>citeKey: </strong>farmer2011westernarcticoceantempera
<p style="margin-left: 10px"><strong>journal: </strong>Geophysical Research Letters
<p style="margin-left: 10px"><strong>volume: </strong>38
<p style="margin-left: 10px"><strong>pages: </strong>n/a-n/a
<p style="margin-left: 10px"><strong>pubYear: </strong>2011
<p style="margin-left: 10px"><strong>title: </strong>Western Arctic Ocean temperature variability during the last 8000 years
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>72.16
<p style="margin-left: 0px"><strong>longitude: </strong>-155.51
<p style="margin-left: 0px"><strong>elevation: </strong>-369
<p style="margin-left: 0px"><strong>siteName: </strong>GGC19
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB51a8c8e2
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (yr BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB6c332c90
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) yr BP
</details>
<details style="margin-left: 10px">
<summary>Temp (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH1cf1e0ac
<p style="margin-left: 10px"><strong>variableName: </strong>Temp
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Salinity (psu) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH7ee92330
<p style="margin-left: 10px"><strong>variableName: </strong>Salinity
<p style="margin-left: 10px"><strong>units: </strong>psu
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>S
<p style="margin-left: 20px"><strong>variableDetail: </strong>SSS
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sea_Ice_months (months/year) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH19e66ffa
<p style="margin-left: 10px"><strong>variableName: </strong>Sea_Ice_months
<p style="margin-left: 10px"><strong>units: </strong>months/year
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>ICE
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sea_Ice_conc (0-10) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHfc5a45a8
<p style="margin-left: 10px"><strong>variableName: </strong>Sea_Ice_conc
<p style="margin-left: 10px"><strong>units: </strong>0-10
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>ICE
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Temp_winter (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB2ab3d1cb
<p style="margin-left: 10px"><strong>variableName: </strong>Temp_winter
<p style="margin-left: 10px"><strong>units: </strong>degC
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>productivity (gcm2) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH69b77781
<p style="margin-left: 10px"><strong>variableName: </strong>productivity
<p style="margin-left: 10px"><strong>units: </strong>gcm2
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB73e65930
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (yr BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB5ed40776
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr BP
</details>
<details style="margin-left: 10px">
<summary>BWT (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB83c93f8b
<p style="margin-left: 10px"><strong>variableName: </strong>BWT
<p style="margin-left: 10px"><strong>units: </strong>degC
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>bottom water temperature
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O-Islandiella (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3c7ed2c6
<p style="margin-left: 10px"><strong>variableName: </strong>d18O-Islandiella
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Temp (degC) [1-1]
```{r}
plotCol(thisTS,ind = 1)
```

### Salinity (psu) [1-1]
```{r}
plotCol(thisTS,ind = 4)
```

### Sea_Ice_months (months/year) [1-1]
```{r}
plotCol(thisTS,ind = 5)
```

### Sea_Ice_conc (0-10) [1-1]
```{r}
plotCol(thisTS,ind = 6)
```

### Temp_winter (degC) [1-1]
```{r}
plotCol(thisTS,ind = 8)
```

### productivity (gcm2) [1-1]
```{r}
plotCol(thisTS,ind = 7)
```

### BWT (degC) [1-2]
```{r}
plotCol(thisTS,ind = 12)
```

### d18O-Islandiella (permil) [1-2]
```{r}
plotCol(thisTS,ind = 11)
```
