---
title: "KoksilahDischarge.Brown.2015"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 52
thisTS <- TS[which(udsn[i] == dsn)]
```
#KoksilahDischarge.Brown.2015

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](KoksilahDischarge.Brown.2015.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/wNAm0_1_0/KoksilahDischarge.Brown.2015.lpd)
            

[Download data only (csv)](KoksilahDischarge.Brown.2015.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Research
<p style="margin-left: 10px"><strong>volume: </strong>83
<p style="margin-left: 10px"><strong>pages: </strong>415-426
<p style="margin-left: 10px"><strong>title: </strong>Multi-millennial streamflow dynamics in two forested watersheds on Vancouver Island, Canada
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>48.73
<p style="margin-left: 0px"><strong>longitude: </strong>-123.67
<p style="margin-left: 0px"><strong>elevation: </strong>13
<p style="margin-left: 0px"><strong>siteName: </strong>Koksilah River Discharge
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>age (yr BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3585e3c0
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr BP
</details>
<details style="margin-left: 10px">
<summary>JAN (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd45020ec
<p style="margin-left: 10px"><strong>variableName: </strong>JAN
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>JAN
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>FEB (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBb83878b7
<p style="margin-left: 10px"><strong>variableName: </strong>FEB
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>FEB
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MAR (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB0ee4c6c9
<p style="margin-left: 10px"><strong>variableName: </strong>MAR
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>MAR
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>APR (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBee7ebf6d
<p style="margin-left: 10px"><strong>variableName: </strong>APR
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>APR
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MAY (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBb1d70ffc
<p style="margin-left: 10px"><strong>variableName: </strong>MAY
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>MAY
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>JUN (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB55435adb
<p style="margin-left: 10px"><strong>variableName: </strong>JUN
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>JUN
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>JUL (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd6cdf711
<p style="margin-left: 10px"><strong>variableName: </strong>JUL
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>JUL
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>AUG (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBe3542db6
<p style="margin-left: 10px"><strong>variableName: </strong>AUG
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>AUG
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>SEP (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd7bec2c4
<p style="margin-left: 10px"><strong>variableName: </strong>SEP
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>SEP
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>OCT (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB7d62f2ab
<p style="margin-left: 10px"><strong>variableName: </strong>OCT
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>OCT
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>NOV (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB7afcfa10
<p style="margin-left: 10px"><strong>variableName: </strong>NOV
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positve
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>NOV
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>DEC (mm/month)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB8866c2b8
<p style="margin-left: 10px"><strong>variableName: </strong>DEC
<p style="margin-left: 10px"><strong>units: </strong>mm/month
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>DEC
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamflow
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>ANN (mm/year)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB282a251d
<p style="margin-left: 10px"><strong>variableName: </strong>ANN
<p style="margin-left: 10px"><strong>units: </strong>mm/year
<p style="margin-left: 10px"><strong>description: </strong>Koksilah River discharge (Q) at gauging station 48.73°N, 123.67°W. Rainshadow forest. Watershed area: 214km2. Watershed average annual precipitation: 2074mm. 
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>streamfloq
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### JAN (mm/month)
```{r}
plotCol(thisTS,ind = 2)
```

### FEB (mm/month)
```{r}
plotCol(thisTS,ind = 3)
```

### MAR (mm/month)
```{r}
plotCol(thisTS,ind = 4)
```

### APR (mm/month)
```{r}
plotCol(thisTS,ind = 5)
```

### MAY (mm/month)
```{r}
plotCol(thisTS,ind = 6)
```

### JUN (mm/month)
```{r}
plotCol(thisTS,ind = 7)
```

### JUL (mm/month)
```{r}
plotCol(thisTS,ind = 8)
```

### AUG (mm/month)
```{r}
plotCol(thisTS,ind = 9)
```

### SEP (mm/month)
```{r}
plotCol(thisTS,ind = 10)
```

### OCT (mm/month)
```{r}
plotCol(thisTS,ind = 11)
```

### NOV (mm/month)
```{r}
plotCol(thisTS,ind = 12)
```

### DEC (mm/month)
```{r}
plotCol(thisTS,ind = 13)
```

### ANN (mm/year)
```{r}
plotCol(thisTS,ind = 14)
```
