---
title: "LagunaDeJuanacatlan.Jones.2015"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 56
thisTS <- TS[which(udsn[i] == dsn)]
```
#LagunaDeJuanacatlan.Jones.2015

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LagunaDeJuanacatlan.Jones.2015.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/wNAm0_1_0/LagunaDeJuanacatlan.Jones.2015.lpd)
            

[Download data only (csv)](LagunaDeJuanacatlan.Jones.2015.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.sciencedirect.com/science/article/pii/S0277379115300433
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>124
<p style="margin-left: 10px"><strong>pages: </strong>290-295
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Late Holocene climate reorganisation and the North American Monsoon
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>20
<p style="margin-left: 10px"><strong>pages: </strong>1195-1206
<p style="margin-left: 10px"><strong>title: </strong>Climate variability over the last two millennia in the North American Monsoon region, recorded in laminated lake sediments from Laguna de Juanacatlán, Mexico
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>20.6293
<p style="margin-left: 0px"><strong>longitude: </strong>-104.7364
<p style="margin-left: 0px"><strong>elevation: </strong>2000
<p style="margin-left: 0px"><strong>siteName: </strong>Laguna de Juanacatlan
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB988cf23d
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBce52080e
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>Ti_peakArea (unitless) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe11c862a
<p style="margin-left: 10px"><strong>variableName: </strong>Ti_peakArea
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>indicator or terriginous runnoff
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>monsoon
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>CAL (unitless) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD01441887
<p style="margin-left: 10px"><strong>variableName: </strong>CAL
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>year (AD) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBddfe7278
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa25ed912
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>Ti_norm (index) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD91196716
<p style="margin-left: 10px"><strong>variableName: </strong>Ti_norm
<p style="margin-left: 10px"><strong>units: </strong>index
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>indicator or terriginous runnoff
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>monsoon
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>CAL (unitless) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe9872299
<p style="margin-left: 10px"><strong>variableName: </strong>CAL
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Ti_peakArea (unitless) [1-1]
```{r}
plotCol(thisTS,ind = 4)
```

### CAL (unitless) [1-1]
```{r}
plotCol(thisTS,ind = 1)
```

### Ti_norm (index) [2-1]
```{r}
plotCol(thisTS,ind = 8)
```

### CAL (unitless) [2-1]
```{r}
plotCol(thisTS,ind = 5)
```
