---
title: "CO06QUNG"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 29
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO06QUNG

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO06QUNG.lpd)
            

[Download data only (csv)](CO06QUNG.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=519:1:::::P1_STUDY_ID:6116,ftp://ftp.ncdc.noaa.gov/pub/data/paleo/coral/west_pacific/papua_new_guinea/rabaul2006.txt
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>MNE
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Quinn, Terrence M. , Taylor, Frederick W. , Crowley, Thomas J.
<p style="margin-left: 10px"><strong>citeKey: </strong>quinn2006coral
<p style="margin-left: 10px"><strong>journal: </strong>J. Geophys. Res.
<p style="margin-left: 10px"><strong>volume: </strong>111
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Coral-based climate variability in the Western Pacific Warm Pool since 1867
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2005JC003243
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Tierney, Jessica E. , Abram, Nerilie J. , Anchukaitis, Kevin J. , Evans, Michael N. , Giry, Cyril , Kilbourne, K. Halimeda , Saenger, Casey P. , Wu, Henry C. , Zinke, Jens
<p style="margin-left: 10px"><strong>citeKey: </strong>tierney2015tropical
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Ocean2kHR-PacificQuinn2008Rabaul
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2014PA002717
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-4.1916
<p style="margin-left: 0px"><strong>longitude: </strong>151.9772
<p style="margin-left: 0px"><strong>elevation: </strong>-8
<p style="margin-left: 0px"><strong>siteName: </strong>Rabaul
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT85ba7be434
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_144
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Coral d18O variations at Rabaul are likely driven by the combined variations in SST and seawater d18O (and hence SSS) given the general climatology of the WPWP
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease/increase
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Coral d18O variations are modestly correlated with SST variations over their common period of overlap (1970? 1993), both in terms of the monthly and monthly anomaly time series
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Age models were constructed using the AnalySeries program [Paillard et al., 1996]. We used tie points to connect the lowest (highest) d18O values to the warmest (coolest) temperatures in the instrumental SST record to establish each year.The use of coral Sr/Ca values instead of coral d18O values to construct the age model results produces a similar chronology. The geochemical data were then interpolated to give monthly d18O values. The geochemically based age models were confirmed via comparison with ages determined by counting of skeletal density-band couplets in the X-ray images of the coral slab.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>month
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The monthly coral d18O anomaly time series at Rabaul yields no significant correlation with the instrumental SSS record, despite the fact that similar coral records from Fiji [Le Bec et al., 2000] and Vanuatu [Kilbourne et al., 2004] have been demonstrated to reflect SSS variations. It is possible that the monthly coral d18O anomaly record does reflect local SSS variability at Rabaul and the observed low correlation between these two variables results from differences between the ship-track SSS record and the actual SSS variability at Rabaul
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Age models were constructed using the AnalySeries program [Paillard et al., 1996]. We used tie points to connect the lowest (highest) d18O values to the warmest (coolest) temperatures in the instrumental SST record to establish each year.The use of coral Sr/Ca values instead of coral d18O values to construct the age model results produces a similar chronology. The geochemical data were then interpolated to give monthly d18O values. The geochemically based age models were confirmed via comparison with ages determined by counting of skeletal density-band couplets in the X-ray images of the coral slab.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>month
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sr_Ca (mmol/mol)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_145
<p style="margin-left: 10px"><strong>variableName: </strong>Sr_Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>temperature
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d13C (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_146
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### Sr_Ca
```{r}
plotCol(thisTS,ind = 3)
```

### d13C
```{r}
plotCol(thisTS,ind = 4)
```
