---
title: "CO08GOBE"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 32
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO08GOBE

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO08GOBE.lpd)
            

[Download data only (csv)](CO08GOBE.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/6115
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>KHK, MAS
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Goodkin, Nathalie F. , Hughen, Konrad A. , Doney, Scott C. , Curry, William B.
<p style="margin-left: 10px"><strong>citeKey: </strong>goodkin2008increased
<p style="margin-left: 10px"><strong>journal: </strong>Nature Geoscience
<p style="margin-left: 10px"><strong>volume: </strong>1
<p style="margin-left: 10px"><strong>pages: </strong>-4
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Increased multidecadal variability of the North Atlantic Oscillation since 1781
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/ngeo352
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Tierney, Jessica E. , Abram, Nerilie J. , Anchukaitis, Kevin J. , Evans, Michael N. , Giry, Cyril , Kilbourne, K. Halimeda , Saenger, Casey P. , Wu, Henry C. , Zinke, Jens
<p style="margin-left: 10px"><strong>citeKey: </strong>tierney2015tropical
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Ocean2kHR-AtlanticBermudaGoodkin2006
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2014PA002717
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>30.6486
<p style="margin-left: 0px"><strong>longitude: </strong>-64.9888
<p style="margin-left: 0px"><strong>elevation: </strong>-16
<p style="margin-left: 0px"><strong>siteName: </strong>Bermuda south shore
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT2c683ac207
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>year (AD) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATaba87e5775
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_094
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>However, the long-term trends in the raw d18O and Sr/Ca data provide a strong indication that the ocean surface waters near Bermuda were fresher during the LIA, even if we cannot quantitatively partition the temperature and salinity signals. Over the course of the 200-year record, long-term trends in mean annual and wintertime dOc (0.0003%/a and < 0.0001%/a, respectively) are effectively flat (Figures 4a and 4b). If dOc were purely a result of SST, and SST is increasing through time, a strong negative trend would be visible in the dOc records [McConnaughey, 1989a, 1989b].
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>temperature
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>we show that with the present coral record and relatively short calibration data set, we are unable to derive a robust, statistically significant separation of the salinity and temperature signals within the coral d18O.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>11
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Age models were developed using density banding visible in the X radiographs to identify the calendar year. X radiographs for these corals have been previously published [Goodkin, 2007; Goodkin et al., 2007, 2005]. Some error is expected within this age model because of years of very little or no growth, not visible on the X ray and also not clearly discernible in the seasonal cycles of Sr/Ca. While there is the potential for error generated by noise in the Sr/Ca or the annual band counting to result in the inappropriate addition of a year, the majority of age model error will arise because of missing years, generating a bias in which coral bands are assigned to artificially recent (younger) dates. For example, if the coral did not grow in 1950, 1949 would be inappropriately assigned the date 1950, and similarly for all coral years prior to 1950 (1781?1949). Such age model bias is suspected during the early to mid-1800s when growth rates were extremely slow for an extended period of time and hiatuses in growth may have occurred [Goodkin et al., 2005].
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>counting
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>There are several factors that may prevent the quantification of these relationships, the most likely being the lack of large changes in SSS documented in the instrumental data. Over the length of the Hydrostation S record, salinity (mean annual and winter) has a range of only 0.3 psu, too small to establish a significant relationship for these proxies, given representation error (noise) in the coral and instrumental records.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>11
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Age models were developed using density banding visible in the X radiographs to identify the calendar year. X radiographs for these corals have been previously published [Goodkin, 2007; Goodkin et al., 2007, 2005]. Some error is expected within this age model because of years of very little or no growth, not visible on the X ray and also not clearly discernible in the seasonal cycles of Sr/Ca. While there is the potential for error generated by noise in the Sr/Ca or the annual band counting to result in the inappropriate addition of a year, the majority of age model error will arise because of missing years, generating a bias in which coral bands are assigned to artificially recent (younger) dates. For example, if the coral did not grow in 1950, 1949 would be inappropriately assigned the date 1950, and similarly for all coral years prior to 1950 (1781?1949). Such age model bias is suspected during the early to mid-1800s when growth rates were extremely slow for an extended period of time and hiatuses in growth may have occurred [Goodkin et al., 2005].
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>counting
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sr_Ca (mmol/mol) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_095
<p style="margin-left: 10px"><strong>variableName: </strong>Sr_Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>temperature
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### Sr_Ca
```{r}
plotCol(thisTS,ind = 3)
```
