---
title: "CO14OSPA"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 50
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO14OSPA

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO14OSPA.lpd)
            

[Download data only (csv)](CO14OSPA.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=519:1:::::P1_STUDY_ID:16339
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>Henry Wu
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Osborne, M.C.; Dunbar, R.B.; Mucciarone, D.A.; Druffel, E.R.M.; Sanchez-Cabeza, J.-A.
<p style="margin-left: 10px"><strong>journal: </strong>Coral Reefs
<p style="margin-left: 10px"><strong>volume: </strong>33
<p style="margin-left: 10px"><strong>pages: </strong>719
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>A 215-yr coral δ18O time series from Palau records dynamics of the West Pacific Warm Pool following the end of the Little Ice Age
<p style="margin-left: 10px"><strong>DOI: </strong>10.1007/s00338-014-1146-1
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Osborne, M.C.
<p style="margin-left: 10px"><strong>citeKey: </strong>osborne2014ocean2khrDataCitation
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Ocean2kHR-PacificPalauulongchannelOsborne2014
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>7.2859
<p style="margin-left: 0px"><strong>longitude: </strong>134.2503
<p style="margin-left: 0px"><strong>elevation: </strong>-12
<p style="margin-left: 0px"><strong>siteName: </strong>Palau
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT4a18177d7a
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>year (AD) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATfb90983e27
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_181
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Although empirically determined regression slopes are similar to published SST?d18OCRL fractionation values for P. lutea, in both instances, the per cents of explained variance in the regressions are small. This suggests that factors such as SSS are contributing to Palau d18OCRL variability in the pre-instrumental period.
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease/increase
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Although empirically determined regression slopes are similar to published SST?d18OCRL fractionation values for P. lutea, in both instances, the per cents of explained variance in the regressions are small. This suggests that factors such as SSS are contributing to Palau d18OCRL variability in the pre-instrumental period.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>We developed age models by visually comparing coral banding with seasonal d18O and d13C cycles. Dark regions of the coral X-ray positives corresponded with minima in d18O and d13C. We then associated local d18O and d13C minima with March, based on the mean Palau SSS and SST climatology. We converted samples to monthly resolution by performing linear interpolations between chronological anchor points.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>month
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Although empirically determined regression slopes are similar to published SST?d18OCRL fractionation values for P. lutea, in both instances, the per cents of explained variance in the regressions are small. This suggests that factors such as SSS are contributing to Palau d18OCRL variability in the pre-instrumental period.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>We developed age models by visually comparing coral banding with seasonal d18O and d13C cycles. Dark regions of the coral X-ray positives corresponded with minima in d18O and d13C. We then associated local d18O and d13C minima with March, based on the mean Palau SSS and SST climatology. We converted samples to monthly resolution by performing linear interpolations between chronological anchor points.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>month
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_183
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Although empirically determined regression slopes are similar to published SST?d18OCRL fractionation values for P. lutea, in both instances, the per cents of explained variance in the regressions are small. This suggests that factors such as SSS are contributing to Palau d18OCRL variability in the pre-instrumental period.
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease/increase
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Although empirically determined regression slopes are similar to published SST?d18OCRL fractionation values for P. lutea, in both instances, the per cents of explained variance in the regressions are small. This suggests that factors such as SSS are contributing to Palau d18OCRL variability in the pre-instrumental period.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>We developed age models by visually comparing coral banding with seasonal d18O and d13C cycles. Dark regions of the coral X-ray positives corresponded with minima in d18O and d13C. We then associated local d18O and d13C minima with March, based on the mean Palau SSS and SST climatology. We converted samples to monthly resolution by performing linear interpolations between chronological anchor points.The UC record is based upon a composite of the living and deceased colonies assembled by ?wiggle matching? chronologies for the period of overlap
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>month
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Although empirically determined regression slopes are similar to published SST?d18OCRL fractionation values for P. lutea, in both instances, the per cents of explained variance in the regressions are small. This suggests that factors such as SSS are contributing to Palau d18OCRL variability in the pre-instrumental period.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>We developed age models by visually comparing coral banding with seasonal d18O and d13C cycles. Dark regions of the coral X-ray positives corresponded with minima in d18O and d13C. We then associated local d18O and d13C minima with March, based on the mean Palau SSS and SST climatology. We converted samples to monthly resolution by performing linear interpolations between chronological anchor points.The UC record is based upon a composite of the living and deceased colonies assembled by ?wiggle matching? chronologies for the period of overlap
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>month
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d13C (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_182
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_184
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 4)
```

### d13C
```{r}
plotCol(thisTS,ind = 3)
```

### d13C
```{r}
plotCol(thisTS,ind = 6)
```
