---
title: "CO96SWBB"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 80
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO96SWBB

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO96SWBB.lpd)
            

[Download data only (csv)](CO96SWBB.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Swart
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>DOI: </strong>10.2307/3515246
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Tierney, Jessica E.,Abram, Nerilie J.,Anchukaitis, Kevin J.,Evans, Michael N.,Giry, Cyril,Kilbourne, K. Halimeda,Saenger, Casey P.,Wu, Henry C.,Zinke, Jens
<p style="margin-left: 10px"><strong>citeKey: </strong>tierney2015tropical
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2014PA002717
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>25.3903
<p style="margin-left: 0px"><strong>longitude: </strong>-80.1715
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Alinas Reef, Biscayne National Park, Florida
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATbcda567eac
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATa013819a6a
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO96SWBB01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>precipitation
<p style="margin-left: 20px"><strong>direction: </strong>decrease/increase
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>when precipitation is greater than average, precipitation is inversely correlated with d18O reflecting the input of isotopical depleted precipitation, and vice versa reflectin ghte input of isotopically heavy weaters from the Everglades.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.37
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Counting annual density bands provided an age model for these samples assuming high density band is July. Data linearly interpolated to monthly for less than 12 samples per year and used rectanglar interpolation for years with more than 12 samples. From NOAA wb site: The skeleton was sampled at about 10-15 samples a year and  these data have been pooled to construct the annual means.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>subannual samples averaged to annual for archived data
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>summer precipitation
<p style="margin-left: 20px"><strong>variable: </strong>P_E
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Counting annual density bands provided an age model for these samples assuming high density band is July. Data linearly interpolated to monthly for less than 12 samples per year and used rectanglar interpolation for years with more than 12 samples. From NOAA wb site: The skeleton was sampled at about 10-15 samples a year and  these data have been pooled to construct the annual means.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>subannual samples averaged to annual for archived data
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
