---
title: "CO96QUVA"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 79
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO96QUVA

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO96QUVA.lpd)
            

[Download data only (csv)](CO96QUVA.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/1839
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Quinn, T. M.
<p style="margin-left: 10px"><strong>citeKey: </strong>quinn1996new
<p style="margin-left: 10px"><strong>journal: </strong>Geophys. Res. Lett.
<p style="margin-left: 10px"><strong>volume: </strong>23
<p style="margin-left: 10px"><strong>pages: </strong>-3
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>New stable isotope results from a 173-year coral from Espiritu Santo, Vanuatu
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/S0277-3791(05)80005-8, 10.1029/96GL03169
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Tierney, Jessica E. , Abram, Nerilie J. , Anchukaitis, Kevin J. , Evans, Michael N. , Giry, Cyril , Kilbourne, K. Halimeda , Saenger, Casey P. , Wu, Henry C. , Zinke, Jens
<p style="margin-left: 10px"><strong>citeKey: </strong>tierney2015tropical
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Ocean2kHR-PacificVanuatuQuinn1996
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2014PA002717
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-15
<p style="margin-left: 0px"><strong>longitude: </strong>167
<p style="margin-left: 0px"><strong>elevation: </strong>-1
<p style="margin-left: 0px"><strong>siteName: </strong>Tangoa Island, Vanuatu
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT76b067a764
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_133
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>This sample was collected alive at < 1 m water depth (Quinn 1993). Comparison of the d180 with SST and rainfall records indicates a correlation of 0.71 and 0.54, respectively, over the 13-year interval where data overlaps (Fig. 2). Just as in the precipitation and SST comparison, the correlation is much higher at the annual cycle (coherence of 0.95). There is also a slight suggestion of coherence at the El Nino time scale, but the calibration time series is too short to draw any definitive conclusions. Since the 0.71 correlation between SST and d180 explains only half the variance in the SST record, other factors are obviously responsible for the d180 variations. (Quinn 1996)
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease/increase
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Comparison of the d180 with SST and rainfall records indicates a correlation of 0.71 and 0.54, respectively, over the 13-year interval where data overlaps (Fig. 2). Just as in the precipitation and SST comparison, the correlation is much higher at the annual cycle (coherence of 0.95). There is also a slight suggestion of coherence at the El Nino time scale, but the calibration time series is too short to draw any definitive conclusions. Since the 0.71 correlation between SST and d180 explains only half the variance in the SST record, other factors are obviously responsible for the d180 variations.
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1-Jan
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Sampling resolution is four samples per year, one sample in the middle of each density band. The 0.5 mm diameter, discrete point sampling strategy used in this study creates samples that are a homogeneous mixture of-26 (7 mm/year) to -20 (9 mm/year) days of skeletal growth, assuming a linear extension rate. (Quinn et al, 1993). Isotope sampling methods were also identical to Quinn et al. [1993], with new samples being midway between the original samples reported in that study.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1 year
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological and 230Th dates
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Comparison of the d180 with SST and rainfall records indicates a correlation of 0.71 and 0.54, respectively, over the 13-year interval where data overlaps (Fig. 2). Just as in the precipitation and SST comparison, the correlation is much higher at the annual cycle (coherence of 0.95). There is also a slight suggestion of coherence at the El Nino time scale, but the calibration time series is too short to draw any definitive conclusions. Since the 0.71 correlation between SST and d180 explains only half the variance in the SST record, other factors are obviously responsible for the d180 variations.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>0.29
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1-Jan
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Sampling resolution is four samples per year, one sample in the middle of each density band. The 0.5 mm diameter, discrete point sampling strategy used in this study creates samples that are a homogeneous mixture of-26 (7 mm/year) to -20 (9 mm/year) days of skeletal growth, assuming a linear extension rate. (Quinn et al, 1993). Isotope sampling methods were also identical to Quinn et al. [1993], with new samples being midway between the original samples reported in that study.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1 year
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological and 230Th dates
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
