---
title: "IC07KARB"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 142
thisTS <- TS[which(udsn[i] == dsn)]
```
#IC07KARB

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](IC07KARB.lpd)
            

[Download data only (csv)](IC07KARB.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>glacier ice
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Kaspari
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2007GL030440
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>28.03
<p style="margin-left: 0px"><strong>longitude: </strong>86.96
<p style="margin-left: 0px"><strong>elevation: </strong>6518
<p style="margin-left: 0px"><strong>siteName: </strong>East Rongbuk Glacier
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDbf535196
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>depth (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe7e3cd79
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>IC07KARB01A
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>dD of glacier ice
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>"This verifies that the amount effect acts as an important control on seasonal-decadal scale variations in the isotopic composition of Everest precipitation. More specifically, precipitation increases during periods of more intense convective activity, resulting in more negative dD. Variations in convective activity (i.e., amount effect) and moisture source region related to changes in atmospheric circulation are the dominant controls on the isotopic composition of precipitation in this region (see auxiliary material)."
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>amount effect
<p style="margin-left: 20px"><strong>variableDetail: </strong>precipitation
<p style="margin-left: 20px"><strong>direction: </strong>positive
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Tian, L., V. Masson-Delmotte, M. Stievenard, T. Yao and J. Jouzel.2001. Tibetan Plateau summer monsoon northward extent revealed by measurements of water stable isotopes.J. Geophys. Res., 106(D22), 28,081?28,088.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>precipitation
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model based on volcanic horizons and counting of annual layers (seasonal variations of stable isotopes)
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>0 to 5
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD
```{r}
plotCol(thisTS,ind = 1)
```
