---
title: "LS06SHBE"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 273
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS06SHBE

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS06SHBE.lpd)
            

[Download data only (csv)](LS06SHBE.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>EKT
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Shuman, Bryan , Huang, Yongsong , Newby, Paige , Wang, Yi
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>25
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Compound-specific isotopic analyses track changes in seasonal precipitation regimes in the Northeastern United States at ca 8200calyrBP
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.2006.02.021
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>42.505
<p style="margin-left: 0px"><strong>longitude: </strong>-73.319
<p style="margin-left: 0px"><strong>elevation: </strong>630
<p style="margin-left: 0px"><strong>siteName: </strong>Berry Pond
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATa0273b9d37
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD0779737d
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS06SHBE01B
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Given the lack of correlation between dDlw and pollen- inferred mean July temperatures (Fig. 6), the downcore dDlw changes likely represent either a change in the ratio of soil water and precipitation utilized by the vegetation and/ or a change in source and pathway of regional precipita- tion. The dDlw data may indicate a heavy reliance of terrestrial plants on cool-season derived soil moisture from 11,000?8000 cal yr BP when conditions were dry. Growing- season precipitation may have been too low to provide sufficient water to the plants. An alternative and not mutually exclusive interpretation is that growing-season precipitation was not enriched in deuterium from 11,000?8000 cal yr BP because the presence of high pressure over the Laurentide ice sheet prevented the northward advection of humid, sub-tropical airmasses that are important for summer precipitation today. Both interpre- tations are consistent with Shuman and Donnelly?s (2006) interpretation that low lake levels prior to ca 8200 cal yr BP resulted from low summer precipitation rates and a high ratio of winter to summer precipitation.
<p style="margin-left: 20px"><strong>interpDirection: </strong>depends
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>depends
<p style="margin-left: 20px"><strong>variable: </strong>circulation changes caused by ice sheet topography. Precipitation seasonality.
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
<p style="margin-left: 20px"><strong>direction: </strong>depends
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Given the lack of correlation between dDlw and pollen- inferred mean July temperatures (Fig. 6), the downcore dDlw changes likely represent either a change in the ratio of soil water and precipitation utilized by the vegetation and/ or a change in source and pathway of regional precipita- tion. The dDlw data may indicate a heavy reliance of terrestrial plants on cool-season derived soil moisture from 11,000?8000 cal yr BP when conditions were dry. Growing- season precipitation may have been too low to provide sufficient water to the plants. An alternative and not mutually exclusive interpretation is that growing-season precipitation was not enriched in deuterium from 11,000?8000 cal yr BP because the presence of high pressure over the Laurentide ice sheet prevented the northward advection of humid, sub-tropical airmasses that are important for summer precipitation today. Both interpre- tations are consistent with Shuman and Donnelly?s (2006) interpretation that low lake levels prior to ca 8200 cal yr BP resulted from low summer precipitation rates and a high ratio of winter to summer precipitation.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>depends on the source area and transport path to the study site
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Given the lack of correlation between dDlw and pollen- inferred mean July temperatures (Fig. 6), the downcore dDlw changes likely represent either a change in the ratio of soil water and precipitation utilized by the vegetation and/ or a change in source and pathway of regional precipita- tion. The dDlw data may indicate a heavy reliance of terrestrial plants on cool-season derived soil moisture from 11,000?8000 cal yr BP when conditions were dry. Growing- season precipitation may have been too low to provide sufficient water to the plants. An alternative and not mutually exclusive interpretation is that growing-season precipitation was not enriched in deuterium from 11,000?8000 cal yr BP because the presence of high pressure over the Laurentide ice sheet prevented the northward advection of humid, sub-tropical airmasses that are important for summer precipitation today. Both interpre- tations are consistent with Shuman and Donnelly?s (2006) interpretation that low lake levels prior to ca 8200 cal yr BP resulted from low summer precipitation rates and a high ratio of winter to summer precipitation.
<p style="margin-left: 20px"><strong>direction: </strong>depends on which season provides source moisture for plants
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>depends on which season provides source moisture for plants
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>changes depending on which season provides source moisture for plants
<p style="margin-left: 20px"><strong>variable: </strong>precipitation seasonality
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS06SHBE01A
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>match with pollen based January temperature, C16 n-acids are produced by aquatic plants, and ponds in this region are recharged mainly by winter precipitation (Shuman and Donnelly, 2006, Quat Res, 65:44-56)
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>match with pollen based January temperature, C16 n-acids are produced by aquatic plants, and ponds in this region are recharged mainly by winter precipitation
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 2
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>lake equilibrium with the mean annual balance of precipitation and evaporation across the watershed
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD
```{r}
plotCol(thisTS,ind = 1)
```

### dD
```{r}
plotCol(thisTS,ind = 4)
```
