---
title: "LS16THN301"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 345
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS16THN301

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS16THN301.lpd)
            

[Download data only (csv)](LS16THN301.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Geophysical Research Letters
<p style="margin-left: 10px"><strong>volume: </strong>43
<p style="margin-left: 10px"><strong>pages: </strong>5302-5308
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>A major increase in winter snowfall during the middle Holocene on western Greenland caused by reduced sea ice in Baffin Bay and the Labrador Sea
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2016GL068513
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>National Science Foundation
<p style="margin-left: 10px"><strong>grant: </strong>909334
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>agency: </strong>National Science Foundation
<p style="margin-left: 10px"><strong>grant: </strong>0520718
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding3</summary>
<p style="margin-left: 10px"><strong>agency: </strong>National Science Foundation
<p style="margin-left: 10px"><strong>grant: </strong>Graduate Research Fellowship
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding4</summary>
<p style="margin-left: 10px"><strong>agency: </strong>National Science Foundation
<p style="margin-left: 10px"><strong>grant: </strong>1349595
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding5</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Geological Society of America
<p style="margin-left: 10px"><strong>grant: </strong>Student Research Grant
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding6</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Geological Society of America
<p style="margin-left: 10px"><strong>grant: </strong>Quaternary Geology and Geomorphology Division Marie Morisawa Research Award
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding7</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Geological Society of America
<p style="margin-left: 10px"><strong>grant: </strong>Limnogeology Division Kerry Kelts Research Award
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>68.6374
<p style="margin-left: 0px"><strong>longitude: </strong>-50.98
<p style="margin-left: 0px"><strong>elevation: </strong>59
<p style="margin-left: 0px"><strong>siteName: </strong>Lake N3
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d2H C24 (per mil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB69678476
<p style="margin-left: 10px"><strong>variableName: </strong>d2H C24
<p style="margin-left: 10px"><strong>units: </strong>per mil
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>precipitation seasonality
<p style="margin-left: 20px"><strong>variableDetail: </strong>relative amount of winter snowfall
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Lake N3 δ2Haq has a >100‰ range during the past 8 kyr, larger than the range of modern seasonal δ2Hprecip in Disko Bugt (Figures 1 and 2a). We interpret these large changes in δ2Haq to indicate changes in precipitation sea- sonality, with Arctic moisture sources contributing to the exceptionally low δ2H values. The magnitude and direc- tion of δ2Haq changes cannot be explained by changes in terrestrial plant contributions of C24 n-alkanoic acids, by Holocene temperature change, or by lake water residence time (Figures S6 and S7 in the supporting information).Lake N3 δ2Haq decreased steadily from !190 to !300‰ from 7.5 to 6 ka, in step with declining sea ice in Disko Bugt (Figures 2a and 2b) [Ouellet-Bernier et al., 2014]. Lake N3 δ2Haq remained low during the middle Holocene, synchronous with minimum regional sea ice. The Labrador Sea, an important moisture source region for wes- tern Greenland [Sodemann et al., 2008], had minimum sea ice cover from 6.5 to 3.5 ka (Figure 2b) [de Vernal et al., 2013]. Furthermore, sea ice reached a minimum in northern Baffin Bay and the Canadian Arctic from 6 to 3 ka [Ledu et al., 2010; de Vernal et al., 2013], creating a source for moisture that was 2H-depleted compared to mod- ern winter precipitation around Lake N3. Although Baffin Bay still had seasonal sea ice during the middle Holocene, sea ice would have formed later in the year [Markus et al., 2009]. A loss of sea ice during early winter, when evaporation is greatest, can cause large increases in early winter snowfall [Bintanja and Selten, 2014]. Finally, the West Greenland Current was both strong and warm 6 to 4 ka, likely due to an increased contribution of the warm Irminger Current to the West Greenland Current, resulting in regional warmth and providing energy to evaporate more moisture (Figures 2c and 2d) [Perner et al., 2013]. Winter insolation was low during the middle Holocene [Laskar et al., 2004], so there was likely a large contrast between winter air temperature and winter ocean surface temperature. This temperature contrast would cause high evaporation. Thus, we inter- pret the significant middle Holocene depletion of Lake N3 δ2Haq as an increase in winter precipitation, caused by the near total loss of sea ice cover in the Labrador Sea, and the loss of early winter sea ice and increased ocea- nic heat advection in Baffin Bay.
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d2H C26 (per mil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB00087524
<p style="margin-left: 10px"><strong>variableName: </strong>d2H C26
<p style="margin-left: 10px"><strong>units: </strong>per mil
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>air temperature
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Our interpretation of Lake N3 δ2Hterr as summer temperature is supported in several ways (Figure 3). First, δ2Hterr exhibits similar centennial-scale patterns during the past ~ 300 years as midge-inferred summer temperature anomalies at North Lake, western Greenland (Figure 3c) [Axford et al., 2013]. Coldest conditions in both records correspond with the Little Ice Age and end with warming in recent decades, a pattern also documented in Disko Bugt [Perner et al., 2013]. Second, the centennial-scale variability in Lake N3 δ2Hterr is remarkably similar to the 4 kyr-long record of annual average surface temperature at Greenland Ice Sheet Project 2 (GISP2), Greenland (r2 = 0.43) [Kobashi et al., 2011] (Figure 3b and Figure S5 in the supporting information), suggesting similar con- trols on late Holocene centennial-scale temperature at these sites, despite seasonal and elevation differences.
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d2H C28 (per mil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB2bbc35a8
<p style="margin-left: 10px"><strong>variableName: </strong>d2H C28
<p style="margin-left: 10px"><strong>units: </strong>per mil
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>air temperature
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Our interpretation of Lake N3 δ2Hterr as summer temperature is supported in several ways (Figure 3). First, δ2Hterr exhibits similar centennial-scale patterns during the past ~ 300 years as midge-inferred summer temperature anomalies at North Lake, western Greenland (Figure 3c) [Axford et al., 2013]. Coldest conditions in both records correspond with the Little Ice Age and end with warming in recent decades, a pattern also documented in Disko Bugt [Perner et al., 2013]. Second, the centennial-scale variability in Lake N3 δ2Hterr is remarkably similar to the 4 kyr-long record of annual average surface temperature at Greenland Ice Sheet Project 2 (GISP2), Greenland (r2 = 0.43) [Kobashi et al., 2011] (Figure 3b and Figure S5 in the supporting information), suggesting similar con- trols on late Holocene centennial-scale temperature at these sites, despite seasonal and elevation differences.
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Core name (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3ccf3cbb
<p style="margin-left: 10px"><strong>variableName: </strong>Core name
<p style="margin-left: 10px"><strong>units: </strong>unitless
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Composite Midpoint Depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBddaef138
<p style="margin-left: 10px"><strong>variableName: </strong>Composite Midpoint Depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Mean Age (year BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB37c6f827
<p style="margin-left: 10px"><strong>variableName: </strong>Mean Age
<p style="margin-left: 10px"><strong>units: </strong>year BP
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Min Age (year BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB86feb1be
<p style="margin-left: 10px"><strong>variableName: </strong>Min Age
<p style="margin-left: 10px"><strong>units: </strong>year BP
<p style="margin-left: 10px"><strong>description: </strong>minimum age of 95% confidence interval
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Max Age (year BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa4c3db78
<p style="margin-left: 10px"><strong>variableName: </strong>Max Age
<p style="margin-left: 10px"><strong>units: </strong>year BP
<p style="margin-left: 10px"><strong>description: </strong>maximum age of 95% confidence interval
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>stdev C24 (per mil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB08e3980f
<p style="margin-left: 10px"><strong>variableName: </strong>stdev C24
<p style="margin-left: 10px"><strong>units: </strong>per mil
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>n C24 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBfd7e019e
<p style="margin-left: 10px"><strong>variableName: </strong>n C24
<p style="margin-left: 10px"><strong>units: </strong>unitless
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>stdev C26 (per mil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB61208225
<p style="margin-left: 10px"><strong>variableName: </strong>stdev C26
<p style="margin-left: 10px"><strong>units: </strong>per mil
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>n C26 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB956729cc
<p style="margin-left: 10px"><strong>variableName: </strong>n C26
<p style="margin-left: 10px"><strong>units: </strong>unitless
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>stdev C28 (per mil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB63a13e10
<p style="margin-left: 10px"><strong>variableName: </strong>stdev C28
<p style="margin-left: 10px"><strong>units: </strong>per mil
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>n C28 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB708ebec7
<p style="margin-left: 10px"><strong>variableName: </strong>n C28
<p style="margin-left: 10px"><strong>units: </strong>unitless
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Mean Age (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB37c6f827year
<p style="margin-left: 10px"><strong>variableName: </strong>Mean Age
<p style="margin-left: 10px"><strong>units: </strong>AD
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
