---
title: "LS17BAHA01"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 347
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS17BAHA01

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS17BAHA01.lpd)
            

[Download data only (csv)](LS17BAHA01.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>183
<p style="margin-left: 10px"><strong>pages: </strong>177-187
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Hydroclimate variability of High Arctic Svalbard during the Holocene inferred from hydrogen isotopes of leaf waxes
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.2016.11.036
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>183
<p style="margin-left: 10px"><strong>pages: </strong>164-176
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Holocene multi-proxy environmental reconstruction from lake Hakluytvatnet, Amsterdamøya Island, Svalbard (79.5°N)
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.2017.02.017
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Lamont Doherty Earth Observatory
<p style="margin-left: 10px"><strong>grant: </strong>Postdoctoral Fellowship
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Norwegian Research Council
<p style="margin-left: 10px"><strong>grant: </strong>Arctic Field Grant
<p style="margin-left: 10px"><strong>country: </strong>Norway
</details>
<details style="margin-left: 10px">
<summary>funding3</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Vetlesen Foundation
<p style="margin-left: 10px"><strong>country: </strong>Norway
</details>
<details style="margin-left: 10px">
<summary>funding4</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Norwegian Research Council
<p style="margin-left: 10px"><strong>grant: </strong>210004
<p style="margin-left: 10px"><strong>country: </strong>Norway
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>79.7733
<p style="margin-left: 0px"><strong>longitude: </strong>10.7378
<p style="margin-left: 0px"><strong>elevation: </strong>12
<p style="margin-left: 0px"><strong>siteName: </strong>Haklyutvatnet
<p style="margin-left: 0px"><strong>country: </strong>Svalbard and Jan Mayen
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB60381dc823
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
</details>
<details style="margin-left: 10px">
<summary>d2HC25 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBc5c2e8ea
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC25
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation source
<p style="margin-left: 20px"><strong>variableDetail: </strong>Competing influence of polar and maritime airmasses
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The hydrogen isotopic composition (D/H; dD using the delta notation) of leaf wax n-al- kanes reflects the D/H of source water used by a plant after modification by evaporation and biosynthetic fractionation (Kahmen et al., 2013a,b; Sachse et al., 2004, 2012), and therefore is useful for paleohydrologic reconstructions. The movement of water through the hydrologic cycle (Dansgaard, 1964), as well as regional and seasonal climatological conditions (Bowen and Revenaugh, 2003), results in variations of stable isotopes (D/H and 18O/16O) of local precipitation. Algae and macrophytes incorporate hydrogen from lake water while terrestrial plants use hydrogen from soil moisture; both water sources are ultimately derived from local precipitation. Therefore, dD of different n-alkanes can be used to reconstruct the climatic factors controlling the isotopic composi- tion of lake water and precipitation (Balascio et al., 2013; Rach et al., 2014).
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>seasonality: </strong>not specified, most likely growing season (June to August)
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d2HC27 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB13dc04eb
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC27
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation source
<p style="margin-left: 20px"><strong>variableDetail: </strong>Competing influence of polar and maritime airmasses
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The hydrogen isotopic composition (D/H; dD using the delta notation) of leaf wax n-al- kanes reflects the D/H of source water used by a plant after modification by evaporation and biosynthetic fractionation (Kahmen et al., 2013a,b; Sachse et al., 2004, 2012), and therefore is useful for paleohydrologic reconstructions. The movement of water through the hydrologic cycle (Dansgaard, 1964), as well as regional and seasonal climatological conditions (Bowen and Revenaugh, 2003), results in variations of stable isotopes (D/H and 18O/16O) of local precipitation. Algae and macrophytes incorporate hydrogen from lake water while terrestrial plants use hydrogen from soil moisture; both water sources are ultimately derived from local precipitation. Therefore, dD of different n-alkanes can be used to reconstruct the climatic factors controlling the isotopic composi- tion of lake water and precipitation (Balascio et al., 2013; Rach et al., 2014).
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>seasonality: </strong>not specified, most likely growing season (June to August)
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d2HC29 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd7a384df
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC29
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation source
<p style="margin-left: 20px"><strong>variableDetail: </strong>Competing influence of polar and maritime airmasses
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The hydrogen isotopic composition (D/H; dD using the delta notation) of leaf wax n-al- kanes reflects the D/H of source water used by a plant after modification by evaporation and biosynthetic fractionation (Kahmen et al., 2013a,b; Sachse et al., 2004, 2012), and therefore is useful for paleohydrologic reconstructions. The movement of water through the hydrologic cycle (Dansgaard, 1964), as well as regional and seasonal climatological conditions (Bowen and Revenaugh, 2003), results in variations of stable isotopes (D/H and 18O/16O) of local precipitation. Algae and macrophytes incorporate hydrogen from lake water while terrestrial plants use hydrogen from soil moisture; both water sources are ultimately derived from local precipitation. Therefore, dD of different n-alkanes can be used to reconstruct the climatic factors controlling the isotopic composi- tion of lake water and precipitation (Balascio et al., 2013; Rach et al., 2014).
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>seasonality: </strong>not specified, most likely growing season (June to August)
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d2HC31 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBf388e826
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC31
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation source
<p style="margin-left: 20px"><strong>variableDetail: </strong>Competing influence of polar and maritime airmasses
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The hydrogen isotopic composition (D/H; dD using the delta notation) of leaf wax n-al- kanes reflects the D/H of source water used by a plant after modification by evaporation and biosynthetic fractionation (Kahmen et al., 2013a,b; Sachse et al., 2004, 2012), and therefore is useful for paleohydrologic reconstructions. The movement of water through the hydrologic cycle (Dansgaard, 1964), as well as regional and seasonal climatological conditions (Bowen and Revenaugh, 2003), results in variations of stable isotopes (D/H and 18O/16O) of local precipitation. Algae and macrophytes incorporate hydrogen from lake water while terrestrial plants use hydrogen from soil moisture; both water sources are ultimately derived from local precipitation. Therefore, dD of different n-alkanes can be used to reconstruct the climatic factors controlling the isotopic composi- tion of lake water and precipitation (Balascio et al., 2013; Rach et al., 2014).
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>seasonality: </strong>not specified, most likely growing season (June to August)
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB60381dc8
<p style="margin-left: 10px"><strong>variableName: </strong>Age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>stdevC25 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBba4d631e
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC25
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>stdevC27 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBbdc9dedb
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC27
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>stdevC29 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa1b29ebc
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC29
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>stdevC31 (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1e989b0d
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC31
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d2HC25
```{r}
plotCol(thisTS,ind = 2)
```

### d2HC27
```{r}
plotCol(thisTS,ind = 4)
```

### d2HC29
```{r}
plotCol(thisTS,ind = 6)
```

### d2HC31
```{r}
plotCol(thisTS,ind = 8)
```

### Age
```{r}
plotCol(thisTS,ind = 1)
```

### stdevC25
```{r}
plotCol(thisTS,ind = 3)
```

### stdevC27
```{r}
plotCol(thisTS,ind = 5)
```

### stdevC29
```{r}
plotCol(thisTS,ind = 7)
```

### stdevC31
```{r}
plotCol(thisTS,ind = 9)
```
