---
title: "SP11BOAT"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 441
thisTS <- TS[which(udsn[i] == dsn)]
```
#SP11BOAT

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SP11BOAT.lpd)
            

[Download data only (csv)](SP11BOAT.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>speleothem
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Boch, R
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/jqs.1490
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>46.95
<p style="margin-left: 0px"><strong>longitude: </strong>10.55
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Klapferloch Cave, Austria
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATffbad747dc
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATe2c5370410
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP11BOAT01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Annual and homogenized precipitation data of the nearby station Nauders, however, reveal good correspondence with observed C and O isotope changes on a decadal timescale, considering the age uncertainties and different temporal resolution
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>multi-annual
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation_amount
<p style="margin-left: 20px"><strong>variableDetail: </strong>variations in paleoprecipitation amount on a multi-annual timescale (On longer timescales, however, the flowstone?s growth dynamics have to be considered)
<p style="margin-left: 20px"><strong>direction: </strong>decrease
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positve
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>There is kinetic osotope fractionation: Strongly positive correlation between d13C and d18O values in the younger segments with Dd13C/Dd18O slopes of 1?1.5. The older parts of the cores are characterized by a significantly lower degree of correlation and typically lower slopes. Linear fits of d13C vs. d18O in cores PFU8 and PFU9 show comparable slopes (1?1.5) but typically lower coefficients (in particular PFU8). Modern calcite precipitates also exhibit a strongly positive correlation of C and O isotope values (R2=0.87). A comparison of the drill core d18O values with calculated modern O isotopic equilibrium values based on monitoring data reveals O isotopic compositions close to isotopic equilibrium only for the calcite d18O minima.
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>multi-annual (not specified)
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Lack of seasonal signal in stable isotopic composition + the drip-water trace element concentrations strongly suggesta that most of the water discharging into this cave has a mean residence time well in excess of one year.
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>uncertainty is higher on long timescales due to flowstone?s growth dynamics
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
