---
title: "LS07ROTI"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 278
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS07ROTI

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS07ROTI.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Rosqvist, G. C. , Leng, M. J. , Jonsson, C.
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>17
<p style="margin-left: 10px"><strong>pages: </strong>-6
<p style="margin-left: 10px"><strong>pubYear: </strong>2007
<p style="margin-left: 10px"><strong>title: </strong>North Atlantic region atmospheric circulation dynamics inferred from a late-Holocene lacustrine carbonate isotope record, northern Swedish Lapland
<p style="margin-left: 10px"><strong>DOI: </strong>10.1177/0959683607080508
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>68.3
<p style="margin-left: 0px"><strong>longitude: </strong>18.7
<p style="margin-left: 0px"><strong>elevation: </strong>560
<p style="margin-left: 0px"><strong>siteName: </strong>Tibetanus
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS07ROTI
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>We argue that a substantial and persistent change in !p is required to change the annual mean values of d18Ow in northern Scandinavia.
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>rainfall source area
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>All the modern lake and groundwater isotope data lie on the Local Meteoric Water Line (LMWL) (IAEA/WMO, 2006) indicating that evaporation is not important. The similarity of the isotope composition of the lake and its different groundwater reservoirs indicate that the lake is likely to be constantly replenished by groundwater input and subterraneous outflow resulting in a short water residence time.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>our calculated [equilibium] d18OC values of ?12.7? are similar to core values from the last few hundred years, which lends support to the idea that the modern carbonates are precipitating in equilibrium.
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>>6 (infered from paper)
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>our calculated [equilibium] d18OC values of ?12.7? are similar to core values from the last few hundred years, which lends support to the idea that the modern carbonates are precipitating in equilibrium.
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>Lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>>6 (infered from paper)
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Groundwtaer
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>our calculated [equilibium] d18OC values of ?12.7? are similar to core values from the last few hundred years, which lends support to the idea that the modern carbonates are precipitating in equilibrium.
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>Lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>>6 (infered from paper)
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
