---
title: "MS12AMMM"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 397
thisTS <- TS[which(udsn[i] == dsn)]
```
#MS12AMMM

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](MS12AMMM.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>marine sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://doi.pangaea.de/10.1594/PANGAEA.780423
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>BM
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>McGregor, Helen V. , Evans, Michael N. , Goosse, Hugues , Leduc, Guillaume , Martrat, Belen , Addison, Jason A. , Mortyn, P. Graham , Oppo, Delia W. , Seidenkrantz, Marit-Solveig , Sicre, Marie-Alexandrine , Phipps, Steven J. , Selvaraj, Kandasamy , Thirumalai, Kaustubh , Filipsson, Helena L. , Ersek, Vasile
<p style="margin-left: 10px"><strong>citeKey: </strong>moreno2012the
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>43
<p style="margin-left: 10px"><strong>pages: </strong>-16
<p style="margin-left: 10px"><strong>pubYear: </strong>2012
<p style="margin-left: 10px"><strong>title: </strong>The Medieval Climate Anomaly in the Iberian Peninsula reconstructed from marine and lake records
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.2012.04.007
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>McGregor, Helen V. , Evans, Michael N. , Goosse, Hugues , Leduc, Guillaume , Martrat, Belen , Addison, Jason A. , Mortyn, P. Graham , Oppo, Delia W. , Seidenkrantz, Marit-Solveig , Sicre, Marie-Alexandrine , Phipps, Steven J. , Selvaraj, Kandasamy , Thirumalai, Kaustubh , Filipsson, Helena L. , Ersek, Vasile
<p style="margin-left: 10px"><strong>citeKey: </strong>mcgregor2015robust
<p style="margin-left: 10px"><strong>journal: </strong>Nature Geoscience
<p style="margin-left: 10px"><strong>volume: </strong>8
<p style="margin-left: 10px"><strong>pages: </strong>-6
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Robust global ocean cooling trend for the pre-industrial Common Era
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/ngeo2510
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>McGregor, Helen V. , Evans, Michael N. , Goosse, Hugues , Leduc, Guillaume , Martrat, Belen , Addison, Jason A. , Mortyn, P. Graham , Oppo, Delia W. , Seidenkrantz, Marit-Solveig , Sicre, Marie-Alexandrine , Phipps, Steven J. , Selvaraj, Kandasamy , Thirumalai, Kaustubh , Filipsson, Helena L. , Ersek, Vasile
<p style="margin-left: 10px"><strong>citeKey: </strong>moreno2012o2klrDataCitation
<p style="margin-left: 10px"><strong>title: </strong>O2kLR-Minorca.Moreno.2012
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>40.5
<p style="margin-left: 0px"><strong>longitude: </strong>4.03
<p style="margin-left: 0px"><strong>elevation: </strong>-2391
<p style="margin-left: 0px"><strong>siteName: </strong>Mediterranean (Minorca)
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD10e9f8f7
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>alkenone calibration to SST
<p style="margin-left: 20px"><strong>interpDirection: </strong>increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MS12AMMM01b
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>inferred seawater
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The Mg/Ca temperature record has been used to extract the temperature effect of the d18O from G. bulloides to obtain the sea water d18O (d18Osw), which is associated with salinity and thus becomes a proxy for sea surface salinity (SSS).
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>spring
<p style="margin-left: 20px"><strong>variable: </strong>salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Schmidt, 1999
<p style="margin-left: 20px"><strong>coefficient: </strong>NaN
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>NaN
<p style="margin-left: 20px"><strong>fraction: </strong>NaN
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>sea surface
<p style="margin-left: 20px"><strong>integrationTime: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>NaN
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (always)
<p style="margin-left: 20px"><strong>variable: </strong>salinity
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MS12AMMM02b
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>inferred seawater
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The Mg/Ca temperature record has been used to extract the temperature effect of the d18O from G. bulloides to obtain the sea water d18O (d18Osw), which is associated with salinity and thus becomes a proxy for sea surface salinity (SSS).
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>spring
<p style="margin-left: 20px"><strong>variable: </strong>salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Schmidt, 1999
<p style="margin-left: 20px"><strong>coefficient: </strong>NaN
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>NaN
<p style="margin-left: 20px"><strong>fraction: </strong>NaN
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>sea surface
<p style="margin-left: 20px"><strong>integrationTime: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>NaN
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (always)
<p style="margin-left: 20px"><strong>variable: </strong>salinity
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Uk37</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD312b2365
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>native UK37 ratio from which SST was calculated
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>notes</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7129c65e
<p style="margin-left: 10px"><strong>variableName: </strong>notes
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>quality-controlled data from Moreno et al. (2012) that was used in the O2K-LR analysis; alkenone data were measured in two cores (MINMC06-1 and MINMC06-2) from the same site; these two records were combined with the data sorted based on age.
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD10e9f8f7d
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Mg/Ca derived temperature
</details>
<details style="margin-left: 10px">
<summary>Mg_Ca</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD312b2365e
<p style="margin-left: 10px"><strong>variableName: </strong>Mg_Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>description: </strong>Mg/Ca ratio of foraminifera calcite
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD10e9f8f75
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Mg/Ca derived temperature
</details>
<details style="margin-left: 10px">
<summary>Mg_Ca</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD312b2365d
<p style="margin-left: 10px"><strong>variableName: </strong>Mg_Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>description: </strong>Mg/Ca ratio of foraminifera calcite
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 4)
```

### d18O
```{r}
plotCol(thisTS,ind = 7)
```

### Uk37
```{r}
plotCol(thisTS,ind = 2)
```

### notes
```{r}
plotCol(thisTS,ind = 3)
```

### temperature
```{r}
plotCol(thisTS,ind = 5)
```

### Mg_Ca
```{r}
plotCol(thisTS,ind = 6)
```

### temperature
```{r}
plotCol(thisTS,ind = 8)
```

### Mg_Ca
```{r}
plotCol(thisTS,ind = 9)
```
