---
title: "SP06DYCN"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 420
thisTS <- TS[which(udsn[i] == dsn)]
```
#SP06DYCN

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SP06DYCN.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>speleothem
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Dykoski, CA
<p style="margin-left: 10px"><strong>pubYear: </strong>2006
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.epsl.2005.01.036
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>25.28
<p style="margin-left: 0px"><strong>longitude: </strong>108.08
<p style="margin-left: 0px"><strong>elevation: </strong>680
<p style="margin-left: 0px"><strong>siteName: </strong>Dongge Cave, China
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP06DYCN01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Yuan et al. [12] observed that other northern low- latitude sites around the world (Venezuela, [24]; and Israel, [25]) record y18O changes similar to China that are inverted with respect to the y18O record in Greenland. However, these sites do not record the strong seasonal difference in precipitation observed in China. To broaden the interpretation of y18O values to these other sites, Yuan et al. [12] modified the previous explanation by describing how changes in the percentage of water vapor lost prior to reaching the subtropics varied over time using a Rayleigh fractionation model [26]. Integrated rainfall from  tropical sources to SE China during glacial times was calculated to be 65% of that during the mid-Holocene [12]. Thus, following this interpretation, changes in the proportion of precipitation reaching China corre- late with changes in Greenland temperature. The Yuan et al. [12] mechanism provides a single explanation for the fact that the y18O relationship seen in the northern tropics and subtropics at multiple sites is inverted with respect to Greenland.,evidence of equilibrium found from (1) lack of correlation between d18O and d13C and (2) Replicated sample from the same cave with different dripwater properties,groundwater d18O,from 1 to 19,,,,years,,,,,,Fraction of water vapor lost from an air mass,2,year,,,,,,,,,,,,,,,,,,,https://docs.google.com/spreadsheets/d/1OyOWgsBrRwp5sjVgqS1GFO2wnRkwGNY4wUXIpib45N4 SP06RACA01,SP06RACA,,SP06RACA01,Speleothem (SP),,Carlsbad.Rasmussen.2006,2006,10.1029/2006GL025714,,,,,,,,,, ,,,,32.1,104.26,,Carlsbad cave,,,LaminaeThickness,mm,Annual growth bands from two stalagmites sampled in two nearby caves,,number and thickeness of stalagmite layers,rainfall amount,Pacific-modulated precipitation variability during the late Holocene from the southwestern USA: mechanisms driving drought cycles,annual,,the thickness of the laminae decrease during periods of drought,,,,The data are supported by U-Th results,,,years,It has been demonstrated that some speleothems from the Guadalupe Mountains in southeastern New Mexico are annually banded, and variations in band thickness and mineralogy can be used as a record of regional relative moisture [Asmerom and Polyak, 2004].,,Changes in precipitation over relatively short time periods are indicated by hiatuses in stalagmite growth and large-scale shifts in band thickness,,,no isotopic analyes here,1,,,,,,,,,,,,,,,,,,,,https://docs.google.com/spreadsheets/d/1bxnCwCgUbDr2MFZp193p1MHzpsTuqPZuBYBzy1LcMCU SP07ASUS01A,SP07ASUS,,SP07ASUS01A,Speleothem (SP),,Asmerom, P,2007,10.1130/G22865A.1,,,,,,,,,, ,,,,32.083,-105.1667,,Pink Panter Cave, New Mexico,,,d18O,parts per mil,stable isotopes (d18O),,calcite powder,rainfall amount,more positive d18O values are interpreted to represent wetter conditions,under present conditions, wet years often have higehr amount of winter rain, but d18O may reflect high summer rain, winter rain, or both,negative,observed negative correlation between summer monsoon rainfall amount and d18O,,groundwater d18O,7-71,,,,years,observed negative correlation between summer monsoon rainfall amount and d18O,,negative,,,isotopic composition of rainfall,2,,,,,,,,,,,,,,,,,,,,https://docs.google.com/spreadsheets/d/1TLPUcn1ABQX_Rf5RWRDie6kyNZ6ZrNhq04Dpv-l2FvQ SP07DEUS01A,SP07DEUS,,SP07DEUS01A,Speleothem (SP),,Denniston, RF,2007,10.1016/j.yqres.2007.04.001,,,,,,,,,, ,,,,38.9,-92.3,,Devils Icebox Cave, Missouri,,,d18O,parts per mil,stable isotopes (d18O),,calcite powder,rainfall amount,more poritive d13C values reflect less rainfall amount,,negative,The influence of vegetation changes and changes in the water residence time on d13C of DIC. Drier conditions cause an increase of C4 plants in the vegetation and longer residence times of water in the bedrock (increasing the contribution of bedrock carbonate to DIC). Either one would cause an increase of d13C in the speleothem. Temperature changes may have a similar effect but would also affect d18O. Since d18O values are stable a temperature effect therefore can be eliminated.,repetition test comparing d18O and d13C of two speleothems shows similar trends,d13C of DIC; groundwater d18O,10-100,age model,,,years,,,,,,precipitation amount,,,,,,,,,,,,,,,,,,,,,https://docs.google.com/spreadsheets/d/1CKvU6bQUbaqK0SdowSO09No7Z9Hfx3wxtlzWgwIMamk SP07DEUS01A_d13C,SP07DEUS,,,Speleothem (SP),,Denniston, RF,2007,10.1016/j.yqres.2007.04.001,,,,,,,,,, ,,,,38.9,-92.3,,Devils Icebox Cave, Missouri,,,d13C,parts per mil,stable isotopes (d13C)  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,https://docs.google.com/spreadsheets/d/1CKvU6bQUbaqK0SdowSO09No7Z9Hfx3wxtlzWgwIMamk SP07FLOM01A,SP07FLOM,,SP07FLOM01A,Speleothem (SP),,Fleitmann, D,2007,10.1016/j.quascirev.2003.06.019,,,,,,,,,, ,,,,17.17,54.3,,Qunf Cave, Oman,,,d18O,parts per mil,stable isotopes d18O,,calcite powder,Indian Summer Monsoon,more negative values of d18O are interpreted as indicative of increased monsoon strength,year round,negative,Based on previously published results from Oman and Yemen, we interpret the oxygen isotope ratios of stalagmite calcite to primarily reflect variations in the amount of rainfall (termed ??amount effect??; Dansgaard, 1964;Rozanski et al., 1992), with more negative d18O reflecting higher monsoon rainfall (Burns et al., 1998, 2001, 2003; Neff et al., 2001; detailed discussion in Fleitmann et al., 2004). This interpretation is substantiated by isotopic time series of tropical precipitation (Dansgaard, 1964; Rozanski et al., 1992; Johnson and Ingram, 2004) and paleoclimate records from the ASM domain (e.g., Wei and Gasse, 1999; Wang et al., 2001, 2005; Dykoski et al., 2005), which confirm the inverse relationship between d18O and the amount of precipitation in regions affected by monsoons"
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>year round
<p style="margin-left: 20px"><strong>variable: </strong>East Asian Monsoon Strength
<p style="margin-left: 20px"><strong>variableDetail: </strong>more negative values of d18O are interpreted as indicative of increased monsoon strength
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>direction: </strong>northern moisture source for late Holocene gives a positive change in d18O
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>rainfall d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>from 1.5 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>year
<p style="margin-left: 20px"><strong>variable: </strong>amount of monsoon rainfall
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
