---
title: "TR17SAMA00"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 490
thisTS <- TS[which(udsn[i] == dsn)]
```
#TR17SAMA00

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](TR17SAMA00.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>wood
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Global and Planetary Change
<p style="margin-left: 10px"><strong>volume: </strong>157
<p style="margin-left: 10px"><strong>pages: </strong>73-82
<p style="margin-left: 10px"><strong>title: </strong>Moisture source signals preserved in a 242-year tree-ring δ 18 O chronology in the western Himalaya
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.gloplacha.2017.08.009
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>32.2167
<p style="margin-left: 0px"><strong>longitude: </strong>77.2167
<p style="margin-left: 0px"><strong>elevation: </strong>2700
<p style="margin-left: 0px"><strong>siteName: </strong>Manali
<p style="margin-left: 0px"><strong>country: </strong>India
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB30c97fa82
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>d18O of tree-cellulose of Abies Pindrow
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>calibration with instrumental rainfall record; More specifically, inverse correlations between the δ18O of precipitation and the amount of precipitation are observed at low latitudes, known as the ‘amount effect’ (Araguás-Araguás et al., 1998; Dansgaard, 1964). Therefore, smaller amounts of precipitation are associated with higher δ18O values for precipitation, representing the enrichment of 18O in the source water that is taken up by the trees.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.3481
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>precipitation
<p style="margin-left: 20px"><strong>variableDetail: </strong>precipitation amount during JJAS
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Warmer conditions enhance the evaporation of the soil water, which increases δ18O in the source water.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>0.25
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>temperature
<p style="margin-left: 20px"><strong>variableDetail: </strong>atmospheric surface temperature
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The isotopic composition of the leaf water originating from soil moisture is subsequently modulated by its transpiration through the stomata, leading to the preferential loss of the lighter isotope (16O) and the consequent enrichment of the leaf water 18O. During the transpiration process, lower relative humidity increases the δ18O of the leaf water.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.36
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>relative humidity
<p style="margin-left: 20px"><strong>variableDetail: </strong>surface relative humidity
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Because tree-ring δ18O correlates negatively with precipitation and relative humidity and positively with temperature, moisture-related climatic indices are expected to be suitable parameters to explain the variations in tree-ring oxygen isotopes.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.44
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>soil PDSI conditions
</details>
<details style="margin-left: 20px">
<summary>5</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>leaf water d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>a year
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>leafwater isotope
<p style="margin-left: 20px"><strong>variableDetail: </strong>isotopic composition of summer rainfall
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
