---
title: "Afr-LakeMalawi.Powers.2011"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- sapply(TS,"[[","geo_latitude")[ui]
lon <- sapply(TS,"[[","geo_longitude")[ui]
elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                       elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 2
thisTS <- TS[which(udsn[i] == dsn)]
```
#Afr-LakeMalawi.Powers.2011

Metadata {.sidebar}
-------------------------------------

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/13216
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Powers, Lindsay A.;Johnson, Thomas C.;Werne, Josef P.;Castañeda, Isla S.;Hopmans, Ellen C.;Sinninghe Damsté, Jaap S.;Schouten, Stefan
<p style="margin-left: 10px"><strong>citeKey: </strong>powers2011organicgeochemicalrecords
<p style="margin-left: 10px"><strong>journal: </strong>Palaeogeography, Palaeoclimatology, Palaeoecology
<p style="margin-left: 10px"><strong>volume: </strong>303
<p style="margin-left: 10px"><strong>pages: </strong>133-139
<p style="margin-left: 10px"><strong>pubYear: </strong>2011
<p style="margin-left: 10px"><strong>title: </strong>Organic geochemical records of environmental variability in Lake Malawi during the last 700 years, Part I: The TEX86 temperature record
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.palaeo.2010.09.006
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Powers, L.A.
<p style="margin-left: 10px"><strong>citeKey: </strong>powers2012httpswwwncdcnoaagovpaleostudy13216DataCitation
<p style="margin-left: 10px"><strong>title: </strong>World Data Center for Paleoclimatology
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>US NSF
<p style="margin-left: 10px"><strong>grant: </strong>ATM-0502456
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>agency: </strong>US NOAA
<p style="margin-left: 10px"><strong>grant: </strong>NA06OAR4310113
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-10.0033
<p style="margin-left: 0px"><strong>longitude: </strong>34.2883
<p style="margin-left: 0px"><strong>elevation: </strong>477
<p style="margin-left: 0px"><strong>siteName: </strong>Lake Malawi
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Africa
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>TEX86</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Malawi04
<p style="margin-left: 10px"><strong>variableName: </strong>TEX86
<p style="margin-left: 10px"><strong>units: </strong>NA
<p style="margin-left: 10px"><strong>description: </strong>mean TEX86 from 1-4 replicates
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>lake surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Malawi05
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred lake surface temperature
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>lake@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>core</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Malawi01
<p style="margin-left: 10px"><strong>variableName: </strong>core
<p style="margin-left: 10px"><strong>description: </strong>core name
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
leaflet() %>% 
  addTiles() %>% 
  #fitBounds(min(map.meta$lon),min(map.meta$lat),max(map.meta$lon),max(map.meta$lat)) %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff) %>% 
  addCircleMarkers(map.meta$lon, 
                   map.meta$lat, 
                   color = factpal(map.meta$archiveType),
                   radius = 5, 
                   fill = T,
                   fillOpacity = 1,
                   opacity = 1,
                   popup = paste(str_c('Dataset: <a href="',map.meta$link,'">',map.meta$dataSetName,'</a>'),
                                 str_c("Elevation: ",map.meta$elev),
                                 str_c("Archive Type: ",map.meta$archiveType),
                                 sep = "<br>")) %>%
  addCircleMarkers(map.meta$lon[i], 
                   map.meta$lat[i], 
                   color = "black",
                   radius = 12, 
                   fill = F,
                   opacity = 1) %>%
  addLabelOnlyMarkers(map.meta$lon[i], 
                      map.meta$lat[i], 
                      label = map.meta$dataSetName[i]) %>%
  addLegend("bottomleft",
            colors = unique(factpal(map.meta$archiveType)),
            labels = unique(map.meta$archiveType),
            opacity = 0.8)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### TEX86
```{r}
plotCol(thisTS,ind = 2)
```

### temperature
```{r}
plotCol(thisTS,ind = 3)
```

### core
```{r}
plotCol(thisTS,ind = 1)
```
