---
title: "Arc-Hvítárvatn.Larsen.2011"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- sapply(TS,"[[","geo_latitude")[ui]
lon <- sapply(TS,"[[","geo_longitude")[ui]
elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                       elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 50
thisTS <- TS[which(udsn[i] == dsn)]
```
#Arc-Hvítárvatn.Larsen.2011

Metadata {.sidebar}
-------------------------------------

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/14730
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Larsen, Darren J.;Miller, Gifford H.;Geirsdóttir, Áslaug;Thordarson, Thorvaldur
<p style="margin-left: 10px"><strong>citeKey: </strong>larsen2011a3000yearvarvedrecordofgl
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>30
<p style="margin-left: 10px"><strong>pages: </strong>2715-2731
<p style="margin-left: 10px"><strong>pubYear: </strong>2011
<p style="margin-left: 10px"><strong>title: </strong>A 3000-year varved record of glacier activity and climate change from the proglacial lake Hvítárvatn, Iceland
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.2011.05.026
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Larsen, D.J.
<p style="margin-left: 10px"><strong>citeKey: </strong>larsen2013httpswwwncdcnoaagovpaleostudy14730DataCitation
<p style="margin-left: 10px"><strong>title: </strong>World Data Center for Paleoclimatology
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>64.6
<p style="margin-left: 0px"><strong>longitude: </strong>-19.8
<p style="margin-left: 0px"><strong>elevation: </strong>422
<p style="margin-left: 0px"><strong>siteName: </strong>Hvítárvatn
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Arc
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>thickness</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Arc_021
<p style="margin-left: 10px"><strong>variableName: </strong>thickness
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>based on studies of glacier mass balance and glaciology in Iceland (e.g. Bjornsson; Flowers), I would agree that Icelandic glacier fluctuations are dominantly controlled by changes in melt season temperature. Glacier fluctuations influence the production and transport of eroded material and the eventual deposition of this sediment in a downstream basin (i.e. a proglacial lake). ... On short timescales (seasonal, annual, inter-annual), changes in sediment accumulation can be driven by many factors and we can all agree that identifying individual controls is messy. But on longer timescales (for example, centennial timescales, ... I would argue strongly that changes in sediment accumulation are driven by changes in glacier size. This is laid out in Larsen et al., 2011 QSR. We subsequently expanded on this initial study to: 1) include the whole Holocene (Larsen et al., 2012 QSR attached, which demonstrates a clear "8.2ka-event" signal and subsequent Neoglacial onset), and 2) by measuring varve thickness in multiple cores along a lake transect and tying the core data to seismic stratigraphy (Larsen et al. 2013 EPSL attached). This latter work demonstrates that the trends in sediment accumulation are consistent and observed throughout the lake basin. Given the available data, I feel comfortable summarizing as follows: Icelandic glacier fluctuations are dominantly controlled by summer temperature. On longer timescales, fluctuations of the Langjokull ice cap can be reconstructed from changes in mean varve thickness at glacial lake 'Hvitarvatn. with instrumental record'
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>6 7 8
<p style="margin-left: 20px"><strong>timescale: </strong>multidecadal to millennial
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
leaflet() %>% 
  addTiles() %>% 
  #fitBounds(min(map.meta$lon),min(map.meta$lat),max(map.meta$lon),max(map.meta$lat)) %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff) %>% 
  addCircleMarkers(map.meta$lon, 
                   map.meta$lat, 
                   color = factpal(map.meta$archiveType),
                   radius = 5, 
                   fill = T,
                   fillOpacity = 1,
                   opacity = 1,
                   popup = paste(str_c('Dataset: <a href="',map.meta$link,'">',map.meta$dataSetName,'</a>'),
                                 str_c("Elevation: ",map.meta$elev),
                                 str_c("Archive Type: ",map.meta$archiveType),
                                 sep = "<br>")) %>%
  addCircleMarkers(map.meta$lon[i], 
                   map.meta$lat[i], 
                   color = "black",
                   radius = 12, 
                   fill = F,
                   opacity = 1) %>%
  addLabelOnlyMarkers(map.meta$lon[i], 
                      map.meta$lat[i], 
                      label = map.meta$dataSetName[i]) %>%
  addLegend("bottomleft",
            colors = unique(factpal(map.meta$archiveType)),
            labels = unique(map.meta$archiveType),
            opacity = 0.8)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### thickness
```{r}
plotCol(thisTS,ind = 1)
```
