---
title: "CO00COKY"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 2
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO00COKY

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO00COKY.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/1855
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>NJA, Ally May
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cole, J.E.
<p style="margin-left: 10px"><strong>citeKey: </strong>cole2000tropical
<p style="margin-left: 10px"><strong>journal: </strong>Science
<p style="margin-left: 10px"><strong>volume: </strong>287
<p style="margin-left: 10px"><strong>pages: </strong>-2
<p style="margin-left: 10px"><strong>pubYear: </strong>2000
<p style="margin-left: 10px"><strong>title: </strong>Tropical Pacific Forcing of Decadal SST Variability in the Western Indian Ocean over the Past Two Centuries
<p style="margin-left: 10px"><strong>DOI: </strong>10.1126/science.287.5453.617
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Auer, Gerald , Piller, Werner E. , Reuter, Markus , Harzhauser, Mathias
<p style="margin-left: 10px"><strong>citeKey: </strong>auer2015correlating
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>30
<p style="margin-left: 10px"><strong>pages: </strong>-2
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Correlating carbon and oxygen isotope events in early to middle Miocene shallow marine carbonates in the Mediterranean region using orbitally tuned chemostratigraphy and lithostratigraphy
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2014PA002716
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cole, J.E.
<p style="margin-left: 10px"><strong>citeKey: </strong>cole2000ocean2khrDataCitation
<p style="margin-left: 10px"><strong>title: </strong>Ocean2kHR-IndianMalindiCole2000
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-3.2556
<p style="margin-left: 0px"><strong>longitude: </strong>40.1433
<p style="margin-left: 0px"><strong>elevation: </strong>-6
<p style="margin-left: 0px"><strong>siteName: </strong>Malindi Marine Park
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_001
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The coral 18O record from this site re- flects primarily SST; a linear regression of coral 18O versus SST yields a slope of0.24 per mil (‰) 18O per 1°C, explaining 47% of the SST variance (20).
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>0.47
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>.083 to 0.167 yrs
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>additional variability in coral 18O may arise from vari- ations in the 18O of seawater due to precip- itation, evaporation, or runoff, but at this site these changes are likely to be secondary be- cause local rainfall 18O is not strongly de- pleted from average seawater (21) and salin- ity gradients are small (22). Rainfall and SST influences are likely to be additive in terms of annual effect on coral 18O because warmer years tend to be wetter at this site.
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>.083 to 0.167 yrs
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
