---
title: "CO03COPM"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 11
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO03COPM

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO03COPM.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/1875
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>KLD, Stevenson
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2003el
<p style="margin-left: 10px"><strong>journal: </strong>Nature
<p style="margin-left: 10px"><strong>volume: </strong>424
<p style="margin-left: 10px"><strong>pages: </strong>-5
<p style="margin-left: 10px"><strong>pubYear: </strong>2003 2001
<p style="margin-left: 10px"><strong>title: </strong>El Nino/Southern Oscillation and tropical Pacific climate during the last millennium
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/nature01779, 10.1029/2001GL012918
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb, Kim M. , Charles, Christopher D. , Cheng, Hai , Kastner, Miriam , Edwards, R.Lawrence
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2003u
<p style="margin-left: 10px"><strong>journal: </strong>Earth and Planetary Science Letters
<p style="margin-left: 10px"><strong>volume: </strong>210
<p style="margin-left: 10px"><strong>pages: </strong>-5
<p style="margin-left: 10px"><strong>pubYear: </strong>2003
<p style="margin-left: 10px"><strong>title: </strong>U/Th-dating living and young fossil corals from the central tropical Pacific
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/S0012-821X(03)00138-9
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2013highly
<p style="margin-left: 10px"><strong>journal: </strong>Science
<p style="margin-left: 10px"><strong>volume: </strong>339
<p style="margin-left: 10px"><strong>pages: </strong>-5
<p style="margin-left: 10px"><strong>title: </strong>Highly Variable El Nino-Southern Oscillation Throughout the Holocene
<p style="margin-left: 10px"><strong>DOI: </strong>10.1126/science.1228246
</details>
<details style="margin-left: 10px">
<summary>pub4</summary>
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2001a
<p style="margin-left: 10px"><strong>journal: </strong>Geophys. Res. Lett.
<p style="margin-left: 10px"><strong>volume: </strong>28
<p style="margin-left: 10px"><strong>pages: </strong>-5
<p style="margin-left: 10px"><strong>title: </strong>A central tropical Pacific coral demonstrates Pacific, Indian, and Atlantic decadal climate connections
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2001GL012919
</details>
<details style="margin-left: 10px">
<summary>pub5</summary>
<p style="margin-left: 10px"><strong>citeKey: </strong>tierney2015tropical
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>30
<p style="margin-left: 10px"><strong>pages: </strong>-26
<p style="margin-left: 10px"><strong>title: </strong>Tropical sea surface temperatures for the past four centuries reconstructed from coral archives
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2014PA002717
</details>
<details style="margin-left: 10px">
<summary>pub6</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb, K.M.
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2003ocean2khrDataCitation
<p style="margin-left: 10px"><strong>title: </strong>Ocean2kHR-PacificPalmyracombinedCobb2003
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>5.87
<p style="margin-left: 0px"><strong>longitude: </strong>-162.13
<p style="margin-left: 0px"><strong>elevation: </strong>-7
<p style="margin-left: 0px"><strong>siteName: </strong>Palmyra (composite)
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_139
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM02A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM03A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM04C
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM05C
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM06C
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM07C
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM11C
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM08B
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM09B
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM10B
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO03COPM01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease/increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>ENSO variability is the dominant source of d18O variability in the Palmyra fossil-coral d18O records
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>83% variance shared with ENSO cycle
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>d18O tied to warmest month (Aug) and coolest month (Feb), linear interpolation used to obtain dates between
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>months
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 2)
```

### d18O
```{r}
plotCol(thisTS,ind = 3)
```

### d18O
```{r}
plotCol(thisTS,ind = 4)
```

### d18O
```{r}
plotCol(thisTS,ind = 5)
```

### d18O
```{r}
plotCol(thisTS,ind = 6)
```

### d18O
```{r}
plotCol(thisTS,ind = 7)
```

### d18O
```{r}
plotCol(thisTS,ind = 8)
```

### d18O
```{r}
plotCol(thisTS,ind = 9)
```

### d18O
```{r}
plotCol(thisTS,ind = 10)
```

### d18O
```{r}
plotCol(thisTS,ind = 11)
```

### d18O
```{r}
plotCol(thisTS,ind = 12)
```
