---
title: "CO04BAFI"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 12
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO04BAFI

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO04BAFI.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Bagnato, S., B.K. Linsley, S.S. Howe, G.M. Wellington, J. Salinger
<p style="margin-left: 10px"><strong>pubYear: </strong>2004
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2003PA000935
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>Bagnato, S., B.K. Linsley, S.S. Howe, G.M. Wellington, J. Salinger.
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-16.8167
<p style="margin-left: 0px"><strong>longitude: </strong>179.2333
<p style="margin-left: 0px"><strong>elevation: </strong>-2
<p style="margin-left: 0px"><strong>siteName: </strong>Savusavu Bay, Fiji
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO04BAFI01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>-0.15 per mil per degree C
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>80%
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>12-Jun
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The d18O  were tuned to the SST record by assigning the lowest (highest) d18O values of each year to the highest (lowest) SST. Age assignments were then linearly interpolated between these two annual anchor points using the Arand software package (P. Howell, personal commu- nication, 2002). A continuous monthly SST data set is available only as far back as 1970, so for age assignments before 1970 the lowest (highest) d18O and Sr/Ca values were assigned to March (August), March and August being the average times of highest and lowest SST, respectively, between 1970 and 1997
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1/12 to 2/12
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>12-Jun
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The d18O  were tuned to the SST record by assigning the lowest (highest) d18O values of each year to the highest (lowest) SST. Age assignments were then linearly interpolated between these two annual anchor points using the Arand software package (P. Howell, personal commu- nication, 2002). A continuous monthly SST data set is available only as far back as 1970, so for age assignments before 1970 the lowest (highest) d18O and Sr/Ca values were assigned to March (August), March and August being the average times of highest and lowest SST, respectively, between 1970 and 1997
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1/12 to 2/12
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO04BAFI02A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>-0.16 per mil per degree C
<p style="margin-left: 20px"><strong>direction: </strong>decrease
<p style="margin-left: 20px"><strong>fraction: </strong>80%
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>12-Jun
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The d18O  were tuned to the SST record by assigning the lowest (highest) d18O values of each year to the highest (lowest) SST. Age assignments were then linearly interpolated between these two annual anchor points using the Arand software package (P. Howell, personal commu- nication, 2002). A continuous monthly SST data set is available only as far back as 1970, so for age assignments before 1970 the lowest (highest) d18O and Sr/Ca values were assigned to March (August), March and August being the average times of highest and lowest SST, respectively, between 1970 and 1997
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1/12 to 2/12
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>12-Jun
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The d18O  were tuned to the SST record by assigning the lowest (highest) d18O values of each year to the highest (lowest) SST. Age assignments were then linearly interpolated between these two annual anchor points using the Arand software package (P. Howell, personal commu- nication, 2002). A continuous monthly SST data set is available only as far back as 1970, so for age assignments before 1970 the lowest (highest) d18O and Sr/Ca values were assigned to March (August), March and August being the average times of highest and lowest SST, respectively, between 1970 and 1997
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1/12 to 2/12
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO04BAFI00A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The d18O  were tuned to the SST record by assigning the lowest (highest) d18O values of each year to the highest (lowest) SST. Age assignments were then linearly interpolated between these two annual anchor points using the Arand software package (P. Howell, personal commu- nication, 2002). A continuous monthly SST data set is available only as far back as 1970, so for age assignments before 1970 the lowest (highest) d18O and Sr/Ca values were assigned to March (August), March and August being the average times of highest and lowest SST, respectively, between 1970 and 1997
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The d18O  were tuned to the SST record by assigning the lowest (highest) d18O values of each year to the highest (lowest) SST. Age assignments were then linearly interpolated between these two annual anchor points using the Arand software package (P. Howell, personal commu- nication, 2002). A continuous monthly SST data set is available only as far back as 1970, so for age assignments before 1970 the lowest (highest) d18O and Sr/Ca values were assigned to March (August), March and August being the average times of highest and lowest SST, respectively, between 1970 and 1997
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 2)
```

### d18O
```{r}
plotCol(thisTS,ind = 3)
```
