---
title: "CO99KUHO"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 89
thisTS <- TS[which(udsn[i] == dsn)]
```
#CO99KUHO

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](CO99KUHO.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Kuhnert, H., J. Pätzold, B. Hatcher, K.H. Wyrwoll, A. Eisenhauer, L. B. Collins, Z. R. Zhu, and G. Wefer
<p style="margin-left: 10px"><strong>pubYear: </strong>1999
<p style="margin-left: 10px"><strong>DOI: </strong>10.1007/s003380050147
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-28.4617
<p style="margin-left: 0px"><strong>longitude: </strong>113.7683
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Houtman Abrolhos Islands
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO99KUHO01Aa
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>fraction: </strong>50%
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>A first rough age assignment was based on the density banding pattern evident in x-radiographs over most portions of the coral core. Each couplet of one low- and one high-density band represents the growth of one year. The higher-resolving age model is based on the assumption, that coral d18O primarily depends on temperature. In the d18O data deriving from an annual banding couplet the highest value was assigned to the mid of September, the coldest month on average. The chronology is thus tied to one point within each year; the ages of the other sampling points were linearly interpolated according to their spatial distances along the sampling profile. In skeletal portions with unclear density banding pattern the stratigraphy is solely based on cyclic variations in coral d18O. Each cycle was assumed to represent an annual cycle, as long as it occurred over a skeletal portion extending between 10 and 20 mm. Assignments of sub-annual dates were performed as described
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1/100
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>CO99KUHO01Ab
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>fraction: </strong>50%
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>A first rough age assignment was based on the density banding pattern evident in x-radiographs over most portions of the coral core. Each couplet of one low- and one high-density band represents the growth of one year. The higher-resolving age model is based on the assumption, that coral d18O primarily depends on temperature. In the d18O data deriving from an annual banding couplet the highest value was assigned to the mid of September, the coldest month on average. The chronology is thus tied to one point within each year; the ages of the other sampling points were linearly interpolated according to their spatial distances along the sampling profile. In skeletal portions with unclear density banding pattern the stratigraphy is solely based on cyclic variations in coral d18O. Each cycle was assumed to represent an annual cycle, as long as it occurred over a skeletal portion extending between 10 and 20 mm. Assignments of sub-annual dates were performed as described
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>1/100
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature_water
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Salinity_water
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 2)
```
