---
title: "LS09MAAS"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 284
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS09MAAS

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS09MAAS.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Marshall, Michael H. , Lamb, Henry F. , Davies, Sarah J. , Leng, Melanie J. , Kubsa, Zelalem , Umer, Mohammed , Bryant, Charlotte
<p style="margin-left: 10px"><strong>journal: </strong>Palaeogeography, Palaeoclimatology, Palaeoecology
<p style="margin-left: 10px"><strong>volume: </strong>279
<p style="margin-left: 10px"><strong>pages: </strong>114127
<p style="margin-left: 10px"><strong>pubYear: </strong>2009
<p style="margin-left: 10px"><strong>title: </strong>Climatic change in northern Ethiopia during the past 17,000degreesyears: A diatom and stable isotope record from Lake Ashenge
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.palaeo.2009.05.003
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>12.5833
<p style="margin-left: 0px"><strong>longitude: </strong>39.4833
<p style="margin-left: 0px"><strong>elevation: </strong>2440
<p style="margin-left: 0px"><strong>siteName: </strong>Ashenge
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS09MAAS
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Where water loss is mainly through evaporation as is likely for Lake Ashenge, the waters tend to have a variable and elevated oxygen isotope composition relative to regional rainfall (which tends to be negative). Measured ?18Ocarb values are always higher than those of ambient precipitation as the lighter isotope 16O is preferentially lost to evaporation (Leng et al.,2006)...The isotope records from Ashenge therefore show large swings in composition as the ratio of precipitation to evaporation (P/E) has changed through time
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology, unknown lake residence time
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>Years
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>Lake water
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology, unknown lake residence time
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>Years
<p style="margin-left: 20px"><strong>variable: </strong>Temperature
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
