---
title: "LS10CLTA"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 294
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS10CLTA

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS10CLTA.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Clegg
<p style="margin-left: 10px"><strong>pubYear: </strong>2010
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.20 09.12.0 09
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>67.35
<p style="margin-left: 0px"><strong>longitude: </strong>153.67
<p style="margin-left: 0px"><strong>elevation: </strong>275
<p style="margin-left: 0px"><strong>siteName: </strong>Takahula
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS10CLTA
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The dominant role of winter precipitation (Pw) in the waterbalance of Takahula Lake suggests that the lake should be particularly  sensitive to interannual changes in the strength and position  of the AL. A westerly AL corresponds to increased moisture delivery  into interior Alaska, whereas an easterly AL results in storm  systems that cross the Coastal Range and the Alaska Range and cut  off winter moisture supply to interior Alaska
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation
<p style="margin-left: 20px"><strong>variableDetail: </strong>Strength & position of Aleutian low
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>These exceptionally low values suggest that factors other than effective moisture must have contributed to the pronounced variations in the Takahula Lake d18O  record. Increased winter precipitation associated with a westerly Aleutian Low position may account for 1 permil of the d18O decrease. Other factors leading to the 18O-depletion during these periods probably  include decreased temperatures, as well as increased lake-ice cover and associated reductions in evaporation.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>12-100
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>decrease
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>12-100
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>variable: </strong>Evaporation (P-E)
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>basis: </strong>A lowering of lake level by 0.5m would turn the lake into a topographically closed basin. Under such conditions, evaporation becomes the main  process of water loss, and lake-water continues to become 18Oenriched  until d18O of the evaporating vapor equals d18O of the input (Gat and Levy, 1978; Leng and Marshall, 2004). In contrast, a more positive water balance than the present is expected to  shorten the lake?s water-residence time, reducing the influence of evaporation on the lake?s isotope composition (Craig, 1961). Thus  the d18OCc record can be used to infer qualitative changes in  effective moisture.
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>12-100
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronological
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
