---
title: "LS12THAY"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 317
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS12THAY

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS12THAY.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://www.ncdc.noaa.gov/paleo/pubs/jopl2012arctic/jopl2012arctic.html
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>EKT
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Thomas
<p style="margin-left: 10px"><strong>pubYear: </strong>2012
<p style="margin-left: 10px"><strong>DOI: </strong>10.?1007/?s10933-012-9584-7
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>70.459
<p style="margin-left: 0px"><strong>longitude: </strong>-70.086
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Ayr Lake
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY01E
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The remarkable similarity between d2Hwax and regional temperature indicates that d2Hwax is a useful proxy to reconstruct temper- ature at decadal- to sub-centennial-resolution.
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Bottom line: more snowmelt providing source water to plants causes pool of plant source water to be more 2H-depleted. "The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake."
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>winter snow melting during growing season
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY01B
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The remarkable similarity between d2Hwax and regional temperature indicates that d2Hwax is a useful proxy to reconstruct temper- ature at decadal- to sub-centennial-resolution.
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Bottom line: more snowmelt providing source water to plants causes pool of plant source water to be more 2H-depleted. "The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake."
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>winter snow melting during growing season
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY01C
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The remarkable similarity between d2Hwax and regional temperature indicates that d2Hwax is a useful proxy to reconstruct temper- ature at decadal- to sub-centennial-resolution.
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Bottom line: more snowmelt providing source water to plants causes pool of plant source water to be more 2H-depleted. "The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake."
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>winter snow melting during growing season
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY01D
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The remarkable similarity between d2Hwax and regional temperature indicates that d2Hwax is a useful proxy to reconstruct temper- ature at decadal- to sub-centennial-resolution.
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Bottom line: more snowmelt providing source water to plants causes pool of plant source water to be more 2H-depleted. "The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake."
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>winter snow melting during growing season
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY01E
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The remarkable similarity between d2Hwax and regional temperature indicates that d2Hwax is a useful proxy to reconstruct temper- ature at decadal- to sub-centennial-resolution.
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Bottom line: more snowmelt providing source water to plants causes pool of plant source water to be more 2H-depleted. "The major source of water for plants in the Arctic, where permafrost precludes extensive groundwater systems, is precipitation, either as snowmelt or summer rain (Elberling et al. 2008). Thus, we hypothesize that d2Hwax in the Arctic is likely closely related to d2Hprecip. Leaf wax synthesis occurs during the summer months when plants are neither temper- ature- nor light-limited. The apparent fractionation (e) between leaf waxes and source waters varies with relative humidity (RH) and with potential evapotrans- piration (Sachse et al. 2012). Long-term average growing season (June, July, August) RH at Clyde River is 80% (Environment Canada, 2011). The eleven-month dataset from Silasiutitalik at the head of Clyde Inlet suggests that growing season RH is slightly lower inland, around 75% (Kangiqtugaapik (Clyde River) Weather Station Network, 2011). The n-alkanoic acids synthesized by plants that grow at 70?80% RH have an e of -100 to -120% relative to annual mean precipitation (Hou et al. 2008). The d2Hwax values from Ayr Lake sediments (-240 to -265 %) therefore suggest that source water d2H should range between -140 to -165% (assuming an e of -100%) and -120 to -145% (assuming an e of -120%). These calculated source water d2H values are within the range of measured summer d2Hprecip values for both Pond Inlet and Hall Beach, although the values obtained with the larger e are close to the maximum summer d2Hprecip values for Pond Inlet. We therefore hypothesize that plants in this catchment utilize summer precipitation as their main water source (Fig. 2). Variability in summer d2Hprecip, or utilization of small but varying amounts of winter precipitation, is likely driving variability in d2Hwax at Ayr Lake."
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 to 10
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Leaf wax hydrogen isotopes exhibit a surprising amount of variability at the sub-decadal scale (Fig. 6). This high degree of variability indicates that leaf waxes are likely produced, transported and deposited in a relatively short period of time.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>10
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>winter snow melting during growing season
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY0130s
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY0124s
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY0126s
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY0128s
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS12THAY0130s
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD
```{r}
plotCol(thisTS,ind = 1)
```

### dD
```{r}
plotCol(thisTS,ind = 2)
```

### dD
```{r}
plotCol(thisTS,ind = 3)
```

### dD
```{r}
plotCol(thisTS,ind = 4)
```

### dD
```{r}
plotCol(thisTS,ind = 5)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 6)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 7)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 8)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 9)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 10)
```
