---
title: "LS13BAFL"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 319
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS13BAFL

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS13BAFL.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Balascio, N. L. , DAndrea, W. J. , Bradley, R. S. , Perren, B. B.
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>23
<p style="margin-left: 10px"><strong>pages: </strong>14281439
<p style="margin-left: 10px"><strong>pubYear: </strong>2013
<p style="margin-left: 10px"><strong>title: </strong>Biogeochemical evidence for hydrologic changes during the Holocene in a lake sediment record from southeast Greenland
<p style="margin-left: 10px"><strong>DOI: </strong>10.1177/0959683613493938
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>65.6107
<p style="margin-left: 0px"><strong>longitude: </strong>-37.6935
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Flower Valley Lake
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS13BAFL01D
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>not interpreted to reflect climate (note by Iso2k compiler: dD precip does not change seasonally in this part of Greenland, likely because source areas are proximal and carry relatively enriched moisture to this region throughout the year)
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>?D values of long-chain n-alkanes (?Dwax) reflect ?D of water used by terrestrial vegetation after modification by biosynthetic processes (Sachse et al., 2012 and references therein). Soil mois- ture provides the source water for terrestrial plants, while lake water is the source for aquatic macrophytes and algae. ?D of water in soils can be modified to some extent from ?D of annual precipitation by evaporation. However, it has been shown that ?Dwax is unaltered by plants following leaf formation and there- fore reflects ?Dwater used during leaf flush (Kahmen et al., 2011; Sachse et al., 2010; Tipple et al., 2013). In the Arctic, the majority of leaf formation takes place in late spring/early summer follow- ing the return of appreciable sunlight. Because snowmelt is the predominant water source available to plants at the time of leaf formation, the ?Dwax is potentially biased toward wintertime ?Dp (i.e. snowfall months). In Tasiilaq, the difference between precip- itation-weighted annual average ?Dp (?92?) and precipitation- weighted average ?Dp during months with below zero average temperatures (October?April; ?96?) is negligible (Bowen, 2008; Cappelen et al., 2011), and thus, any changes in the timing of leaf formation during the Holocene, or in the seasonality of precipita- tion, are unlikely to have had much impact on ?Dwax.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>see interpretation for independentParameter1
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>variable: </strong>winter snow melting during growing season
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS13BAFL01B
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>aquatic biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The extent of isotopic enrichment of surface waters from meteoric water is determined by the degree of evaporative enrichment of the water body (Leng and Anderson, 2003). Therefore, ... the ?D of lipids produced by aquatic plants (?Daq) tracks the degree of evaporative isotopic enrichment of lake water from meteoric water...."The relatively D-enriched values (more positive ?D) of ?D25 and ?D27 are consistent with our interpretation that these compounds reflect isotopically enriched lake water."
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ice-free season
<p style="margin-left: 20px"><strong>variable: </strong>moisture balance (P-E)
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>?D values of long-chain n-alkanes (?Dwax) reflect ?D of water used by terrestrial vegetation after modification by biosynthetic processes (Sachse et al., 2012 and references therein). Soil mois- ture provides the source water for terrestrial plants, while lake water is the source for aquatic macrophytes and algae. ?D of water in soils can be modified to some extent from ?D of annual precipitation by evaporation. However, it has been shown that ?Dwax is unaltered by plants following leaf formation and there- fore reflects ?Dwater used during leaf flush (Kahmen et al., 2011; Sachse et al., 2010; Tipple et al., 2013). In the Arctic, the majority of leaf formation takes place in late spring/early summer follow- ing the return of appreciable sunlight. Because snowmelt is the predominant water source available to plants at the time of leaf formation, the ?Dwax is potentially biased toward wintertime ?Dp (i.e. snowfall months). In Tasiilaq, the difference between precip- itation-weighted annual average ?Dp (?92?) and precipitation- weighted average ?Dp during months with below zero average temperatures (October?April; ?96?) is negligible (Bowen, 2008; Cappelen et al., 2011), and thus, any changes in the timing of leaf formation during the Holocene, or in the seasonality of precipita- tion, are unlikely to have had much impact on ?Dwax.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>see interpretation for independentParameter1
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS13BAFL01C
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>not interpreted to reflect climate (note by Iso2k compiler: dD precip does not change seasonally in this part of Greenland, likely because source areas are proximal and carry relatively enriched moisture to this region throughout the year)
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>?D values of long-chain n-alkanes (?Dwax) reflect ?D of water used by terrestrial vegetation after modification by biosynthetic processes (Sachse et al., 2012 and references therein). Soil mois- ture provides the source water for terrestrial plants, while lake water is the source for aquatic macrophytes and algae. ?D of water in soils can be modified to some extent from ?D of annual precipitation by evaporation. However, it has been shown that ?Dwax is unaltered by plants following leaf formation and there- fore reflects ?Dwater used during leaf flush (Kahmen et al., 2011; Sachse et al., 2010; Tipple et al., 2013). In the Arctic, the majority of leaf formation takes place in late spring/early summer follow- ing the return of appreciable sunlight. Because snowmelt is the predominant water source available to plants at the time of leaf formation, the ?Dwax is potentially biased toward wintertime ?Dp (i.e. snowfall months). In Tasiilaq, the difference between precip- itation-weighted annual average ?Dp (?92?) and precipitation- weighted average ?Dp during months with below zero average temperatures (October?April; ?96?) is negligible (Bowen, 2008; Cappelen et al., 2011), and thus, any changes in the timing of leaf formation during the Holocene, or in the seasonality of precipita- tion, are unlikely to have had much impact on ?Dwax.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>see interpretation for independentParameter1
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS13BAFL01D
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>not interpreted to reflect climate (note by Iso2k compiler: dD precip does not change seasonally in this part of Greenland, likely because source areas are proximal and carry relatively enriched moisture to this region throughout the year)
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>?D values of long-chain n-alkanes (?Dwax) reflect ?D of water used by terrestrial vegetation after modification by biosynthetic processes (Sachse et al., 2012 and references therein). Soil mois- ture provides the source water for terrestrial plants, while lake water is the source for aquatic macrophytes and algae. ?D of water in soils can be modified to some extent from ?D of annual precipitation by evaporation. However, it has been shown that ?Dwax is unaltered by plants following leaf formation and there- fore reflects ?Dwater used during leaf flush (Kahmen et al., 2011; Sachse et al., 2010; Tipple et al., 2013). In the Arctic, the majority of leaf formation takes place in late spring/early summer follow- ing the return of appreciable sunlight. Because snowmelt is the predominant water source available to plants at the time of leaf formation, the ?Dwax is potentially biased toward wintertime ?Dp (i.e. snowfall months). In Tasiilaq, the difference between precip- itation-weighted annual average ?Dp (?92?) and precipitation- weighted average ?Dp during months with below zero average temperatures (October?April; ?96?) is negligible (Bowen, 2008; Cappelen et al., 2011), and thus, any changes in the timing of leaf formation during the Holocene, or in the seasonality of precipita- tion, are unlikely to have had much impact on ?Dwax.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>see interpretation for independentParameter1
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD
```{r}
plotCol(thisTS,ind = 1)
```

### dD
```{r}
plotCol(thisTS,ind = 2)
```

### dD
```{r}
plotCol(thisTS,ind = 3)
```

### dD
```{r}
plotCol(thisTS,ind = 4)
```
