---
title: "LS14KOSA"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 327
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS14KOSA

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS14KOSA.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Konecky, Bronwen , Russell, James , Huang, Yongsong , Vuille, Mathias , Cohen, Lily , Street-Perrott, F. Alayne
<p style="margin-left: 10px"><strong>journal: </strong>Palaeogeography, Palaeoclimatology, Palaeoecology
<p style="margin-left: 10px"><strong>volume: </strong>396
<p style="margin-left: 10px"><strong>pages: </strong>-8
<p style="margin-left: 10px"><strong>pubYear: </strong>2014
<p style="margin-left: 10px"><strong>title: </strong>Impact of monsoons, temperature, and CO2 on the rainfall and ecosystems of Mt. Kenya during the Common Era
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.palaeo.2013.12.037
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>0.0833
<p style="margin-left: 0px"><strong>longitude: </strong>37.5333
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Sacred Lake
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14KOSA01A
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Indian source: "Sacred Lake currently receives no Atlantic-derived precipi- tation, and its elevation, northeastern slope exposure, and rainfall seasonality make it particularly susceptible to changes in the Indian Ocean monsoons. In contrast, equatorial lakes in central Kenya (e.g. Lake Naivasha) and the western Rift Valley (e.g. Lake Edward, Uganda/ Congo) receive a mixture of Indian- and Atlantic-derived moisture, and hence are sensitive to both monsoons (Nicholson, 1996). " Moisture transport and temperature influence: "The strength of low-level equatorial westerlies in the Indian Ocean has been linked to East African lake levels as well as Mt. Kenyas glaciers, with stronger (weaker) winds inhibiting (enhanc- ing) precipitation in East Africa (Hastenrath, 2001). Overall, these west- erlies have increased in strength since the 1880s. This important Indian Ocean forcing may explain Sacred Lakes particular sensitivity to these changes, and recent drying may have also been locally enhanced by a re- cent rise in temperature (via an upward shift in the ZMR and/or in- creased evaporation of soil water)"
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>OND
<p style="margin-left: 20px"><strong>variable: </strong>strength of Indian ocean moisture transport
<p style="margin-left: 20px"><strong>variableDetail: </strong>Indian monsoon
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>In East Africa, stable isotopes in modern precipitation have been shown to reflect large-scale atmospheric circulation processes (Vuille et al., 2005), and the ?18O of precipitation (and by inference, the ?D of precipitation) on Mt. Kenya has been shown to be a good indicator of moisture balance (Barker et al., 2001). Leaf wax ?D reflects ?Dprecip, after a series of offsets due to soil water evaporation, fractionation of leaf water relative to xylem water, and biosynthesis (Sachse et al., 2012).
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Air temperature has 2 influences: "air temperature is important for the elevation of the zone of maximum rainfall (ZMR) on Mt. Kenya" and for soil/lake evaporation. "Recent drying may have also been locally enhanced by a recent rise in temperature (via an upward shift in the ZMR and/or increased evaporation of soil water)."
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>air temperature
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD
```{r}
plotCol(thisTS,ind = 1)
```
