---
title: "LS14FEZA"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 325
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS14FEZA

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS14FEZA.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Feakins, Sarah J. , Kirby, Matthew E. , Cheetham, Michael I. , Ibarra, Yadira , Zimmerman, Susan R.H.
<p style="margin-left: 10px"><strong>pubYear: </strong>2014
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.orggeochem.2013.10.015
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>34.7778
<p style="margin-left: 0px"><strong>longitude: </strong>-120.0392
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Zaca Lake
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FEZA01B
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>biomarkers
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Downcore variation involved subtle changes in distribution, C22 and C24 covarying and suggesting a similar source, perhaps partially aquatic, with an increase in recent decades perhaps related to indirect fertilization of the lake (Fig. 5a).
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water and soil water
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Veg
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FEZA01C
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>These changes in moisture source have been further linked to SST anomalies (SSTa) in the Kuroshio Extension region of the N Pacific, which exerts steering on atmo- spheric circulation and hence moisture sources to the west coast of N America. ... These positive excursions may be linked to warm Kuroshio Extension SSTa, driv- ing greater amplitude waves in the circulation over the N Pacific entraining subtropical moisture sources but generally associated with drier conditions in coastal southern California. Conversely negative isotopic excursions centered on 300 and 800 yr BP may correspond to more N Pacific moisture flux and wetter conditions in coastal southern California, the former of these perhaps associ- ated with the Little Ice Age. In combination with other proxies recording wet/dry climate regime shifts, the information on mois- ture source from precipitation isotopes may thus be particularly helpful in understanding the dynamical causes of hydroclimate shifts. Warm SST anomaly --> less moisture flux -->more enriched precipitation. "Elevated dD values indi- cate more (sub)tropical moisture sources and/or drier conditions, whereas lower dD values are consistent with N Pacific moisture sources and/or more antecedent precipitation. "
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>Moisture flux from the subtropical North Pacific (driven by SST anomalies in the Kuroshio Extension region)
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>SEASONALITY: "First, during water uptake, plants are expected to sample the spring growing season precipitation, at the end of the wet season [October-March], as the temperature warms up and before the dry summer months (Feakins and Sessions, 2010; Kahmen et al., 2011; Tipple et al., 2013). During this time, the plants may record the isotopic signature of just a few storms each year heightening variability; however, sedimentary samples integrating a decade might average the signal from > 20 storms. " PARAMETER: "Paleoclimatic interpretation of the precipitation isotopic history recorded in the Crystal Cave has been suggested to record changes in moisture source primarily and local amount effect secondarily (McCabe-Glynn et al., 2013). ... Our record provides an extension of the Crystal Cave isotopic record, from a more southerly coastal location, but likely also records interdecadal variability in the same processes. ... We suggest that the plant leaf wax record preferentially captures spring precipitation isotopic anomalies integrated over decades, providing a sensitive record of atmospheric circulation and moisture source changes. "
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Rapid transfer from plant to sediment is likely within the small, steep-sided watershed, suggesting that the leaf wax record would be capable of reconstructing up to decadal resolution variation in leaf wax dD values.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>spring
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>SEASONALITY: "First, during water uptake, plants are expected to sample the spring growing season precipitation, at the end of the wet season [October-March], as the temperature warms up and before the dry summer months (Feakins and Sessions, 2010; Kahmen et al., 2011; Tipple et al., 2013). During this time, the plants may record the isotopic signature of just a few storms each year heightening variability; however, sedimentary samples integrating a decade might average the signal from > 20 storms. " PARAMETER: "Paleoclimatic interpretation of the precipitation isotopic history recorded in the Crystal Cave has been suggested to record changes in moisture source primarily and local amount effect secondarily (McCabe-Glynn et al., 2013). ... Our record provides an extension of the Crystal Cave isotopic record, from a more southerly coastal location, but likely also records interdecadal variability in the same processes."
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>spring
<p style="margin-left: 20px"><strong>variable: </strong>precipitation amount
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Secondly, plant community changes in the catchment (or other ecological changes) may influence the dD record. Vegetation changes could reasonably have an influence on the mean catchment ewax/precip that lasts for decades, so this mecha- nism might operate too slowly to explain sample-to-sample vari- ability in the sediment, although it may contribute to the multi- decadal variability. We observed abundance variation in homo- logues downcore (Fig. 5), which could be consistent with ecological changes influencing dD values; however, the non-unique chain length distributions of different plant species (Bush and McIner- ney, 2013) make it impossible to draw unique solutions here.
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>plant community composition
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FEZA01D
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>These changes in moisture source have been further linked to SST anomalies (SSTa) in the Kuroshio Extension region of the N Pacific, which exerts steering on atmo- spheric circulation and hence moisture sources to the west coast of N America. ... These positive excursions may be linked to warm Kuroshio Extension SSTa, driv- ing greater amplitude waves in the circulation over the N Pacific entraining subtropical moisture sources but generally associated with drier conditions in coastal southern California. Conversely negative isotopic excursions centered on 300 and 800 yr BP may correspond to more N Pacific moisture flux and wetter conditions in coastal southern California, the former of these perhaps associ- ated with the Little Ice Age. In combination with other proxies recording wet/dry climate regime shifts, the information on mois- ture source from precipitation isotopes may thus be particularly helpful in understanding the dynamical causes of hydroclimate shifts. Warm SST anomaly --> less moisture flux -->more enriched precipitation. "Elevated dD values indi- cate more (sub)tropical moisture sources and/or drier conditions, whereas lower dD values are consistent with N Pacific moisture sources and/or more antecedent precipitation. "
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>Moisture flux from the subtropical North Pacific (driven by SST anomalies in the Kuroshio Extension region)
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>SEASONALITY: "First, during water uptake, plants are expected to sample the spring growing season precipitation, at the end of the wet season [October-March], as the temperature warms up and before the dry summer months (Feakins and Sessions, 2010; Kahmen et al., 2011; Tipple et al., 2013). During this time, the plants may record the isotopic signature of just a few storms each year heightening variability; however, sedimentary samples integrating a decade might average the signal from > 20 storms. " PARAMETER: "Paleoclimatic interpretation of the precipitation isotopic history recorded in the Crystal Cave has been suggested to record changes in moisture source primarily and local amount effect secondarily (McCabe-Glynn et al., 2013). ... Our record provides an extension of the Crystal Cave isotopic record, from a more southerly coastal location, but likely also records interdecadal variability in the same processes. ... We suggest that the plant leaf wax record preferentially captures spring precipitation isotopic anomalies integrated over decades, providing a sensitive record of atmospheric circulation and moisture source changes. "
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>Rapid transfer from plant to sediment is likely within the small, steep-sided watershed, suggesting that the leaf wax record would be capable of reconstructing up to decadal resolution variation in leaf wax dD values.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>spring
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>SEASONALITY: "First, during water uptake, plants are expected to sample the spring growing season precipitation, at the end of the wet season [October-March], as the temperature warms up and before the dry summer months (Feakins and Sessions, 2010; Kahmen et al., 2011; Tipple et al., 2013). During this time, the plants may record the isotopic signature of just a few storms each year heightening variability; however, sedimentary samples integrating a decade might average the signal from > 20 storms. " PARAMETER: "Paleoclimatic interpretation of the precipitation isotopic history recorded in the Crystal Cave has been suggested to record changes in moisture source primarily and local amount effect secondarily (McCabe-Glynn et al., 2013). ... Our record provides an extension of the Crystal Cave isotopic record, from a more southerly coastal location, but likely also records interdecadal variability in the same processes."
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>spring
<p style="margin-left: 20px"><strong>variable: </strong>precipitation amount
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Secondly, plant community changes in the catchment (or other ecological changes) may influence the dD record. Vegetation changes could reasonably have an influence on the mean catchment ewax/precip that lasts for decades, so this mecha- nism might operate too slowly to explain sample-to-sample vari- ability in the sediment, although it may contribute to the multi- decadal variability. We observed abundance variation in homo- logues downcore (Fig. 5), which could be consistent with ecological changes influencing dD values; however, the non-unique chain length distributions of different plant species (Bush and McIner- ney, 2013) make it impossible to draw unique solutions here.
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>plant community composition
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FEZA01F
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>biomarkers
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>not interpreted
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd239c4652
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>description: </strong>stdev of d2H measurements
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd72fd146
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>description: </strong>stdev of d2H measurements
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9e7bf79e
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>description: </strong>stdev of d2H measurements
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9e7bf79e2
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>description: </strong>stdev of d2H measurements
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FEZA01E
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>biomarkers
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>not interpreted
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd239c465
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>description: </strong>stdev of d2H measurements
</details>
<details style="margin-left: 10px">
<summary>dD</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FEZA01F
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>biomarkers
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>not interpreted
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dDUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd239c4652
<p style="margin-left: 10px"><strong>variableName: </strong>dDUncertainty
<p style="margin-left: 10px"><strong>description: </strong>stdev of d2H measurements
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD
```{r}
plotCol(thisTS,ind = 3)
```

### dD
```{r}
plotCol(thisTS,ind = 5)
```

### dD
```{r}
plotCol(thisTS,ind = 7)
```

### dD
```{r}
plotCol(thisTS,ind = 1)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 2)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 4)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 6)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 8)
```

### dD
```{r}
plotCol(thisTS,ind = 9)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 10)
```

### dD
```{r}
plotCol(thisTS,ind = 11)
```

### dDUncertainty
```{r}
plotCol(thisTS,ind = 12)
```
