---
title: "LS15ABSH"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 334
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS15ABSH

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS15ABSH.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Abu-Zied, R. H. , Bantan, R. A.
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>25
<p style="margin-left: 10px"><strong>pages: </strong>-11
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Palaeoenvironment, palaeoclimate and sea-level changes in the Shuaiba Lagoon during the late Holocene (last 3.6 ka), eastern Red Sea coast, Saudi Arabia
<p style="margin-left: 10px"><strong>DOI: </strong>10.1177/0959683615584204
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>20.7
<p style="margin-left: 0px"><strong>longitude: </strong>39.4333
<p style="margin-left: 0px"><strong>elevation: </strong>0
<p style="margin-left: 0px"><strong>siteName: </strong>Shuaiba Lagoon
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS15ABSH01a
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>It is notable that the periods of ?18O enrichment in the core are in agreement with the high relative abundance of the epiphytic, algal symbiont Sorites orbiculus and "The ?13C values of Elphidium striatopunctatum co-vary, with ?18O values indicating a warm, evaporative basin, where degassing of CO2 from the water leads to the concentration of 13C (Abu-Zied et al., 2011c; Lamb et al., 2002; Leng and Marshall, 2004). Therefore, the values of ?18O and ?13C were used as an evaporation index in the Shuaiba Lagoon."
<p style="margin-left: 20px"><strong>interpDirection: </strong>increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>Evaporation
<p style="margin-left: 20px"><strong>variableDetail: </strong>coastal lagoon water
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Low frequency correlation with inferred tidal level
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lagoon water
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology; seasonality; habitat; vital effects
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>I_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>coastal lagoon water
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>chronology; seasonality; habitat; vital effects
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>temperature
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
