---
title: "LS17BAHA01"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 347
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS17BAHA01

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS17BAHA01.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>183
<p style="margin-left: 10px"><strong>pages: </strong>177-187
<p style="margin-left: 10px"><strong>title: </strong>Hydroclimate variability of High Arctic Svalbard during the Holocene inferred from hydrogen isotopes of leaf waxes
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.2016.11.036
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>183
<p style="margin-left: 10px"><strong>pages: </strong>164-176
<p style="margin-left: 10px"><strong>title: </strong>Holocene multi-proxy environmental reconstruction from lake Hakluytvatnet, Amsterdamøya Island, Svalbard (79.5°N)
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.quascirev.2017.02.017
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Lamont Doherty Earth Observatory
<p style="margin-left: 10px"><strong>grant: </strong>Postdoctoral Fellowship
<p style="margin-left: 10px"><strong>country: </strong>USA
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Norwegian Research Council
<p style="margin-left: 10px"><strong>grant: </strong>Arctic Field Grant
<p style="margin-left: 10px"><strong>country: </strong>Norway
</details>
<details style="margin-left: 10px">
<summary>funding3</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Vetlesen Foundation
<p style="margin-left: 10px"><strong>country: </strong>Norway
</details>
<details style="margin-left: 10px">
<summary>funding4</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Norwegian Research Council
<p style="margin-left: 10px"><strong>grant: </strong>210004
<p style="margin-left: 10px"><strong>country: </strong>Norway
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>79.7733
<p style="margin-left: 0px"><strong>longitude: </strong>10.7378
<p style="margin-left: 0px"><strong>elevation: </strong>12
<p style="margin-left: 0px"><strong>siteName: </strong>Haklyutvatnet
<p style="margin-left: 0px"><strong>country: </strong>Svalbard and Jan Mayen
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>Age</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB60381dc8
<p style="margin-left: 10px"><strong>variableName: </strong>Age
<p style="margin-left: 10px"><strong>units: </strong>yrBP
</details>
<details style="margin-left: 10px">
<summary>d2HC25</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBc5c2e8ea
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC25
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>stdevC25</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBba4d631e
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC25
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>d2HC27</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB13dc04eb
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC27
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>stdevC27</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBbdc9dedb
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC27
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>d2HC29</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBd7a384df
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC29
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>stdevC29</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBa1b29ebc
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC29
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>d2HC31</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBf388e826
<p style="margin-left: 10px"><strong>variableName: </strong>d2HC31
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>
<details style="margin-left: 10px">
<summary>stdevC31</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1e989b0d
<p style="margin-left: 10px"><strong>variableName: </strong>stdevC31
<p style="margin-left: 10px"><strong>units: </strong>permil
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Age
```{r}
plotCol(thisTS,ind = 1)
```

### d2HC25
```{r}
plotCol(thisTS,ind = 2)
```

### stdevC25
```{r}
plotCol(thisTS,ind = 3)
```

### d2HC27
```{r}
plotCol(thisTS,ind = 4)
```

### stdevC27
```{r}
plotCol(thisTS,ind = 5)
```

### d2HC29
```{r}
plotCol(thisTS,ind = 6)
```

### stdevC29
```{r}
plotCol(thisTS,ind = 7)
```

### d2HC31
```{r}
plotCol(thisTS,ind = 8)
```

### stdevC31
```{r}
plotCol(thisTS,ind = 9)
```
