---
title: "LS98CUPE"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 356
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS98CUPE

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS98CUPE.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Curtis, Jason H. , Brenner, Mark , Hodell, David A. , Balser, Richard A. , Islebe, Gerald A. , Hooghiemstra, Henry
<p style="margin-left: 10px"><strong>journal: </strong>Journal of Paleolimnology
<p style="margin-left: 10px"><strong>volume: </strong>19
<p style="margin-left: 10px"><strong>pages: </strong>-20
<p style="margin-left: 10px"><strong>pubYear: </strong>1998
<p style="margin-left: 10px"><strong>DOI: </strong>10.1023/A:1007968508262
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>17.0003
<p style="margin-left: 0px"><strong>longitude: </strong>-89.7848
<p style="margin-left: 0px"><strong>elevation: </strong>110
<p style="margin-left: 0px"><strong>siteName: </strong>Lake Peten-Itza
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS98CUPE
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>see above
<p style="margin-left: 20px"><strong>interpDirection: </strong>increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>E/P
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Mean lake water was enriched in 18O by evaporation and was 3.6? greater than mean rainwater.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Calculated 18O values for aragonite and calcite, precipitated in equilibrium with modern lake water (18Owater = + 2.6‰) at a mean annual temperature of 25 C, yield values of 0.92‰ and 0.78‰, respectively (Craig, 1965; Grossman & Ku, 1981). These theoretical values are close to mean values (0.85‰, 0.47‰, and 0.39‰) for recent samples of Cochliopina sp., Pyrgophorus sp., and C. ilosvayi, respectively. This suggests that all three taxa precipitate carbonate near equilibrium with the water in which they live.
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>Chonology; multiple potential controls on d18O
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Interpretation of early Holocene (9000 until 7300 14C yrBP) oxygen isotopic results in terms of E/P is at odds with the strong evidence for moist conditions based on the presence of extensive lowland forest. The discrepancy between early Holocene pollen and 18Oresults in the PetenItza core can be reconciled if lakewater 18O is assumed to have been controlled by both regional climate and the changing surface area/volume ratio of the filling lake
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Calculated 18O values for aragonite and calcite, precipitated in equilibrium with modern lake water (18Owater = + 2.6‰) at a mean annual temperature of 25 C, yield values of 0.92‰ and 0.78‰, respectively (Craig, 1965; Grossman & Ku, 1981). These theoretical values are close to mean values (0.85‰, 0.47‰, and 0.39‰) for recent samples of Cochliopina sp., Pyrgophorus sp., and C. ilosvayi, respectively. This suggests that all three taxa precipitate carbonate near equilibrium with the water in which they live.
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>Chonology; multiple potential controls on d18O
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>area/volume ratio
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Calculated 18O values for aragonite and calcite, precipitated in equilibrium with modern lake water (18Owater = + 2.6‰) at a mean annual temperature of 25 C, yield values of 0.92‰ and 0.78‰, respectively (Craig, 1965; Grossman & Ku, 1981). These theoretical values are close to mean values (0.85‰, 0.47‰, and 0.39‰) for recent samples of Cochliopina sp., Pyrgophorus sp., and C. ilosvayi, respectively. This suggests that all three taxa precipitate carbonate near equilibrium with the water in which they live.
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>Chonology; multiple potential controls on d18O
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Temperature
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
