---
title: "LS99CUVA"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 357
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS99CUVA

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS99CUVA.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Curtis, J.H. , Hodell, D.A. , Brenner, M.
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>9
<p style="margin-left: 10px"><strong>pages: </strong>-10
<p style="margin-left: 10px"><strong>pubYear: </strong>1999
<p style="margin-left: 10px"><strong>title: </strong>Climate change in the Lake Valencia Basin, Venezuela, |12600 yr BP to present
<p style="margin-left: 10px"><strong>DOI: </strong>10.1191/095968399669724431
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>10.1667
<p style="margin-left: 0px"><strong>longitude: </strong>-67.75
<p style="margin-left: 0px"><strong>elevation: </strong>400
<p style="margin-left: 0px"><strong>siteName: </strong>Lake Valencia
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS99CUVAc
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Lake level also important as lake not always closed but Since ,3000 14C yr BP the level of Lake Valencia has been dropping. Lake closed in present day, but last 2k isotoeps realtively fresh suggesting more open system?
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>temperature
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS99CUVAb
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Lake level also important as lake not always closed but Since ,3000 14C yr BP the level of Lake Valencia has been dropping. Lake closed in present day, but last 2k isotoeps realtively fresh suggesting more open system?
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>temperature
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS99CUVAc
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Lake level also important as lake not always closed but Since ,3000 14C yr BP the level of Lake Valencia has been dropping. Lake closed in present day, but last 2k isotoeps realtively fresh suggesting more open system?
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>temperature
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 2)
```

### d18O
```{r}
plotCol(thisTS,ind = 3)
```
