---
title: "MS11CSCS"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 392
thisTS <- TS[which(udsn[i] == dsn)]
```
#MS11CSCS

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](MS11CSCS.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>marine sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=519:1:3800011116671332::::P1_STUDY_ID:11816
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>HVM
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Saenger, C.
<p style="margin-left: 10px"><strong>citeKey: </strong>saenger2011regional
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>26
<p style="margin-left: 10px"><strong>pages: </strong>n/a-n/a
<p style="margin-left: 10px"><strong>pubYear: </strong>2011
<p style="margin-left: 10px"><strong>title: </strong>Regional climate variability in the western subtropical North Atlantic during the past two millennia
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2010PA002038
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>McGregor, Helen V. , Evans, Michael N. , Goosse, Hugues , Leduc, Guillaume , Martrat, Belen , Addison, Jason A. , Mortyn, P. Graham , Oppo, Delia W. , Seidenkrantz, Marit-Solveig , Sicre, Marie-Alexandrine , Phipps, Steven J. , Selvaraj, Kandasamy , Thirumalai, Kaustubh , Filipsson, Helena L. , Ersek, Vasile
<p style="margin-left: 10px"><strong>citeKey: </strong>mcgregor2015robust
<p style="margin-left: 10px"><strong>journal: </strong>Nature Geoscience
<p style="margin-left: 10px"><strong>volume: </strong>8
<p style="margin-left: 10px"><strong>pages: </strong>-6
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Robust global ocean cooling trend for the pre-industrial Common Era
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/ngeo2510
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>Saenger, C.
<p style="margin-left: 10px"><strong>citeKey: </strong>saenger2011o2klrDataCitation
<p style="margin-left: 10px"><strong>title: </strong>O2kLR-CH07-98-MC-2.Saenger.2011
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Ocean Climate Change Institute (WHOI)
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Climate Change Institute (OCCI)
</details>
<details style="margin-left: 10px">
<summary>funding3</summary>
<p style="margin-left: 10px"><strong>agency: </strong>National Science Foundation
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>32.78
<p style="margin-left: 0px"><strong>longitude: </strong>-76.28
<p style="margin-left: 0px"><strong>elevation: </strong>-1895
<p style="margin-left: 0px"><strong>siteName: </strong>Carolina Slope South
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MS11CSCS01b
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>inferred seawater
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Mg/Ca?based SST estimates are often subtracted from d18Oc to yield estimates of seawater d18O (d18Osw) [e.g., Lund and Curry, 2006; Richey et al., 2007].
<p style="margin-left: 20px"><strong>interpDirection: </strong>increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>mean annual
<p style="margin-left: 20px"><strong>variable: </strong>salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Schmidt, 1999
<p style="margin-left: 20px"><strong>coefficient: </strong>NaN
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>NaN
<p style="margin-left: 20px"><strong>fraction: </strong>NaN
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>sea surface water
<p style="margin-left: 20px"><strong>integrationTime: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>NaN
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (always)
<p style="margin-left: 20px"><strong>variable: </strong>Salinity
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MS11CSCS01b
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>inferred seawater
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Mg/Ca?based SST estimates are often subtracted from d18Oc to yield estimates of seawater d18O (d18Osw) [e.g., Lund and Curry, 2006; Richey et al., 2007].
<p style="margin-left: 20px"><strong>interpDirection: </strong>increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>mean annual
<p style="margin-left: 20px"><strong>variable: </strong>salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Schmidt, 1999
<p style="margin-left: 20px"><strong>coefficient: </strong>NaN
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>NaN
<p style="margin-left: 20px"><strong>fraction: </strong>NaN
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>sea surface water
<p style="margin-left: 20px"><strong>integrationTime: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>NaN
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>NaN
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>not applicable (always)
<p style="margin-left: 20px"><strong>variable: </strong>Salinity
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Mg_Ca</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD0fd7fc829
<p style="margin-left: 10px"><strong>variableName: </strong>Mg_Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>description: </strong>Mg/Ca ratio
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa03ec713v
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Mg/Ca inferred temperature
</details>
<details style="margin-left: 10px">
<summary>Mg_Ca_sd</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa03ec713e3
<p style="margin-left: 10px"><strong>variableName: </strong>Mg_Ca_sd
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>description: </strong>standard deviation of Mg/Ca
</details>
<details style="margin-left: 10px">
<summary>d18OUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa03ec713e4
<p style="margin-left: 10px"><strong>variableName: </strong>d18OUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>standard deviation of d18Ocalcite
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 2)
```

### Mg_Ca
```{r}
plotCol(thisTS,ind = 3)
```

### temperature
```{r}
plotCol(thisTS,ind = 4)
```

### Mg_Ca_sd
```{r}
plotCol(thisTS,ind = 5)
```

### d18OUncertainty
```{r}
plotCol(thisTS,ind = 6)
```
