---
title: "Ocn-CariacoBasin.Black.2007"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- sapply(TS,"[[","geo_latitude")[ui]
lon <- sapply(TS,"[[","geo_longitude")[ui]
elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                       elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 521
thisTS <- TS[which(udsn[i] == dsn)]
```
#Ocn-CariacoBasin.Black.2007

Metadata {.sidebar}
-------------------------------------

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>marine sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=519:1:1527603787540765::::P1_STUDY_ID:6397
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>PGM
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Black, David E.;Abahazi, Matthew A.;Thunell, Robert C.;Kaplan, Alexey;Tappa, Eric J.;Peterson, Larry C.
<p style="margin-left: 10px"><strong>citeKey: </strong>black2007an8centurytropicalatlanti
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>22
<p style="margin-left: 10px"><strong>pages: </strong>PA4204
<p style="margin-left: 10px"><strong>pubYear: </strong>2007
<p style="margin-left: 10px"><strong>title: </strong>An 8-century tropical Atlantic SST record from the Cariaco Basin: Baseline variability, twentieth-century warming, and Atlantic hurricane frequency
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2007pa001427
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>McGregor, Helen V.;Evans, Michael N.;Goosse, Hugues;Leduc, Guillaume;Martrat, Belen;Addison, Jason A.;Mortyn, P. Graham;Oppo, Delia W.;Seidenkrantz, Marit-Solveig;Sicre, Marie-Alexandrine;Phipps, Steven J.;Selvaraj, Kandasamy;Thirumalai, Kaustubh;Filipsson, Helena L.;Ersek, Vasile
<p style="margin-left: 10px"><strong>citeKey: </strong>mcgregor2015robustglobaloceancoolingt
<p style="margin-left: 10px"><strong>journal: </strong>Nature Geoscience
<p style="margin-left: 10px"><strong>volume: </strong>8
<p style="margin-left: 10px"><strong>pages: </strong>671-677
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Robust global ocean cooling trend for the pre-industrial Common Era
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/ngeo2510
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>Black, D.E.
<p style="margin-left: 10px"><strong>citeKey: </strong>black2007httpswwwncdcnoaagovpaleostudy6397DataCitation
<p style="margin-left: 10px"><strong>title: </strong>World Data Center for Paleoclimatology
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>US-NSF
<p style="margin-left: 10px"><strong>grant: </strong>ATM-0417909
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>grant: </strong>EAR-0320898
</details>
<details style="margin-left: 10px">
<summary>funding3</summary>
<p style="margin-left: 10px"><strong>grant: </strong>OCE-0326313
</details>
<details style="margin-left: 10px">
<summary>funding4</summary>
<p style="margin-left: 10px"><strong>grant: </strong>OCE-0315234
</details>
<details style="margin-left: 10px">
<summary>funding5</summary>
<p style="margin-left: 10px"><strong>grant: </strong>OCE0317941
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>10.77
<p style="margin-left: 0px"><strong>longitude: </strong>-64.77
<p style="margin-left: 0px"><strong>elevation: </strong>-450
<p style="margin-left: 0px"><strong>siteName: </strong>Cariaco Basin
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe51d17e8
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Mg/Ca calibration to SST
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>3 4 5
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD708fb697
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Mg/Ca calibration to SST
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>3 4 5
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Mg_Ca</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD07a4e733
<p style="margin-left: 10px"><strong>variableName: </strong>Mg_Ca
<p style="margin-left: 10px"><strong>description: </strong>native Mg/Ca ratio from which SST was calculated; values are from foram G. bulloides, are are in units of mmol/mol
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Mg_Ca</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD8248269c
<p style="margin-left: 10px"><strong>variableName: </strong>Mg_Ca
<p style="margin-left: 10px"><strong>description: </strong>native Mg/Ca ratio from which SST was calculated; values are from foram G. bulloides, are are in units of mmol/mol
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
leaflet() %>% 
  addTiles() %>% 
  #fitBounds(min(map.meta$lon),min(map.meta$lat),max(map.meta$lon),max(map.meta$lat)) %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff) %>% 
  addCircleMarkers(map.meta$lon, 
                   map.meta$lat, 
                   color = factpal(map.meta$archiveType),
                   radius = 5, 
                   fill = T,
                   fillOpacity = 1,
                   opacity = 1,
                   popup = paste(str_c('Dataset: <a href="',map.meta$link,'">',map.meta$dataSetName,'</a>'),
                                 str_c("Elevation: ",map.meta$elev),
                                 str_c("Archive Type: ",map.meta$archiveType),
                                 sep = "<br>")) %>%
  addCircleMarkers(map.meta$lon[i], 
                   map.meta$lat[i], 
                   color = "black",
                   radius = 12, 
                   fill = F,
                   opacity = 1) %>%
  addLabelOnlyMarkers(map.meta$lon[i], 
                      map.meta$lat[i], 
                      label = map.meta$dataSetName[i]) %>%
  addLegend("bottomleft",
            colors = unique(factpal(map.meta$archiveType)),
            labels = unique(map.meta$archiveType),
            opacity = 0.8)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature
```{r}
plotCol(thisTS,ind = 1)
```

### temperature
```{r}
plotCol(thisTS,ind = 3)
```

### Mg_Ca
```{r}
plotCol(thisTS,ind = 2)
```

### Mg_Ca
```{r}
plotCol(thisTS,ind = 4)
```
