---
title: "Ocn-WestSpitzberg.Bonnet.2010"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 638
thisTS <- TS[which(udsn[i] == dsn)]
```
#Ocn-WestSpitzberg.Bonnet.2010

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](Ocn-WestSpitzberg.Bonnet.2010.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>marine sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://doi.pangaea.de/10.1594/PANGAEA.780179
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>GL
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Bonnet, Sophie;de Vernal, Anne;Hillaire-Marcel, Claude;Radi, Taoufik;Husum, Katrine
<p style="margin-left: 10px"><strong>citeKey: </strong>bonnet2010variabilityofseasurfacete
<p style="margin-left: 10px"><strong>journal: </strong>Marine Micropaleontology
<p style="margin-left: 10px"><strong>volume: </strong>74
<p style="margin-left: 10px"><strong>pages: </strong>59-74
<p style="margin-left: 10px"><strong>pubYear: </strong>2010
<p style="margin-left: 10px"><strong>title: </strong>Variability of sea-surface temperature and sea-ice cover in the Fram Strait over the last two millennia
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.marmicro.2009.12.001
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>McGregor, Helen V.;Evans, Michael N.;Goosse, Hugues;Leduc, Guillaume;Martrat, Belen;Addison, Jason A.;Mortyn, P. Graham;Oppo, Delia W.;Seidenkrantz, Marit-Solveig;Sicre, Marie-Alexandrine;Phipps, Steven J.;Selvaraj, Kandasamy;Thirumalai, Kaustubh;Filipsson, Helena L.;Ersek, Vasile
<p style="margin-left: 10px"><strong>citeKey: </strong>mcgregor2015robustglobaloceancoolingt
<p style="margin-left: 10px"><strong>journal: </strong>Nature Geoscience
<p style="margin-left: 10px"><strong>volume: </strong>8
<p style="margin-left: 10px"><strong>pages: </strong>671-677
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Robust global ocean cooling trend for the pre-industrial Common Era
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/ngeo2510
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>Bonnet, S.
<p style="margin-left: 10px"><strong>citeKey: </strong>bonnet2012httpdoipangaeade101594pangaea780179DataCitation
<p style="margin-left: 10px"><strong>title: </strong>PANGAEA
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Canadian Foundation for Climate and Atmospheric Sciences (CFCAS)
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Fonds Québécois de la Recherche sur la Nature et les Technologies
(FQRNT)
</details>
<details style="margin-left: 10px">
<summary>funding3</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Natural Sciences and Engineering Research Council of Canada (NSERC)
</details>
<details style="margin-left: 10px">
<summary>funding4</summary>
<p style="margin-left: 10px"><strong>agency: </strong>University of Tromsø
</details>
<details style="margin-left: 10px">
<summary>funding5</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Research Council of Norway
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>78.96
<p style="margin-left: 0px"><strong>longitude: </strong>5.885
<p style="margin-left: 0px"><strong>elevation: </strong>-1497
<p style="margin-left: 0px"><strong>siteName: </strong>West Spitzberg, Fram Strait
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD995c6f3c
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature (mean)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Modern Analogue Technique
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe9d8175e
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature (winter)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Modern Analogue Technique
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Winter
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDea4376b6
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature (summer)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Modern Analogue Technique
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9716f325
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature (winter)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Modern Analogue Technique
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Winter
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9774ea11
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred sea-surface temperature (summer)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Modern Analogue Technique
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD0e67730a
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>A. choane [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD733ab786
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>I. pallidum [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7b4c186e
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>I. paradoxum [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7f64d877
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>I. sphaericum [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD4437dd9f
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>N. labyrinthus [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDfac5c056
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>O. centrocarpum [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2f76c77a
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>O. centrocarpum c.p. [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD06f9eeb7
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>S. elongatus [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd0b10380
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>S. ramosus [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd8240377
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>S. mirabilis-hyper [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5757fb67
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>Spiniferites spp. [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD667b69d2
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>P. dalei [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2ff44dc6
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>I. minutum [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD644f0a81
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>Brigantedinium spp. [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7bf8ef76
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>B. cariacoense [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1d7b7842
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>B. simplex [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1d5a1714
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>S. quanta [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7bdc35f5
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>T. applanatum [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>count</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2b450772
<p style="margin-left: 10px"><strong>variableName: </strong>count
<p style="margin-left: 10px"><strong>description: </strong>Dinofl total [#]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>concentration</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa7464709
<p style="margin-left: 10px"><strong>variableName: </strong>concentration
<p style="margin-left: 10px"><strong>description: </strong>Dinofl cyst conc [#/cm**3]
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature
```{r}
plotCol(thisTS,ind = 1)
```

### temperature
```{r}
plotCol(thisTS,ind = 2)
```

### temperature
```{r}
plotCol(thisTS,ind = 3)
```

### temperature
```{r}
plotCol(thisTS,ind = 4)
```

### temperature
```{r}
plotCol(thisTS,ind = 5)
```

### count
```{r}
plotCol(thisTS,ind = 6)
```

### count
```{r}
plotCol(thisTS,ind = 7)
```

### count
```{r}
plotCol(thisTS,ind = 8)
```

### count
```{r}
plotCol(thisTS,ind = 9)
```

### count
```{r}
plotCol(thisTS,ind = 10)
```

### count
```{r}
plotCol(thisTS,ind = 11)
```

### count
```{r}
plotCol(thisTS,ind = 12)
```

### count
```{r}
plotCol(thisTS,ind = 13)
```

### count
```{r}
plotCol(thisTS,ind = 14)
```

### count
```{r}
plotCol(thisTS,ind = 15)
```

### count
```{r}
plotCol(thisTS,ind = 16)
```

### count
```{r}
plotCol(thisTS,ind = 17)
```

### count
```{r}
plotCol(thisTS,ind = 18)
```

### count
```{r}
plotCol(thisTS,ind = 19)
```

### count
```{r}
plotCol(thisTS,ind = 20)
```

### count
```{r}
plotCol(thisTS,ind = 21)
```

### count
```{r}
plotCol(thisTS,ind = 22)
```

### count
```{r}
plotCol(thisTS,ind = 23)
```

### count
```{r}
plotCol(thisTS,ind = 24)
```

### concentration
```{r}
plotCol(thisTS,ind = 25)
```
