---
title: "Ocn-Palmyra.Cobb.2013"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 599
thisTS <- TS[which(udsn[i] == dsn)]
```
#Ocn-Palmyra.Cobb.2013

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](Ocn-Palmyra.Cobb.2013.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>coral
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/1875
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>KLD, Stevenson, JEG
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb, Kim M.;Charles, Christopher D.;Cheng, Hai;Edwards, R. Lawrence
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2003elniosouthernoscillationa
<p style="margin-left: 10px"><strong>journal: </strong>Nature
<p style="margin-left: 10px"><strong>volume: </strong>424
<p style="margin-left: 10px"><strong>pages: </strong>271-276
<p style="margin-left: 10px"><strong>pubYear: </strong>2003
<p style="margin-left: 10px"><strong>title: </strong>El Niño/Southern Oscillation and tropical Pacific climate during the last millennium
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/nature01779
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb, Kim M.;Charles, Christopher D.;Cheng, Hai;Kastner, Miriam;Edwards, R.Lawrence
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2003uthdatinglivingandyoungfo
<p style="margin-left: 10px"><strong>journal: </strong>Earth and Planetary Science Letters
<p style="margin-left: 10px"><strong>volume: </strong>210
<p style="margin-left: 10px"><strong>pages: </strong>271-276
<p style="margin-left: 10px"><strong>pubYear: </strong>2003
<p style="margin-left: 10px"><strong>title: </strong>U/Th-dating living and young fossil corals from the central tropical Pacific
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/S0012-821X(03)00138-9
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb, K. M.;Westphal, N.;Sayani, H. R.;Watson, J. T.;Di Lorenzo, E.;Cheng, H.;Edwards, R. L.;Charles, C. D.
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2013highlyvariableelninosouth
<p style="margin-left: 10px"><strong>journal: </strong>Science
<p style="margin-left: 10px"><strong>volume: </strong>339
<p style="margin-left: 10px"><strong>pages: </strong>271-276
<p style="margin-left: 10px"><strong>pubYear: </strong>2013
<p style="margin-left: 10px"><strong>title: </strong>Highly variable El Nino-Southern Oscillation throughout the Holocene
<p style="margin-left: 10px"><strong>DOI: </strong>10.1126/science.1228246
</details>
<details style="margin-left: 10px">
<summary>pub4</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb, Kim M.;Charles, Christopher D.;Hunter, David E.
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2001acentraltropicalpacificco
<p style="margin-left: 10px"><strong>journal: </strong>Geophysical Research Letters
<p style="margin-left: 10px"><strong>volume: </strong>28
<p style="margin-left: 10px"><strong>pages: </strong>271-276
<p style="margin-left: 10px"><strong>pubYear: </strong>2001
<p style="margin-left: 10px"><strong>title: </strong>A central tropical Pacific coral demonstrates Pacific, Indian, and Atlantic decadal climate connections
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2001GL012919
</details>
<details style="margin-left: 10px">
<summary>pub5</summary>
<p style="margin-left: 10px"><strong>author: </strong>Tierney, Jessica E.;Abram, Nerilie J.;Anchukaitis, Kevin J.;Evans, Michael N.;Giry, Cyril;Kilbourne, K. Halimeda;Saenger, Casey P.;Wu, Henry C.;Zinke, Jens
<p style="margin-left: 10px"><strong>citeKey: </strong>tierney2015tropicalseasurfacetempera
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>30
<p style="margin-left: 10px"><strong>pages: </strong>226-252
<p style="margin-left: 10px"><strong>pubYear: </strong>2015
<p style="margin-left: 10px"><strong>title: </strong>Tropical sea surface temperatures for the past four centuries reconstructed from coral archives
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/2014PA002717
</details>
<details style="margin-left: 10px">
<summary>pub6</summary>
<p style="margin-left: 10px"><strong>author: </strong>Cobb, K.M.
<p style="margin-left: 10px"><strong>citeKey: </strong>cobb2003httpswwwncdcnoaagovpaleostudy1875DataCitation
<p style="margin-left: 10px"><strong>title: </strong>World Data Center for Paleoclimatology
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>5.87
<p style="margin-left: 0px"><strong>longitude: </strong>-162.13
<p style="margin-left: 0px"><strong>elevation: </strong>-7
<p style="margin-left: 0px"><strong>siteName: </strong>Palmyra
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_139
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>N/A (subannually resolved)
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTBWLHQW85
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>per mil
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>local: </strong>local
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>Isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>mean tropical annual
<p style="margin-left: 20px"><strong>variable: </strong>Temperature
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>local: </strong>local
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>Isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>mean tropical annual
<p style="margin-left: 20px"><strong>variable: </strong>d18Osw
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea surface
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 2)
```
