---
title: "SAm-LagunaAculeo.vonGunten.2009"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 644
thisTS <- TS[which(udsn[i] == dsn)]
```
#SAm-LagunaAculeo.vonGunten.2009

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SAm-LagunaAculeo.vonGunten.2009.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/cdo/f?p=519:1:0::::P1_STUDY_ID:1003957
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>RN, IAM
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>von Gunten, L.;Grosjean, M.;Rein, B.;Urrutia, R.;Appleby, P.
<p style="margin-left: 10px"><strong>citeKey: </strong>von2009aquantitativehighresoluti
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>19
<p style="margin-left: 10px"><strong>pages: </strong>873-881
<p style="margin-left: 10px"><strong>pubYear: </strong>2009
<p style="margin-left: 10px"><strong>title: </strong>A quantitative high-resolution summer temperature reconstruction based on sedimentary pigments from Laguna Aculeo, central Chile, back to AD 850
<p style="margin-left: 10px"><strong>DOI: </strong>10.1177/0959683609336573
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>von Gunten, L.
<p style="margin-left: 10px"><strong>citeKey: </strong>von2013httpswwwncdcnoaagovpaleostudy1003957DataCitation
<p style="margin-left: 10px"><strong>title: </strong>World Data Center for Paleoclimatology
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-33.85
<p style="margin-left: 0px"><strong>longitude: </strong>-70.92
<p style="margin-left: 0px"><strong>elevation: </strong>355
<p style="margin-left: 0px"><strong>siteName: </strong>Laguna Aculeo
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>SAm
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_024
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>inferred temperature
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significant correlation to CRU_TS 2.1
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>-12 1 2
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_0241
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>smooth: 5-year triangular filters were applied to account for resampling, dating uncertainties and possible bioturbation.
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significant correlation to CRU_TS 2.1
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_0242
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>smooth: 3-year triangular filters were applied to account for resampling, dating uncertainties and possible bioturbation. Scaling
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significant correlation to CRU_TS 2.1
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_0243
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>smooth: 3-year triangular filters were applied to account for resampling, dating uncertainties and possible bioturbation. Regression
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significant correlation to CRU_TS 2.1
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>-12 1 2
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>R660_670</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_0244
<p style="margin-left: 10px"><strong>variableName: </strong>R660_670
<p style="margin-left: 10px"><strong>units: </strong>NA
<p style="margin-left: 10px"><strong>description: </strong>Smooth: 3-year triangular filter. Highly correlated to Relative Absorption band depth RABD660-670nm (R:0.92;P:2.2*10-16). RABD660-670 represents the total chlorin concentration
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature
```{r}
plotCol(thisTS,ind = 1)
```

### temperature
```{r}
plotCol(thisTS,ind = 2)
```

### temperature
```{r}
plotCol(thisTS,ind = 3)
```

### temperature
```{r}
plotCol(thisTS,ind = 4)
```

### R660_670
```{r}
plotCol(thisTS,ind = 5)
```
