---
title: "SAm-CentralAndes9.Mundo.2014"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 643
thisTS <- TS[which(udsn[i] == dsn)]
```
#SAm-CentralAndes9.Mundo.2014

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SAm-CentralAndes9.Mundo.2014.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>tree
<p style="margin-left: 0px"><strong>originalDataURL: </strong>http://www.ncdc.noaa.gov/paleo/study/1003953
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>RN, IAM
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Neukom, Raphael;Gergis, Joëlle;Karoly, David J.;Wanner, Heinz;Curran, Mark;Elbert, Julie;González-Rouco, Fidel;Linsley, Braddock K.;Moy, Andrew D.;Mundo, Ignacio;Raible, Christoph C.;Steig, Eric J.;van Ommen, Tas;Vance, Tessa;Villalba, Ricardo;Zinke, Jens;Frank, David
<p style="margin-left: 10px"><strong>citeKey: </strong>neukom2014interhemispherictemperatu
<p style="margin-left: 10px"><strong>journal: </strong>Nature Climate Change
<p style="margin-left: 10px"><strong>volume: </strong>4
<p style="margin-left: 10px"><strong>pages: </strong>362-367
<p style="margin-left: 10px"><strong>pubYear: </strong>2014
<p style="margin-left: 10px"><strong>title: </strong>Inter-hemispheric temperature variability over the past millennium
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/NCLIMATE2174
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Mundo, I
<p style="margin-left: 10px"><strong>citeKey: </strong>mundo2013httpswwwncdcnoaagovpaleostudy1003953DataCitation
<p style="margin-left: 10px"><strong>title: </strong>World Data Center for Paleoclimatology
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-39.33
<p style="margin-left: 0px"><strong>longitude: </strong>-71.25
<p style="margin-left: 0px"><strong>elevation: </strong>1100
<p style="margin-left: 0px"><strong>siteName: </strong>Central Andes composite 9
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>SAm
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>trsgi</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_020
<p style="margin-left: 10px"><strong>variableName: </strong>trsgi
<p style="margin-left: 10px"><strong>units: </strong>NA
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significantly positively correlated to southern SAm mean temperatures in DJF prior to the growing season (PAGES 2013) and negatively to local grid cell temperature in the May-Apr year prior to the growing season (Neukom et al. 2014)
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>-5 -6 -7 -8 -9 -10 -11 -12 1 2 3 4
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>trsgi</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_016
<p style="margin-left: 10px"><strong>variableName: </strong>trsgi
<p style="margin-left: 10px"><strong>units: </strong>NA
<p style="margin-left: 10px"><strong>description: </strong>tree ring width
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significantly correlated to local grid cell temperature in the May-Apr year prior to the growing season (Neukom et al. 2014) and to southern SAm mean temperatures in DJF prior to teh growing season (PAGES 2013)
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>-5 -6 -7 -8 -9 -10 -11 -12 1 2 3 4
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>trsgi</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_017
<p style="margin-left: 10px"><strong>variableName: </strong>trsgi
<p style="margin-left: 10px"><strong>units: </strong>NA
<p style="margin-left: 10px"><strong>description: </strong>tree ring width
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significantly correlated to local grid cell temperature in the May-Apr year prior to the growing season (Neukom et al. 2014) and to southern SAm mean temperatures in DJF prior to teh growing season (PAGES 2013)
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>-5 -6 -7 -8 -9 -10 -11 -12 1 2 3 4
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>trsgi</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_018
<p style="margin-left: 10px"><strong>variableName: </strong>trsgi
<p style="margin-left: 10px"><strong>units: </strong>NA
<p style="margin-left: 10px"><strong>description: </strong>tree ring width
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significantly correlated to local grid cell temperature in the May-Apr year prior to the growing season (Neukom et al. 2014) and to southern SAm mean temperatures in DJF prior to teh growing season (PAGES 2013)
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>-5 -6 -7 -8 -9 -10 -11 -12 1 2 3 4
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>trsgi</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SAm_019
<p style="margin-left: 10px"><strong>variableName: </strong>trsgi
<p style="margin-left: 10px"><strong>units: </strong>NA
<p style="margin-left: 10px"><strong>description: </strong>tree ring width
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Significantly correlated to local grid cell temperature in the May-Apr year prior to the growing season (Neukom et al. 2014) and to southern SAm mean temperatures in DJF prior to teh growing season (PAGES 2013)
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>-5 -6 -7 -8 -9 -10 -11 -12 1 2 3 4
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### trsgi
```{r}
plotCol(thisTS,ind = 1)
```

### trsgi
```{r}
plotCol(thisTS,ind = 2)
```

### trsgi
```{r}
plotCol(thisTS,ind = 3)
```

### trsgi
```{r}
plotCol(thisTS,ind = 4)
```

### trsgi
```{r}
plotCol(thisTS,ind = 5)
```
