---
title: "SH18ME"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 411
thisTS <- TS[which(udsn[i] == dsn)]
```
#SH18ME

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SH18ME.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>mollusks shells
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>Limnology and Oceanography
<p style="margin-left: 10px"><strong>volume: </strong>61
<p style="margin-left: 10px"><strong>pages: </strong>748-764
<p style="margin-left: 10px"><strong>title: </strong>Linking large-scale climate variability withArctica islandicashell growth and geochemistry in northern Norway
<p style="margin-left: 10px"><strong>DOI: </strong>10.1002/lno.10252
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>NSF
<p style="margin-left: 10px"><strong>grant: </strong>1417636
</details>
<details style="margin-left: 10px">
<summary>funding2</summary>
<p style="margin-left: 10px"><strong>agency: </strong>NSF
<p style="margin-left: 10px"><strong>grant: </strong>1417766
</details>
<details style="margin-left: 10px">
<summary>funding3</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Research Council of Norway
<p style="margin-left: 10px"><strong>grant: </strong>227046
<p style="margin-left: 10px"><strong>country: </strong>Norway
</details>
<details style="margin-left: 10px">
<summary>funding4</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Geological Society of America
<p style="margin-left: 10px"><strong>grant: </strong>Graduate Research Grant
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>71.0622
<p style="margin-left: 0px"><strong>longitude: </strong>24.0983
<p style="margin-left: 0px"><strong>elevation: </strong>-6
<p style="margin-left: 0px"><strong>siteName: </strong>Ingøya
<p style="margin-left: 0px"><strong>country: </strong>Norway
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB8d8f0a7b
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>per mil
<p style="margin-left: 10px"><strong>description: </strong>d18O, Arctica islandica, per mil VPDB
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The unsmoothed δ18Oshell time series exhibits a relatively strong, negative relationship with the annual AMO index (r = −0.55; adjusted p < 0.001; January–December) over 113 yr (1900–2012).
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>April/June to April/March
<p style="margin-left: 20px"><strong>variable: </strong>AMO
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The annual δ18Oshell time series each show relatively strong, negative correlations with a broad swath of North Atlantic SSTs during the satellite era
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>April/June to April/March
<p style="margin-left: 20px"><strong>variable: </strong>T_water
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>yr</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBc39fe5b2
<p style="margin-left: 10px"><strong>variableName: </strong>yr
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>calendar years AD, cross-dated layer counting
</details>
<details style="margin-left: 10px">
<summary>MShellCrn</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBf4409c5a
<p style="margin-left: 10px"><strong>variableName: </strong>MShellCrn
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>Master Shell Growth Chronology,  Arctica islandica, normalized, standard chronology
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 3)
```

### yr
```{r}
plotCol(thisTS,ind = 1)
```

### MShellCrn
```{r}
plotCol(thisTS,ind = 2)
```
