---
title: "SP07DEUS"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 422
thisTS <- TS[which(udsn[i] == dsn)]
```
#SP07DEUS

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SP07DEUS.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>speleothem
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Denniston, RF
<p style="margin-left: 10px"><strong>pubYear: </strong>2007
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.yqres.2007.04.001
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>38.9
<p style="margin-left: 0px"><strong>longitude: </strong>-92.3
<p style="margin-left: 0px"><strong>elevation: </strong>250
<p style="margin-left: 0px"><strong>siteName: </strong>Devils Icebox Cave, Missouri
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d13C</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP07DEUS01A_d13C
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The influence of vegetation changes and changes in the water residence time on d13C of DIC. Drier conditions cause an increase of C4 plants in the vegetation and longer residence times of water in the bedrock (increasing the contribution of bedrock carbonate to DIC). Either one would cause an increase of d13C in the speleothem. Temperature changes may have a similar effect on d13C as would changes  in the rainfall amount but would also affect d18O. Since d18O values are stable a temperature effect therefore can be eliminated.
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
<p style="margin-left: 20px"><strong>variableDetail: </strong>more poritive d13C values reflect less rainfall amount
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Increase of d13C may generally be associated with increase of the proportion of C4 plants in the vegetation or increase of the contribution of bedrock carbonate to the DIC - both are more likely in drier conditions. Stable d18O values suggest that changes in temperature were minor.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>repetition test comparing d18O and d13C of two speleothems shows similar trends
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>d13C of DIC
<p style="margin-left: 20px"><strong>integrationTime: </strong>5
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Change in vegetation composition C3-C4 plants
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d13C</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP07DEUS02A_d13C
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The influence of vegetation changes and changes in the water residence time on d13C of DIC. Drier conditions cause an increase of C4 plants in the vegetation and longer residence times of water in the bedrock (increasing the contribution of bedrock carbonate to DIC). Either one would cause an increase of d13C in the speleothem. Temperature changes may have a similar effect on d13C as would changes  in the rainfall amount but would also affect d18O. Since d18O values are stable a temperature effect therefore can be eliminated.
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
<p style="margin-left: 20px"><strong>variableDetail: </strong>more poritive d13C values reflect less rainfall amount
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Increase of d13C may generally be associated with increase of the proportion of C4 plants in the vegetation or increase of the contribution of bedrock carbonate to the DIC - both are more likely in drier conditions. Stable d18O values suggest that changes in temperature were minor.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>repetition test comparing d18O and d13C of two speleothems shows similar trends
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>d13C of DIC
<p style="margin-left: 20px"><strong>integrationTime: </strong>5
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>Change in vegetation composition C3-C4 plants
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP07DEUS01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>d18O values are comparatively stable which is interpreted to reflect stable temperature in the region.
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Increase of d13C may generally be associated with increase of the proportion of C4 plants in the vegetation or increase of the contribution of bedrock carbonate to the DIC - both are more likely in drier conditions. Stable d18O values suggest that changes in temperature were minor.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>repetition test comparing d18O and d13C of two speleothems shows similar trends
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>5
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>precipitation amount
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP07DEUS02A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>d18O values are comparatively stable which is interpreted to reflect stable temperature in the region.
<p style="margin-left: 20px"><strong>scope: </strong>climate
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Increase of d13C may generally be associated with increase of the proportion of C4 plants in the vegetation or increase of the contribution of bedrock carbonate to the DIC - both are more likely in drier conditions. Stable d18O values suggest that changes in temperature were minor.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>repetition test comparing d18O and d13C of two speleothems shows similar trends
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>5
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>precipitation amount
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d13C
```{r}
plotCol(thisTS,ind = 2)
```

### d13C
```{r}
plotCol(thisTS,ind = 4)
```

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 3)
```
