---
title: "SP12KEBZ"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 446
thisTS <- TS[which(udsn[i] == dsn)]
```
#SP12KEBZ

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SP12KEBZ.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>speleothem
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Kennett, DJ
<p style="margin-left: 10px"><strong>pubYear: </strong>2012
<p style="margin-left: 10px"><strong>DOI: </strong>10.1126/science.1226299
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>16.2086
<p style="margin-left: 0px"><strong>longitude: </strong>-89.0735
<p style="margin-left: 0px"><strong>elevation: </strong>NA
<p style="margin-left: 0px"><strong>siteName: </strong>Yok Balum Cave, Belize
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP12KEBZ01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>1 year record of weekly monitoring of rainfall d18O near the cave
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
<p style="margin-left: 20px"><strong>variableDetail: </strong>more negative d18O reflects higher rainfall amounts
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>monitoring of present-day speleothem; Hendy tests
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>0.01 - 3.68
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The age model was computed in MATLAB® based on a cubic interpolation between the 230Th ages, its distance from the stalagmite top, and the corresponding dating errors. Multiple age models are produced to account for the analytical uncertainties and the errors in the location of each drill hole (assumed to be <0.2 mm). Therefore, multiple iterations of the age model were calculated assuming a normally distributed deviation from the 230Th age and the standard deviation given by the error range (Monte Carlo simulation). Iterations with reversals were dropped and an ensemble of 100 age models was created (i.e., all reversals could be removed within the error margins). In this model the median age in the distribution was used for each point.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d13C</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP12KEBZ01A_d13C
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>monitoring of present-day speleothem; Hendy tests
<p style="margin-left: 20px"><strong>integrationTime: </strong>0.01 - 3.68
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>The age model was computed in MATLAB® based on a cubic interpolation between the 230Th ages, its distance from the stalagmite top, and the corresponding dating errors. Multiple age models are produced to account for the analytical uncertainties and the errors in the location of each drill hole (assumed to be <0.2 mm). Therefore, multiple iterations of the age model were calculated assuming a normally distributed deviation from the 230Th age and the standard deviation given by the error range (Monte Carlo simulation). Iterations with reversals were dropped and an ensemble of 100 age models was created (i.e., all reversals could be removed within the error margins). In this model the median age in the distribution was used for each point.
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d13C
```{r}
plotCol(thisTS,ind = 2)
```
