---
title: "SP13AYID"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 450
thisTS <- TS[which(udsn[i] == dsn)]
```
#SP13AYID

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SP13AYID.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>speleothem
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Ayliffe, LK
<p style="margin-left: 10px"><strong>pubYear: </strong>2013
<p style="margin-left: 10px"><strong>DOI: </strong>10.1038/ncomms3908
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Ayliffe, L.K.
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>Ayliffe, L.K.
</details>
<details style="margin-left: 10px">
<summary>pub4</summary>
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-8.533
<p style="margin-left: 0px"><strong>longitude: </strong>120.433
<p style="margin-left: 0px"><strong>elevation: </strong>550
<p style="margin-left: 0px"><strong>siteName: </strong>Liang Luar Cave, Indonesia
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP13AYID01_compo
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Analysis of modern rainfall d18O at Liang Luar shows that summer monsoon rainwater is depleted in 18O by 6?7% compared with rain water for the remainder of the year.This large isotopic contrast means that changes in the amount of summer rainfall, or the fraction of the year dominated by the northwest monsoon, produce a significant shift in the d18O of Flores rainfall. Today, the position of the ITCZ governs the balance between summer monsoon rain and winter trade wind induced orographic rainfall, and hence d18O at Flores. Water isotope-enabled climate models show that similar relationships between ITCZ positioning and rainfall d18O also prevailed at Flores during the last glacial. Millennial-scale changes in warm pool temperatures (and surface air temperature) were small over the last 23 kyr, thus changes in the d18O of rainfall, rather than temperature, dominate the record
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>mostly summer
<p style="margin-left: 20px"><strong>variable: </strong>Australian?Indonesian monsoon rainfall
<p style="margin-left: 20px"><strong>variableDetail: </strong>amount of rainfall
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Poor correlation among d13C and d18O and good overlapping of several stalagmites
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>80
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP13AYID01A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Analysis of modern rainfall d18O at Liang Luar shows that summer monsoon rainwater is depleted in 18O by 6?7% compared with rain water for the remainder of the year.This large isotopic contrast means that changes in the amount of summer rainfall, or the fraction of the year dominated by the northwest monsoon, produce a significant shift in the d18O of Flores rainfall. Today, the position of the ITCZ governs the balance between summer monsoon rain and winter trade wind induced orographic rainfall, and hence d18O at Flores. Water isotope-enabled climate models show that similar relationships between ITCZ positioning and rainfall d18O also prevailed at Flores during the last glacial. Millennial-scale changes in warm pool temperatures (and surface air temperature) were small over the last 23 kyr, thus changes in the d18O of rainfall, rather than temperature, dominate the record
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>mostly summer
<p style="margin-left: 20px"><strong>variable: </strong>Australian?Indonesian monsoon rainfall
<p style="margin-left: 20px"><strong>variableDetail: </strong>amount of rainfall
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Poor correlation among d13C and d18O and good overlapping of several stalagmites
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>80
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP13AYID02A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Analysis of modern rainfall d18O at Liang Luar shows that summer monsoon rainwater is depleted in 18O by 6?7% compared with rain water for the remainder of the year.This large isotopic contrast means that changes in the amount of summer rainfall, or the fraction of the year dominated by the northwest monsoon, produce a significant shift in the d18O of Flores rainfall. Today, the position of the ITCZ governs the balance between summer monsoon rain and winter trade wind induced orographic rainfall, and hence d18O at Flores. Water isotope-enabled climate models show that similar relationships between ITCZ positioning and rainfall d18O also prevailed at Flores during the last glacial. Millennial-scale changes in warm pool temperatures (and surface air temperature) were small over the last 23 kyr, thus changes in the d18O of rainfall, rather than temperature, dominate the record
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>mostly summer
<p style="margin-left: 20px"><strong>variable: </strong>Australian?Indonesian monsoon rainfall
<p style="margin-left: 20px"><strong>variableDetail: </strong>amount of rainfall
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Poor correlation among d13C and d18O and good overlapping of several stalagmites
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>80
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP13AYID03A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Analysis of modern rainfall d18O at Liang Luar shows that summer monsoon rainwater is depleted in 18O by 6?7% compared with rain water for the remainder of the year.This large isotopic contrast means that changes in the amount of summer rainfall, or the fraction of the year dominated by the northwest monsoon, produce a significant shift in the d18O of Flores rainfall. Today, the position of the ITCZ governs the balance between summer monsoon rain and winter trade wind induced orographic rainfall, and hence d18O at Flores. Water isotope-enabled climate models show that similar relationships between ITCZ positioning and rainfall d18O also prevailed at Flores during the last glacial. Millennial-scale changes in warm pool temperatures (and surface air temperature) were small over the last 23 kyr, thus changes in the d18O of rainfall, rather than temperature, dominate the record
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>mostly summer
<p style="margin-left: 20px"><strong>variable: </strong>Australian?Indonesian monsoon rainfall
<p style="margin-left: 20px"><strong>variableDetail: </strong>amount of rainfall
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Poor correlation among d13C and d18O and good overlapping of several stalagmites
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>80
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>SP13AYID04A
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Analysis of modern rainfall d18O at Liang Luar shows that summer monsoon rainwater is depleted in 18O by 6?7% compared with rain water for the remainder of the year.This large isotopic contrast means that changes in the amount of summer rainfall, or the fraction of the year dominated by the northwest monsoon, produce a significant shift in the d18O of Flores rainfall. Today, the position of the ITCZ governs the balance between summer monsoon rain and winter trade wind induced orographic rainfall, and hence d18O at Flores. Water isotope-enabled climate models show that similar relationships between ITCZ positioning and rainfall d18O also prevailed at Flores during the last glacial. Millennial-scale changes in warm pool temperatures (and surface air temperature) were small over the last 23 kyr, thus changes in the d18O of rainfall, rather than temperature, dominate the record
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>mostly summer
<p style="margin-left: 20px"><strong>variable: </strong>Australian?Indonesian monsoon rainfall
<p style="margin-left: 20px"><strong>variableDetail: </strong>amount of rainfall
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>Poor correlation among d13C and d18O and good overlapping of several stalagmites
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>groundwater d18O
<p style="margin-left: 20px"><strong>integrationTime: </strong>80
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>age model
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>rainfall amount
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18OUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2c
<p style="margin-left: 10px"><strong>variableName: </strong>d18OUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>count_analyses_B3</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2f
<p style="margin-left: 10px"><strong>variableName: </strong>count_analyses_B3
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>d18OUncertainty</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2d
<p style="margin-left: 10px"><strong>variableName: </strong>d18OUncertainty
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>count_analyses_C2</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2g
<p style="margin-left: 10px"><strong>variableName: </strong>count_analyses_C2
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>count_analyses_C3</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2h
<p style="margin-left: 10px"><strong>variableName: </strong>count_analyses_C3
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>count_analyses_C5</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2i
<p style="margin-left: 10px"><strong>variableName: </strong>count_analyses_C5
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>notes_C5</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2k
<p style="margin-left: 10px"><strong>variableName: </strong>notes_C5
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2e
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>count_analyses_C6</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2j
<p style="margin-left: 10px"><strong>variableName: </strong>count_analyses_C6
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d948e2e
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```

### d18O
```{r}
plotCol(thisTS,ind = 3)
```

### d18O
```{r}
plotCol(thisTS,ind = 6)
```

### d18O
```{r}
plotCol(thisTS,ind = 8)
```

### d18O
```{r}
plotCol(thisTS,ind = 10)
```

### d18OUncertainty
```{r}
plotCol(thisTS,ind = 2)
```

### count_analyses_B3
```{r}
plotCol(thisTS,ind = 4)
```

### d18OUncertainty
```{r}
plotCol(thisTS,ind = 5)
```

### count_analyses_C2
```{r}
plotCol(thisTS,ind = 7)
```

### count_analyses_C3
```{r}
plotCol(thisTS,ind = 9)
```

### count_analyses_C5
```{r}
plotCol(thisTS,ind = 11)
```

### notes_C5
```{r}
plotCol(thisTS,ind = 12)
```

### d18O
```{r}
plotCol(thisTS,ind = 13)
```

### count_analyses_C6
```{r}
plotCol(thisTS,ind = 14)
```

### d18O
```{r}
plotCol(thisTS,ind = 15)
```
