---
title: "TR11SAHU00"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../functions.R")

#prepare LiPD data..
# D <- readLipd("~/Dropbox/LiPD/PAGES2k/Temp_v2_1_0/")
# TS <- extractTs(D)
load("../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

good <- which(!(varNames %in% c("year","depth","age")))
TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link

#set index number

i = 477
thisTS <- TS[which(udsn[i] == dsn)]
```
#TR11SAHU00

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](TR11SAHU00.lpd)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>wood
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>22
<p style="margin-left: 10px"><strong>pages: </strong>809-817
<p style="margin-left: 10px"><strong>title: </strong>Increasing aridity over the past 223 years in the Nepal Himalaya inferred from a tree-ring δ18O chronology
<p style="margin-left: 10px"><strong>DOI: </strong>10.1177/0959683611430338
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>29.85
<p style="margin-left: 0px"><strong>longitude: </strong>81.93
<p style="margin-left: 0px"><strong>elevation: </strong>3848
<p style="margin-left: 0px"><strong>siteName: </strong>Humla
<p style="margin-left: 0px"><strong>country: </strong>Nepal
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>d18O</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB3638db18
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>d18O of tree cellulose of Abies spetabillis
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Instrumental calibration. A negative correlation between δ18O of precipitation and the amount of precipitation is observed in tropical regions including the Himalaya, which is termed as the ‘amount effect’ (Araguás-Araguás et al., 1998; Dansgaard, 1964; Yadava and Ramesh, 2005).
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.36
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>precipitation
<p style="margin-left: 20px"><strong>variableDetail: </strong>precipitation
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Our interpretation of the temperature signal in the δ18O chronology is that higher temperatures stimulate evaporation of soil water, resulting in a preferential loss of lighter isotopes in soil water, which in turn is taken up by trees.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>fraction: </strong>0.1225
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>temperature
<p style="margin-left: 20px"><strong>variableDetail: </strong>surface temperature
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>More specifically, lower atmospheric humidity causes higher vapor pressure gradient between leaf interstitial space and the atmosphere, resulting in a preferential loss of lighter isotopes and consequent enrichment in δ18O of leaf water.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.3844
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>relative humdity
<p style="margin-left: 20px"><strong>variableDetail: </strong>surface relative humidity
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Since all the responses of tree-ring δ18O to the climatic factors (precipitation, relative humidity, and temperature) are related to dry–wet conditions, the PDSI is considered to be the most useful single variable to explain the variance of our δ18O chronology.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.5329
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>soil moisture stress
</details>
<details style="margin-left: 20px">
<summary>5</summary>
<p style="margin-left: 20px"><strong>basis: </strong>d18O of the leaf water takes part in synthesis of photosynthates
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>leaf water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1 year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (June to September)
<p style="margin-left: 20px"><strong>variable: </strong>leaf water isotope
<p style="margin-left: 20px"><strong>variableDetail: </strong>d18O of the leaf water
</details>
</details>
</details>

Row
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O
```{r}
plotCol(thisTS,ind = 1)
```
