---
title: "161_976"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 2
thisTS <- TS[which(udsn[i] == dsn)]
```
#161_976

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](161_976.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/161_976.lpd)
            

[Download paleoData only (csv)](161_976.csv)
            

[Download chronData only (csv)](161_976-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>c("https://doi.pangaea.de/10.1594/PANGAEA.787827", "https://doi.pangaea.de/10.1594/PANGAEA.847255", "https://doi.pangaea.de/10.1594/PANGAEA.847256")
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Martrat, Belen"), list(name = "Jimenez-Amat, Patricia"), list(name = "Zahn, Rainer"), list(name = "Grimalt, Joan O."))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>99
<p style="margin-left: 10px"><strong>title: </strong>Similarities and dissimilarities between the last two deglaciations and interglaciations in the North Atlantic region
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Jimenez-Amat, Patricia"), list(name = "Zahn, Rainer"))
<p style="margin-left: 10px"><strong>journal: </strong>Paleoceanography
<p style="margin-left: 10px"><strong>volume: </strong>30
<p style="margin-left: 10px"><strong>title: </strong>Offset timing of climate oscillations during the last two glacial-interglacial transitions connected with large-scale freshwater perturbation
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>36.2054
<p style="margin-left: 0px"><strong>longitude: </strong>-4.3127
<p style="margin-left: 0px"><strong>elevation: </strong>-1108
<p style="margin-left: 0px"><strong>siteName: </strong>161_976
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RF6p6FnD37J
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RpWJmk8tdl2
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R56JsH0b7h7
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>LOOKUP
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>C37.concentration (g) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RFPqL4xjYcE
<p style="margin-left: 10px"><strong>variableName: </strong>C37.concentration
<p style="margin-left: 10px"><strong>units: </strong>g
<p style="margin-left: 10px"><strong>description: </strong>K37_ng_g
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rn2tbdX4mhO
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RSAKUtFTyUX
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RscxCqgnTot
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_1_12_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>LOOKUP
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>label (missing) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RARmrjSNhwA
<p style="margin-left: 10px"><strong>variableName: </strong>label
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>Label
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RyCQUjotSaO
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G_bulloides_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.MgCa (mmol_mol) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rl3oDldpRFu
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.MgCa
<p style="margin-left: 10px"><strong>units: </strong>mmol_mol
<p style="margin-left: 10px"><strong>description: </strong>G_bulloides_Mg_Ca_mmol_mol
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R9lIvpEn63a
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>dateType ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLvP3x4Pj5b
<p style="margin-left: 10px"><strong>variableName: </strong>dateType
</details>
<details style="margin-left: 10px">
<summary>measurementMaterial ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>ReqOhigOrL8
<p style="margin-left: 10px"><strong>variableName: </strong>measurementMaterial
</details>
<details style="margin-left: 10px">
<summary>sensorSpecies ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1tHsiWECjs
<p style="margin-left: 10px"><strong>variableName: </strong>sensorSpecies
</details>
<details style="margin-left: 10px">
<summary>age14C (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RhE1Ybw9qy0
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CUncertainty (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLVBl5c9nyv
<p style="margin-left: 10px"><strong>variableName: </strong>age14CUncertainty
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CHi (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RRqhDQIg0bh
<p style="margin-left: 10px"><strong>variableName: </strong>age14CHi
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CLow (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R9hbxFu4ybs
<p style="margin-left: 10px"><strong>variableName: </strong>age14CLow
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>reservoirAge (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RiexzyMlqYV
<p style="margin-left: 10px"><strong>variableName: </strong>reservoirAge
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>notes ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1OLJLpKafz
<p style="margin-left: 10px"><strong>variableName: </strong>notes
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 3)
```

### C37.concentration (g)
```{r}
plotCol(thisTS,ind = 4)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 10)
```

### label (missing)
```{r}
plotCol(thisTS,ind = 6)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 8)
```

### planktic.MgCa (mmol_mol)
```{r}
plotCol(thisTS,ind = 9)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### dateType ()
```{r}
plotCol(chronTS,ind = 1)
```

### measurementMaterial ()
```{r}
plotCol(chronTS,ind = 3)
```

### sensorSpecies ()
```{r}
plotCol(chronTS,ind = 4)
```

### age14C (kyr)
```{r}
plotCol(chronTS,ind = 5)
```

### age14CUncertainty (kyr)
```{r}
plotCol(chronTS,ind = 6)
```

### age14CHi (kyr)
```{r}
plotCol(chronTS,ind = 7)
```

### age14CLow (kyr)
```{r}
plotCol(chronTS,ind = 8)
```

### reservoirAge (kyr)
```{r}
plotCol(chronTS,ind = 9)
```

### notes ()
```{r}
plotCol(chronTS,ind = 10)
```
