---
title: "dravladalsvatn.Bakke.2005"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 171
thisTS <- TS[which(udsn[i] == dsn)]
```
#dravladalsvatn.Bakke.2005

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](dravladalsvatn.Bakke.2005.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/dravladalsvatn.Bakke.2005.lpd)
            

[Download paleoData only (csv)](dravladalsvatn.Bakke.2005.csv)
            

[Download chronData only (csv)](dravladalsvatn.Bakke.2005-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>LakeSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo-search/study/15444
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Bakke, Jostein"), list(name = "Lie, oeyvind"), list(name = "Nesje, Atle"), list(name = "Dahl, Svein Olaf"), list(name = "Paasche, oeyvind"))
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>15
<p style="margin-left: 10px"><strong>title: </strong>Utilizing physical sediment variability in glacier-fed lakes for continuous                 glacier reconstructions during the Holocene, northern Folgefonna, western Norway
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>60.0333
<p style="margin-left: 0px"><strong>longitude: </strong>6.0667
<p style="margin-left: 0px"><strong>siteName: </strong>dravladalsvatn
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTFW6ZBU1I
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>ELA (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTWWYWR3J1
<p style="margin-left: 10px"><strong>variableName: </strong>ELA
<p style="margin-left: 10px"><strong>units: </strong>m
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>ANN
<p style="margin-left: 20px"><strong>variable: </strong>ELA
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>age (bp) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTCTKE9398
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT95ZER5BJ
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>depth_top (mm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTUFTWXV3Q
<p style="margin-left: 10px"><strong>variableName: </strong>depth_top
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>depth_bot (mm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTVJ74CPMJ
<p style="margin-left: 10px"><strong>variableName: </strong>depth_bot
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>age14C (bp) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTE4AUNEC7
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>age_error (1s) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTHETODLIT
<p style="margin-left: 10px"><strong>variableName: </strong>age_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>thickness (mm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT66M60K1S
<p style="margin-left: 10px"><strong>variableName: </strong>thickness
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>age (bp) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT431B0REV
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTRF3GH0AK
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>depth_top (mm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT43EAJKHR
<p style="margin-left: 10px"><strong>variableName: </strong>depth_top
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>depth_bot (mm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTL1D3R7EV
<p style="margin-left: 10px"><strong>variableName: </strong>depth_bot
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>age14C (bp) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTRN6SW5MA
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>bp
</details>
<details style="margin-left: 10px">
<summary>age_error (1s) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTU4QD7H3I
<p style="margin-left: 10px"><strong>variableName: </strong>age_error
<p style="margin-left: 10px"><strong>units: </strong>1s
</details>
<details style="margin-left: 10px">
<summary>thickness (mm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTXU74MY2L
<p style="margin-left: 10px"><strong>variableName: </strong>thickness
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>age_type () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTAD0GNLN7
<p style="margin-left: 10px"><strong>variableName: </strong>age_type
</details>
<details style="margin-left: 10px">
<summary>core_name () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTXXXAX126
<p style="margin-left: 10px"><strong>variableName: </strong>core_name
</details>
<details style="margin-left: 10px">
<summary>lab_id () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTQESGC8S9
<p style="margin-left: 10px"><strong>variableName: </strong>lab_id
</details>
<details style="margin-left: 10px">
<summary>material_dated () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYT4XT1S4IG
<p style="margin-left: 10px"><strong>variableName: </strong>material_dated
</details>
<details style="margin-left: 10px">
<summary>rejected_dates () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>PYTTZKKOP75
<p style="margin-left: 10px"><strong>variableName: </strong>rejected_dates
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### ELA (m)
```{r}
plotCol(thisTS,ind = 2)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### age (bp) [1-1]
```{r}
plotCol(chronTS,ind = 5)
```

### depth (cm) [1-1]
```{r}
plotCol(chronTS,ind = 6)
```

### depth_top (mm) [1-1]
```{r}
plotCol(chronTS,ind = 1)
```

### depth_bot (mm) [1-1]
```{r}
plotCol(chronTS,ind = 2)
```

### age14C (bp) [1-1]
```{r}
plotCol(chronTS,ind = 3)
```

### age_error (1s) [1-1]
```{r}
plotCol(chronTS,ind = 4)
```

### thickness (mm) [1-1]
```{r}
plotCol(chronTS,ind = 7)
```

### age (bp) [2-1]
```{r}
plotCol(chronTS,ind = 12)
```

### depth (cm) [2-1]
```{r}
plotCol(chronTS,ind = 13)
```

### depth_top (mm) [2-1]
```{r}
plotCol(chronTS,ind = 8)
```

### depth_bot (mm) [2-1]
```{r}
plotCol(chronTS,ind = 9)
```

### age14C (bp) [2-1]
```{r}
plotCol(chronTS,ind = 10)
```

### age_error (1s) [2-1]
```{r}
plotCol(chronTS,ind = 11)
```

### thickness (mm) [2-1]
```{r}
plotCol(chronTS,ind = 14)
```

### age_type () [2-1]
```{r}
plotCol(chronTS,ind = 15)
```

### core_name () [2-1]
```{r}
plotCol(chronTS,ind = 16)
```

### lab_id () [2-1]
```{r}
plotCol(chronTS,ind = 17)
```

### material_dated () [2-1]
```{r}
plotCol(chronTS,ind = 18)
```

### rejected_dates () [2-1]
```{r}
plotCol(chronTS,ind = 19)
```
