---
title: "GeoB1711_4"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 228
thisTS <- TS[which(udsn[i] == dsn)]
```
#GeoB1711_4

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](GeoB1711_4.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/GeoB1711_4.lpd)
            

[Download paleoData only (csv)](GeoB1711_4.csv)
            

[Download chronData only (csv)](GeoB1711_4-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>c("https://doi.pangaea.de/10.1594/PANGAEA.218245", "https://doi.pangaea.de/10.1594/PANGAEA.58042", "https://doi.pangaea.de/10.1594/PANGAEA.52469", "https://doi.pangaea.de/10.1594/PANGAEA.143593")
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Little, M.G."), list(name = "Schneider, R.R."), list(name = "Kroon, D."), list(name = "Price, B."), list(name = "Bickert, T."), list(name = "Wefer, G."))
<p style="margin-left: 10px"><strong>journal: </strong>Palaeogeography, Palaeoclimatology, Palaeoecology
<p style="margin-left: 10px"><strong>volume: </strong>130
<p style="margin-left: 10px"><strong>title: </strong>Rapid palaeoceanographic changes in the Benguela Upwelling System for the last 160,000 years as indicated by abundances of planktonic foraminifera
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Kirst, Georg J."), list(name = "Schneider, Ralph R."), list(name = "Mueller, Peter J."), list(name = "von Storch, Isabel"), list(name = "Wefer, Gerold"))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Research
<p style="margin-left: 10px"><strong>volume: </strong>52
<p style="margin-left: 10px"><strong>title: </strong>Late Quaternary Temperature Variability in the Benguela Current System Derived from Alkenones
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
</details>
<details style="margin-left: 10px">
<summary>pub4</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Vidal, L."), list(name = "Schneider, R.R."), list(name = "Marchal, O."), list(name = "Bickert, T."), list(name = "Stocker, T.F."), list(name = "Wefer, G."))
<p style="margin-left: 10px"><strong>journal: </strong>Climate Dynamics
<p style="margin-left: 10px"><strong>volume: </strong>15
<p style="margin-left: 10px"><strong>title: </strong>Link between the North and South Atlantic during the Heinrich events of the last glacial period
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-23.315
<p style="margin-left: 0px"><strong>longitude: </strong>12.3767
<p style="margin-left: 0px"><strong>elevation: </strong>-1967
<p style="margin-left: 0px"><strong>siteName: </strong>GeoB1711_4
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RNpiVveLLXO
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>CaCO3 (percent) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RJOIZ6uJIV2
<p style="margin-left: 10px"><strong>variableName: </strong>CaCO3
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>CaCO3_percent
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RgoTgPd2z8I
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RA7uYyQmOkI
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>C_wuellerstorfi_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RyTNbJaBxBL
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>planktic.d13C (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RmHiZuEa6kd
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G_inflata_d13C_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RP6Si8nTn0Q
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>G_inflata_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RlzCB7tSTp3
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RUgrjhJtlcw
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RcDvhOD1NEn
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_1_12_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>TOC (percent) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RAiADtccGF4
<p style="margin-left: 10px"><strong>variableName: </strong>TOC
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>TOC_percent
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C37.concentration (g) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RPENVrDMleN
<p style="margin-left: 10px"><strong>variableName: </strong>C37.concentration
<p style="margin-left: 10px"><strong>units: </strong>g
<p style="margin-left: 10px"><strong>description: </strong>C37_3Me_ng_g
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C37.concentration (g) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RGj3MVVxLvq
<p style="margin-left: 10px"><strong>variableName: </strong>C37.concentration
<p style="margin-left: 10px"><strong>units: </strong>g
<p style="margin-left: 10px"><strong>description: </strong>C37_2Me_ng_g
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Uk37 (missing) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ridn7bDV52c
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>UK'37
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1rmFusbTUF
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>dateType ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RVs2ipGGMIU
<p style="margin-left: 10px"><strong>variableName: </strong>dateType
</details>
<details style="margin-left: 10px">
<summary>measurementMaterial ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RuZaVowie1t
<p style="margin-left: 10px"><strong>variableName: </strong>measurementMaterial
</details>
<details style="margin-left: 10px">
<summary>sensorSpecies ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RJCNjrDzRQz
<p style="margin-left: 10px"><strong>variableName: </strong>sensorSpecies
</details>
<details style="margin-left: 10px">
<summary>labID ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R0THC86z0Mh
<p style="margin-left: 10px"><strong>variableName: </strong>labID
</details>
<details style="margin-left: 10px">
<summary>age14C (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R4c3N7f2F5m
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CHi (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLxH0SL4sjQ
<p style="margin-left: 10px"><strong>variableName: </strong>age14CHi
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CLow (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R7PmL4oi24W
<p style="margin-left: 10px"><strong>variableName: </strong>age14CLow
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>reservoirAge (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RThIR5TCkcE
<p style="margin-left: 10px"><strong>variableName: </strong>reservoirAge
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>rejected ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RCTo69F1yBC
<p style="margin-left: 10px"><strong>variableName: </strong>rejected
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### CaCO3 (percent)
```{r}
plotCol(thisTS,ind = 2)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 4)
```

### planktic.d13C (permil)
```{r}
plotCol(thisTS,ind = 6)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 7)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 14)
```

### TOC (percent)
```{r}
plotCol(thisTS,ind = 10)
```

### C37.concentration (g)
```{r}
plotCol(thisTS,ind = 11)
```

### C37.concentration (g)
```{r}
plotCol(thisTS,ind = 12)
```

### Uk37 (missing)
```{r}
plotCol(thisTS,ind = 13)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### dateType ()
```{r}
plotCol(chronTS,ind = 1)
```

### measurementMaterial ()
```{r}
plotCol(chronTS,ind = 3)
```

### sensorSpecies ()
```{r}
plotCol(chronTS,ind = 4)
```

### labID ()
```{r}
plotCol(chronTS,ind = 5)
```

### age14C (kyr)
```{r}
plotCol(chronTS,ind = 6)
```

### age14CHi (kyr)
```{r}
plotCol(chronTS,ind = 7)
```

### age14CLow (kyr)
```{r}
plotCol(chronTS,ind = 8)
```

### reservoirAge (kyr)
```{r}
plotCol(chronTS,ind = 9)
```

### rejected ()
```{r}
plotCol(chronTS,ind = 10)
```
