---
title: "JinchueanBog.Yu.2013"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 358
thisTS <- TS[which(udsn[i] == dsn)]
```
#JinchueanBog.Yu.2013

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](JinchueanBog.Yu.2013.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/JinchueanBog.Yu.2013.lpd)
            

[Download paleoData only (csv)](JinchueanBog.Yu.2013.csv)
            

[Download chronData only (csv)](JinchueanBog.Yu.2013-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>Peat
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Yu, Shi-Yong"))
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>23
<p style="margin-left: 10px"><strong>pages: </strong>1507-1516
<p style="margin-left: 10px"><strong>title: </strong>Quantitative reconstruction of mid- to late-Holocene climate in NE China from peat cellulose stable oxygen and carbon isotope records and mechanistic models
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Hong, Y. T."), list(name = "Jiang, H. B."), list(name = "Liu, T. S."), list(name = "Zhou, L. P."), list(name = "Beer, J."), list(name = "Li, H. D."), list(name = "Leng, X. T."), list(name = "Hong, B."), list(name = "Qin, X. G."))
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>10
<p style="margin-left: 10px"><strong>pages: </strong>1507-1516
<p style="margin-left: 10px"><strong>title: </strong>Response of climate to solar forcing recorded in a 6000-yearδ18O                 time-series of Chinese peat cellulose
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Hong, Y.T."), list(name = "Wang, Z.G."), list(name = "Jiang, H.B."), list(name = "Lin, Q.H."), list(name = "Hong, B."), list(name = "Zhu, Y.X."), list(name = "Wang, Y."), list(name = "Xu, L.S."), list(name = "Leng, X.T."), list(name = "Li, H.D."))
<p style="margin-left: 10px"><strong>journal: </strong>Earth and Planetary Science Letters
<p style="margin-left: 10px"><strong>volume: </strong>185
<p style="margin-left: 10px"><strong>pages: </strong>1507-1516
<p style="margin-left: 10px"><strong>title: </strong>A 6000-year record of changes in drought and precipitation in northeastern China based on a δ13C time series from peat cellulose
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>42.33
<p style="margin-left: 0px"><strong>longitude: </strong>126.37
<p style="margin-left: 0px"><strong>elevation: </strong>600
<p style="margin-left: 0px"><strong>siteName: </strong>Jinchuan Peat Bog
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB40546116
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB70c87e7c
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB222fb2bd
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Proxy inverse modeling of the stable carbon and oxygen isotopes using a mechanistic model that governs the fractionation of these isotopic species in peat cellulose
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>summer (May-Oct)
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>ageMin (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBefeba8f7
<p style="margin-left: 10px"><strong>variableName: </strong>ageMin
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>uncertaintyHigh (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB925aa804
<p style="margin-left: 10px"><strong>variableName: </strong>uncertaintyHigh
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>uncertaintyLow (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBb1cb6234
<p style="margin-left: 10px"><strong>variableName: </strong>uncertaintyLow
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>age (yr bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB47b37b54
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr bp
</details>
<details style="margin-left: 10px">
<summary>depthTop (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB501fffa2
<p style="margin-left: 10px"><strong>variableName: </strong>depthTop
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>depthBot (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB427c25eb
<p style="margin-left: 10px"><strong>variableName: </strong>depthBot
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>type (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBb04c6bcd
<p style="margin-left: 10px"><strong>variableName: </strong>type
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>
<details style="margin-left: 10px">
<summary>error (yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1f63c56d
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>
<details style="margin-left: 10px">
<summary>includeY/N (NA)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB416df74e
<p style="margin-left: 10px"><strong>variableName: </strong>includeY/N
<p style="margin-left: 10px"><strong>units: </strong>NA
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 4)
```

### ageMin (BP)
```{r}
plotCol(thisTS,ind = 2)
```

### uncertaintyHigh (degC)
```{r}
plotCol(thisTS,ind = 5)
```

### uncertaintyLow (degC)
```{r}
plotCol(thisTS,ind = 6)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### age (yr bp)
```{r}
plotCol(chronTS,ind = 4)
```

### depthTop (cm)
```{r}
plotCol(chronTS,ind = 1)
```

### depthBot (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### type (NA)
```{r}
plotCol(chronTS,ind = 3)
```

### error (yr)
```{r}
plotCol(chronTS,ind = 5)
```

### includeY/N (NA)
```{r}
plotCol(chronTS,ind = 6)
```
