---
title: "Khoe.Leipe.2015"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 381
thisTS <- TS[which(udsn[i] == dsn)]
```
#Khoe.Leipe.2015

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](Khoe.Leipe.2015.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/Khoe.Leipe.2015.lpd)
            

[Download paleoData only (csv)](Khoe.Leipe.2015.csv)
            

[Download chronData only (csv)](Khoe.Leipe.2015-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>LakeSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Leipe, Christian"), list(name = "Nakagawa, Takeshi"), list(name = "Gotanda, Katsuya"), list(name = "Mueller, Stefanie"), list(name = "Tarasov, Pavel E."))
<p style="margin-left: 10px"><strong>citeKey: </strong>leipe2015latequaternaryvegetationa
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Science Reviews
<p style="margin-left: 10px"><strong>volume: </strong>116
<p style="margin-left: 10px"><strong>title: </strong>Late Quaternary vegetation and climate dynamics at the northern limit of the East Asian summer monsoon and its regional and global-scale controls
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>51.34
<p style="margin-left: 0px"><strong>longitude: </strong>142.14
<p style="margin-left: 0px"><strong>elevation: </strong>15
<p style="margin-left: 0px"><strong>siteName: </strong>Khoe
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RTbKXP5jINQ
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RgPYCGdGO8l
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rqy9njwWvxO
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>MAT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHcc7072b7
<p style="margin-left: 10px"><strong>variableName: </strong>MAT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, annual mean
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>CMT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHa67edeec
<p style="margin-left: 10px"><strong>variableName: </strong>CMT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, coldest month
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>WMT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH6a978f14
<p style="margin-left: 10px"><strong>variableName: </strong>WMT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, warmest month
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MAP (mm/yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHdbde26f9
<p style="margin-left: 10px"><strong>variableName: </strong>MAP
<p style="margin-left: 10px"><strong>units: </strong>mm/yr
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>monsoon
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MAT_min (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHa2d39720
<p style="margin-left: 10px"><strong>variableName: </strong>MAT_min
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, annual mean, minimum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MAT_max (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH4ebe13ba
<p style="margin-left: 10px"><strong>variableName: </strong>MAT_max
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, annual mean, maximum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>CMT_min (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHc879da85
<p style="margin-left: 10px"><strong>variableName: </strong>CMT_min
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, coldest month, minimum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>CMT_max (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH00140757
<p style="margin-left: 10px"><strong>variableName: </strong>CMT_max
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, coldest month, maximum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>WMT_min (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHe55d528d
<p style="margin-left: 10px"><strong>variableName: </strong>WMT_min
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, warmest month, minimum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>WMT_max (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH77d77b7d
<p style="margin-left: 10px"><strong>variableName: </strong>WMT_max
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, warmest month, maximum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MAP_min (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH788311e3
<p style="margin-left: 10px"><strong>variableName: </strong>MAP_min
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean, minimum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MAP_max (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHe80938b9
<p style="margin-left: 10px"><strong>variableName: </strong>MAP_max
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean, maximum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TreeCover_min (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH974709f1
<p style="margin-left: 10px"><strong>variableName: </strong>TreeCover_min
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Tree coverage, minimum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TreeCover (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH0e40c2d1
<p style="margin-left: 10px"><strong>variableName: </strong>TreeCover
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Tree coverage
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TreeCover_max (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH597aa72b
<p style="margin-left: 10px"><strong>variableName: </strong>TreeCover_max
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Tree coverage, maximum
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Analogues (number)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH4ad1f0dd
<p style="margin-left: 10px"><strong>variableName: </strong>Analogues
<p style="margin-left: 10px"><strong>units: </strong>number
<p style="margin-left: 10px"><strong>description: </strong>Number of analogues
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf7422476
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (kaBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe54dc6d7
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>kaBP
<p style="margin-left: 10px"><strong>description: </strong>AMS14C
</details>
<details style="margin-left: 10px">
<summary>LabID ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDece0f148
<p style="margin-left: 10px"><strong>variableName: </strong>LabID
</details>
<details style="margin-left: 10px">
<summary>material ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD797006f7
<p style="margin-left: 10px"><strong>variableName: </strong>material
</details>
<details style="margin-left: 10px">
<summary>error (ka)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD777a1b28
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>ka
</details>
<details style="margin-left: 10px">
<summary>calibrated_age (kaBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD493f1394
<p style="margin-left: 10px"><strong>variableName: </strong>calibrated_age
<p style="margin-left: 10px"><strong>units: </strong>kaBP
</details>
<details style="margin-left: 10px">
<summary>Reference ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD23f54a01
<p style="margin-left: 10px"><strong>variableName: </strong>Reference
</details>
<details style="margin-left: 10px">
<summary>age2 (kaBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD53aad777
<p style="margin-left: 10px"><strong>variableName: </strong>age2
<p style="margin-left: 10px"><strong>units: </strong>kaBP
<p style="margin-left: 10px"><strong>description: </strong>AMS14C
</details>
<details style="margin-left: 10px">
<summary>age2min (kaBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd7695163
<p style="margin-left: 10px"><strong>variableName: </strong>age2min
<p style="margin-left: 10px"><strong>units: </strong>kaBP
</details>
<details style="margin-left: 10px">
<summary>age2max (kaBP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9c79485d
<p style="margin-left: 10px"><strong>variableName: </strong>age2max
<p style="margin-left: 10px"><strong>units: </strong>kaBP
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### MAT (degC)
```{r}
plotCol(thisTS,ind = 5)
```

### CMT (degC)
```{r}
plotCol(thisTS,ind = 8)
```

### WMT (degC)
```{r}
plotCol(thisTS,ind = 11)
```

### MAP (mm/yr)
```{r}
plotCol(thisTS,ind = 14)
```

### MAT_min (degC)
```{r}
plotCol(thisTS,ind = 1)
```

### MAT_max (degC)
```{r}
plotCol(thisTS,ind = 6)
```

### CMT_min (degC)
```{r}
plotCol(thisTS,ind = 7)
```

### CMT_max (degC)
```{r}
plotCol(thisTS,ind = 9)
```

### WMT_min (degC)
```{r}
plotCol(thisTS,ind = 10)
```

### WMT_max (degC)
```{r}
plotCol(thisTS,ind = 12)
```

### MAP_min (mm)
```{r}
plotCol(thisTS,ind = 13)
```

### MAP_max (mm)
```{r}
plotCol(thisTS,ind = 15)
```

### TreeCover_min (percent)
```{r}
plotCol(thisTS,ind = 16)
```

### TreeCover (percent)
```{r}
plotCol(thisTS,ind = 17)
```

### TreeCover_max (percent)
```{r}
plotCol(thisTS,ind = 18)
```

### Analogues (number)
```{r}
plotCol(thisTS,ind = 19)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (m)
```{r}
plotCol(chronTS,ind = 2)
```

### age (kaBP)
```{r}
plotCol(chronTS,ind = 4)
```

### LabID ()
```{r}
plotCol(chronTS,ind = 1)
```

### material ()
```{r}
plotCol(chronTS,ind = 3)
```

### error (ka)
```{r}
plotCol(chronTS,ind = 5)
```

### calibrated_age (kaBP)
```{r}
plotCol(chronTS,ind = 6)
```

### Reference ()
```{r}
plotCol(chronTS,ind = 7)
```

### age2 (kaBP)
```{r}
plotCol(chronTS,ind = 8)
```

### age2min (kaBP)
```{r}
plotCol(chronTS,ind = 9)
```

### age2max (kaBP)
```{r}
plotCol(chronTS,ind = 10)
```
