---
title: "Lions.Sabatier.2012"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 465
thisTS <- TS[which(udsn[i] == dsn)]
```
#Lions.Sabatier.2012

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](Lions.Sabatier.2012.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/Lions.Sabatier.2012.lpd)
            

[Download paleoData only (csv)](Lions.Sabatier.2012.csv)
            

[Download chronData only (csv)](Lions.Sabatier.2012-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>ftp://ftp.ncdc.noaa.gov/pub/data/paleo/contributions_by_author/sabatier2012/sabatier2012.xls
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Sabatier, Pierre"), list(name = "Dezileau, Laurent"), list(name = "Colin, Christophe"), list(name = "Briqueu, Louis"), list(name = "Bouchette, Frederic"), list(name = "Martinez, Philippe"), list(name = "Siani, Giuseppe"), list(name = "Raynal, Olivier"), list(name = "Von Grafenstein, Ulrich"))
<p style="margin-left: 10px"><strong>citeKey: </strong>needs0needsatitle
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Research
<p style="margin-left: 10px"><strong>volume: </strong>77
<p style="margin-left: 10px"><strong>title: </strong>7000 years of paleostorm activity in the NW Mediterranean Sea in response to Holocene climate events
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>43.5078
<p style="margin-left: 0px"><strong>longitude: </strong>3.8708
<p style="margin-left: 0px"><strong>elevation: </strong>-0.6
<p style="margin-left: 0px"><strong>siteName: </strong>Lions
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RvNn19ecAA2
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RDEIsYqxrCV
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RYw51sVOB1Z
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>SM/IlliteChlorite (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5927d261
<p style="margin-left: 10px"><strong>variableName: </strong>SM/IlliteChlorite
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>The ratios of smectite/(illite+chlorite) were used as indicators to reconstruct changes in the sedimentation sources from the Mosson drainage basin versus the marine environment, and have been shown to be strongly linked to paleostorm events. Low values of SM/(Il+Cl) ratio correspond to periods of high storm activity in the NW Mediterranean Sea.
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>storm
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>age ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDdd04df25
<p style="margin-left: 10px"><strong>variableName: </strong>age
</details>
<details style="margin-left: 10px">
<summary>dummy2 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD07733103
<p style="margin-left: 10px"><strong>variableName: </strong>dummy2
</details>
<details style="margin-left: 10px">
<summary>dummy3 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa9f97603
<p style="margin-left: 10px"><strong>variableName: </strong>dummy3
</details>
<details style="margin-left: 10px">
<summary>dummy4 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD75210c4b
<p style="margin-left: 10px"><strong>variableName: </strong>dummy4
</details>
<details style="margin-left: 10px">
<summary>dummy5 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD75441c50
<p style="margin-left: 10px"><strong>variableName: </strong>dummy5
</details>
<details style="margin-left: 10px">
<summary>dummy6 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5d2577c1
<p style="margin-left: 10px"><strong>variableName: </strong>dummy6
</details>
<details style="margin-left: 10px">
<summary>dummy7 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDdeb2256a
<p style="margin-left: 10px"><strong>variableName: </strong>dummy7
</details>
<details style="margin-left: 10px">
<summary>dummy8 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDdca86791
<p style="margin-left: 10px"><strong>variableName: </strong>dummy8
</details>
<details style="margin-left: 10px">
<summary>dummy9 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe81579ca
<p style="margin-left: 10px"><strong>variableName: </strong>dummy9
</details>
<details style="margin-left: 10px">
<summary>dummy10 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa74c882d
<p style="margin-left: 10px"><strong>variableName: </strong>dummy10
</details>
<details style="margin-left: 10px">
<summary>dummy11 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2c0b5704
<p style="margin-left: 10px"><strong>variableName: </strong>dummy11
</details>
<details style="margin-left: 10px">
<summary>dummy12 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDbeb25e2d
<p style="margin-left: 10px"><strong>variableName: </strong>dummy12
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### SM/IlliteChlorite (missing)
```{r}
plotCol(thisTS,ind = 1)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### age ()
```{r}
plotCol(chronTS,ind = 1)
```

### dummy2 ()
```{r}
plotCol(chronTS,ind = 2)
```

### dummy3 ()
```{r}
plotCol(chronTS,ind = 3)
```

### dummy4 ()
```{r}
plotCol(chronTS,ind = 4)
```

### dummy5 ()
```{r}
plotCol(chronTS,ind = 5)
```

### dummy6 ()
```{r}
plotCol(chronTS,ind = 6)
```

### dummy7 ()
```{r}
plotCol(chronTS,ind = 7)
```

### dummy8 ()
```{r}
plotCol(chronTS,ind = 8)
```

### dummy9 ()
```{r}
plotCol(chronTS,ind = 9)
```

### dummy10 ()
```{r}
plotCol(chronTS,ind = 10)
```

### dummy11 ()
```{r}
plotCol(chronTS,ind = 11)
```

### dummy12 ()
```{r}
plotCol(chronTS,ind = 12)
```
