---
title: "M35003_4"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 494
thisTS <- TS[which(udsn[i] == dsn)]
```
#M35003_4

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](M35003_4.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/M35003_4.lpd)
            

[Download paleoData only (csv)](M35003_4.csv)
            

[Download chronData only (csv)](M35003_4-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>c("https://doi.pangaea.de/10.1594/PANGAEA.55754", "ftp://ftp.ncdc.noaa.gov/pub/data/paleo/paleocean//sediment_files/complete/m35003-4-tab.txt", "https://doi.pangaea.de/10.1594/PANGAEA.266634", "https://doi.pangaea.de/10.1594/PANGAEA.55760", "https://doi.pangaea.de/10.1594/PANGAEA.55761", "https://doi.pangaea.de/10.1594/PANGAEA.55753")
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Ruehlemann, Carsten"), list(name = "Mulitza, Stefan"), list(name = "Mueller, Peter J."), list(name = "Wefer, Gerold"), list(name = "Zahn, Rainer"))
<p style="margin-left: 10px"><strong>journal: </strong>Nature
<p style="margin-left: 10px"><strong>volume: </strong>402
<p style="margin-left: 10px"><strong>title: </strong>Warming of the tropical Atlantic Ocean and slowdown of thermohaline circulation during the last deglaciation
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>12.0897
<p style="margin-left: 0px"><strong>longitude: </strong>-61.2437
<p style="margin-left: 0px"><strong>elevation: </strong>-1299
<p style="margin-left: 0px"><strong>siteName: </strong>M35003_4
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (m) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R43qzunxmEf
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RozO7dQWI9l
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RwaLWFqn8De
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_cal_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RI2vCrHM2fw
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>sst_uk37
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>C37.concentration (g) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RdO30eYawYJ
<p style="margin-left: 10px"><strong>variableName: </strong>C37.concentration
<p style="margin-left: 10px"><strong>units: </strong>g
<p style="margin-left: 10px"><strong>description: </strong>37_2conc
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>C37.concentration (g) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RYS26m1CzsQ
<p style="margin-left: 10px"><strong>variableName: </strong>C37.concentration
<p style="margin-left: 10px"><strong>units: </strong>g
<p style="margin-left: 10px"><strong>description: </strong>37_3conc
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>planktic.d18O (permil) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RAYCTpSxmsZ
<p style="margin-left: 10px"><strong>variableName: </strong>planktic.d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>d18Og_rub_p
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Uk37 (missing) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R8mdEg5MmpL
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>uk37
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RjTP5fALHgB
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R5wdyxkjJyr
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_win_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-2]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RMD9Cw1t1oU
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_sum_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RyoE5eGHoKy
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>TOC (percent) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RQdv2EiToeb
<p style="margin-left: 10px"><strong>variableName: </strong>TOC
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>TOC_percent
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>CaCO3 (percent) [1-3]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R0awZ62wbT5
<p style="margin-left: 10px"><strong>variableName: </strong>CaCO3
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>CaCO3_percent
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLmcmw10m1h
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RaWGMGBPa4u
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>Cibicidoides_sp_d13C_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RyWx8GO6gDT
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>Cibicidoides_sp_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d13C (permil) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLoEHO49Tp3
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>Uvigerina_sp_d13C_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil) [1-4]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>REWYF5hr5DO
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>Uvigerina_sp_d18O_per_mil_PDB
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ro0ygXOzZIk
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R5WlDUngRcQ
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>ROrJyItwTqx
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_Tc_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-5]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R0wvIqvzYkO
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_Tw_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>depth (m) [1-6]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rm2RhapbO7y
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
</details>
<details style="margin-left: 10px">
<summary>age (BP) [1-6]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RWocFeLN0px
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Age_ka_BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-6]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RuZd3euHEp0
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_sum_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC) [1-6]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RtKEt5VqIb4
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST_win_degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>T
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RLou4kGINbD
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R5WsIdnpVOf
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>dateType ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RHmutRSXBJX
<p style="margin-left: 10px"><strong>variableName: </strong>dateType
</details>
<details style="margin-left: 10px">
<summary>sensorSpecies ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1jZdlgaxiz
<p style="margin-left: 10px"><strong>variableName: </strong>sensorSpecies
</details>
<details style="margin-left: 10px">
<summary>labID ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RqookV0YK0j
<p style="margin-left: 10px"><strong>variableName: </strong>labID
</details>
<details style="margin-left: 10px">
<summary>age14C (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RPCBFUSlTii
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CUncertainty (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RuHjXTX1mFS
<p style="margin-left: 10px"><strong>variableName: </strong>age14CUncertainty
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CHi (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R5i4J9LYMO0
<p style="margin-left: 10px"><strong>variableName: </strong>age14CHi
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>age14CLow (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RgHGaU3KI6Z
<p style="margin-left: 10px"><strong>variableName: </strong>age14CLow
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>reservoirAge (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RRrg83RLT0d
<p style="margin-left: 10px"><strong>variableName: </strong>reservoirAge
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>ageUncertainty1sigLo (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RhBhcL8hLa9
<p style="margin-left: 10px"><strong>variableName: </strong>ageUncertainty1sigLo
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>
<details style="margin-left: 10px">
<summary>ageUncertainty1sigHi (kyr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RID1mGdxUi8
<p style="margin-left: 10px"><strong>variableName: </strong>ageUncertainty1sigHi
<p style="margin-left: 10px"><strong>units: </strong>kyr
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 7)
```

### C37.concentration (g)
```{r}
plotCol(thisTS,ind = 4)
```

### C37.concentration (g)
```{r}
plotCol(thisTS,ind = 5)
```

### planktic.d18O (permil)
```{r}
plotCol(thisTS,ind = 6)
```

### Uk37 (missing)
```{r}
plotCol(thisTS,ind = 8)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 10)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 11)
```

### TOC (percent)
```{r}
plotCol(thisTS,ind = 13)
```

### CaCO3 (percent)
```{r}
plotCol(thisTS,ind = 14)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 16)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 17)
```

### d13C (permil)
```{r}
plotCol(thisTS,ind = 18)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 19)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 22)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 23)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 26)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 27)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### age (kyr)
```{r}
plotCol(chronTS,ind = 10)
```

### dateType ()
```{r}
plotCol(chronTS,ind = 1)
```

### sensorSpecies ()
```{r}
plotCol(chronTS,ind = 3)
```

### labID ()
```{r}
plotCol(chronTS,ind = 4)
```

### age14C (kyr)
```{r}
plotCol(chronTS,ind = 5)
```

### age14CUncertainty (kyr)
```{r}
plotCol(chronTS,ind = 6)
```

### age14CHi (kyr)
```{r}
plotCol(chronTS,ind = 7)
```

### age14CLow (kyr)
```{r}
plotCol(chronTS,ind = 8)
```

### reservoirAge (kyr)
```{r}
plotCol(chronTS,ind = 9)
```

### ageUncertainty1sigLo (kyr)
```{r}
plotCol(chronTS,ind = 11)
```

### ageUncertainty1sigHi (kyr)
```{r}
plotCol(chronTS,ind = 12)
```
