---
title: "Marion.Mathewes.1973"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 511
thisTS <- TS[which(udsn[i] == dsn)]
```
#Marion.Mathewes.1973

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](Marion.Mathewes.1973.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/Marion.Mathewes.1973.lpd)
            

[Download paleoData only (csv)](Marion.Mathewes.1973.csv)
            

[Download chronData only (csv)](Marion.Mathewes.1973-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>LakeSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>Jeremiah Marsicek
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Mathewes, Rolf W."))
<p style="margin-left: 10px"><strong>journal: </strong>Canadian Journal of Botany
<p style="margin-left: 10px"><strong>volume: </strong>51
<p style="margin-left: 10px"><strong>pages: </strong>2085-2103
<p style="margin-left: 10px"><strong>title: </strong>A palynological study of postglacial vegetation changes in the University Research Forest, southwestern British Columbia
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Mathewes, Rolf W."), list(name = "Heusser, Linda E."))
<p style="margin-left: 10px"><strong>journal: </strong>Canadian Journal of Botany
<p style="margin-left: 10px"><strong>volume: </strong>59
<p style="margin-left: 10px"><strong>pages: </strong>2085-2103
<p style="margin-left: 10px"><strong>title: </strong>A 12 000 year palynological record of temperature and precipitation trends in southwestern British Columbia
</details>
<details style="margin-left: 10px">
<summary>pub3</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Marsicek, Jeremiah"), list(name = "Shuman, Bryan N."), list(name = "Bartlein, Patrick J."), list(name = "Shafer, Sarah L."), list(name = "Brewer, Simon"))
<p style="margin-left: 10px"><strong>journal: </strong>Nature
<p style="margin-left: 10px"><strong>volume: </strong>554
<p style="margin-left: 10px"><strong>pages: </strong>2085-2103
<p style="margin-left: 10px"><strong>title: </strong>Reconciling divergent trends and millennial variations in Holocene temperatures
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>49.31
<p style="margin-left: 0px"><strong>longitude: </strong>-122.55
<p style="margin-left: 0px"><strong>elevation: </strong>305
<p style="margin-left: 0px"><strong>siteName: </strong>Marion
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2L5m1nekvdP
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lcqu4ezpxP
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2L5f5ry0h2P
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>warmest month
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lbh1cglq5P
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>coldest month
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lrq9qdhpzP
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm/yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lx9moy4tqP
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm/yr
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>precipitation@surface
</details>
</details>
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2LeydrttujC
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>ageType (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lbkf86ev1C
<p style="margin-left: 10px"><strong>variableName: </strong>ageType
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>labID (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lvyvnhv9gC
<p style="margin-left: 10px"><strong>variableName: </strong>labID
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>age14Cuncertainty (yr 14C)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lknj2u459C
<p style="margin-left: 10px"><strong>variableName: </strong>age14Cuncertainty
<p style="margin-left: 10px"><strong>units: </strong>yr 14C
</details>
<details style="margin-left: 10px">
<summary>age14C (yr 14C BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2L1oszki9oC
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
<p style="margin-left: 10px"><strong>units: </strong>yr 14C BP
</details>
<details style="margin-left: 10px">
<summary>measurementMaterial (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2L25cnwuytC
<p style="margin-left: 10px"><strong>variableName: </strong>measurementMaterial
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>notes (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>M2Lzqem5x0qC
<p style="margin-left: 10px"><strong>variableName: </strong>notes
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 3)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 4)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 5)
```

### precipitation (mm/yr)
```{r}
plotCol(thisTS,ind = 6)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 3)
```

### ageType (unitless)
```{r}
plotCol(chronTS,ind = 1)
```

### labID (unitless)
```{r}
plotCol(chronTS,ind = 2)
```

### age14Cuncertainty (yr 14C)
```{r}
plotCol(chronTS,ind = 4)
```

### age14C (yr 14C BP)
```{r}
plotCol(chronTS,ind = 5)
```

### measurementMaterial (unitless)
```{r}
plotCol(chronTS,ind = 6)
```

### notes (unitless)
```{r}
plotCol(chronTS,ind = 7)
```
