---
title: "MD032601.Crosta.2007"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 532
thisTS <- TS[which(udsn[i] == dsn)]
```
#MD032601.Crosta.2007

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](MD032601.Crosta.2007.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/MD032601.Crosta.2007.lpd)
            

[Download paleoData only (csv)](MD032601.Crosta.2007.csv)
            

[Download chronData only (csv)](MD032601.Crosta.2007-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Crosta, X."), list(name = "Debret, M."), list(name = "Denis, D."), list(name = "Courty, M. A."), list(name = "Ther, O."))
<p style="margin-left: 10px"><strong>citeKey: </strong>crosta2007holocenelongandshorttermc
<p style="margin-left: 10px"><strong>journal: </strong>Geochemistry, Geophysics, Geosystems
<p style="margin-left: 10px"><strong>volume: </strong>8
<p style="margin-left: 10px"><strong>pages: </strong>n/a-n/a
<p style="margin-left: 10px"><strong>title: </strong>Holocene long- and short-term climate changes off Adélie Land, East Antarctica
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-66
<p style="margin-left: 0px"><strong>longitude: </strong>138.6
<p style="margin-left: 0px"><strong>siteName: </strong>DUrvilleTrough
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RxDrUkxHp93
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RzC25Ll0NFf
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>F_kerg__ (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH0a861633
<p style="margin-left: 10px"><strong>variableName: </strong>F_kerg__
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Fragilariopsiskerguelensis,relativeabundanceinofthediatomassemblages
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>F_curta_gp_ (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHc606c2e5
<p style="margin-left: 10px"><strong>variableName: </strong>F_curta_gp_
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Fragilariopsiscurtagroup,relativeabundanceinofthediatomassemblages
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>ICE
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>C (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH53c1f24a
<p style="margin-left: 10px"><strong>variableName: </strong>C
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Chaetocerosrestingsporegroup,relativeabundanceinofthediatomassemblages
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>temperature (percent)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH28bebb64
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>percent
<p style="margin-left: 10px"><strong>description: </strong>Thalassiosiraantarcticagroup,relativeabundanceinofthediatomassemblages
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>glacierCoverage (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH83dacc75
<p style="margin-left: 10px"><strong>variableName: </strong>glacierCoverage
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>Porosiraglacialisgroup,relativeabundanceinofthediatomassemblages
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>diatom_abundance (millions of valves/g dry sed)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GHafcdb9b8
<p style="margin-left: 10px"><strong>variableName: </strong>diatom_abundance
<p style="margin-left: 10px"><strong>units: </strong>millions of valves/g dry sed
<p style="margin-left: 10px"><strong>description: </strong>Diatomabsoluteabundances,millionsofvalvespergofdry
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB09a6ba56
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (yr bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB0fd525a8
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr bp
</details>
<details style="margin-left: 10px">
<summary>error (yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB11c6a89b
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>
<details style="margin-left: 10px">
<summary>type (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB4ed468f6
<p style="margin-left: 10px"><strong>variableName: </strong>type
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>material (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB0f1f741b
<p style="margin-left: 10px"><strong>variableName: </strong>material
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### F_kerg__ (percent)
```{r}
plotCol(thisTS,ind = 1)
```

### F_curta_gp_ (percent)
```{r}
plotCol(thisTS,ind = 4)
```

### C (percent)
```{r}
plotCol(thisTS,ind = 5)
```

### temperature (percent)
```{r}
plotCol(thisTS,ind = 6)
```

### glacierCoverage (missing)
```{r}
plotCol(thisTS,ind = 7)
```

### diatom_abundance (millions of valves/g dry sed)
```{r}
plotCol(thisTS,ind = 8)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 1)
```

### age (yr bp)
```{r}
plotCol(chronTS,ind = 2)
```

### error (yr)
```{r}
plotCol(chronTS,ind = 3)
```

### type (unitless)
```{r}
plotCol(chronTS,ind = 4)
```

### material (unitless)
```{r}
plotCol(chronTS,ind = 5)
```
