---
title: "MV0811-14JC.Du.2018"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 597
thisTS <- TS[which(udsn[i] == dsn)]
```
#MV0811-14JC.Du.2018

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](MV0811-14JC.Du.2018.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/MV0811-14JC.Du.2018.lpd)
            

[Download paleoData only (csv)](MV0811-14JC.Du.2018.csv)
            

[Download chronData only (csv)](MV0811-14JC.Du.2018-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.sciencedirect.com/science/article/pii/S002532271730227X
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Du, Xiaojing"), list(name = "Hendy, Ingrid"), list(name = "Schimmelmann, Arndt"))
<p style="margin-left: 10px"><strong>journal: </strong>Marine Geology
<p style="margin-left: 10px"><strong>volume: </strong>397
<p style="margin-left: 10px"><strong>pages: </strong>29-42
<p style="margin-left: 10px"><strong>title: </strong>A 9000-year flood history for Southern California: A revised stratigraphy of varved sediments in Santa Barbara Basin
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>34.3
<p style="margin-left: 0px"><strong>longitude: </strong>-120
<p style="margin-left: 0px"><strong>elevation: </strong>-591
<p style="margin-left: 0px"><strong>siteName: </strong>Mv0811-14JC
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD08ba3fea
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1dee7617
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1b643ee6
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>thickness (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7939faee
<p style="margin-left: 10px"><strong>variableName: </strong>thickness
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>Flood Layer Thickness. Composite flood record from three cores: MV0811-14JC, SPR0901-06KC and ODP 893A
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>flood
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>color (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDc7bda7fe
<p style="margin-left: 10px"><strong>variableName: </strong>color
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>flood layer color
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>layer_type (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD275256d3
<p style="margin-left: 10px"><strong>variableName: </strong>layer_type
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>uncorrected_depth_top (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD10c46c7c
<p style="margin-left: 10px"><strong>variableName: </strong>uncorrected_depth_top
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>uncorrected_depth_bot (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD8750a07d
<p style="margin-left: 10px"><strong>variableName: </strong>uncorrected_depth_bot
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>error_younger_age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf83c02e4
<p style="margin-left: 10px"><strong>variableName: </strong>error_younger_age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (unitless) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD3d1f6377
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>age (unitless) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDc10d2f94
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>core (unitless) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDcff90453
<p style="margin-left: 10px"><strong>variableName: </strong>core
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>depth_uncorrected (unitless) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDbae77930
<p style="margin-left: 10px"><strong>variableName: </strong>depth_uncorrected
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>error (unitless) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa899b0c6
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>age (yr BP) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDb19b9a9b
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr BP
<p style="margin-left: 10px"><strong>description: </strong>composite ages used for computing age model (radiocarbon, varve, etc)
</details>
<details style="margin-left: 10px">
<summary>depth (cm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD2acd7127
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>ID (unitless) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1a778a36
<p style="margin-left: 10px"><strong>variableName: </strong>ID
<p style="margin-left: 10px"><strong>units: </strong>unitless
<p style="margin-left: 10px"><strong>description: </strong>sample ID
</details>
<details style="margin-left: 10px">
<summary>error (yr) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD725da6e8
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>
<details style="margin-left: 10px">
<summary>reservoir (yr) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9a725b3b
<p style="margin-left: 10px"><strong>variableName: </strong>reservoir
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>
<details style="margin-left: 10px">
<summary>SD_error (yr) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD60a9bca4
<p style="margin-left: 10px"><strong>variableName: </strong>SD_error
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### thickness (cm)
```{r}
plotCol(thisTS,ind = 7)
```

### color (missing)
```{r}
plotCol(thisTS,ind = 1)
```

### layer_type (missing)
```{r}
plotCol(thisTS,ind = 2)
```

### uncorrected_depth_top (cm)
```{r}
plotCol(thisTS,ind = 3)
```

### uncorrected_depth_bot (cm)
```{r}
plotCol(thisTS,ind = 4)
```

### error_younger_age (BP)
```{r}
plotCol(thisTS,ind = 8)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (unitless) [1-1]
```{r}
plotCol(chronTS,ind = 3)
```

### age (unitless) [1-1]
```{r}
plotCol(chronTS,ind = 4)
```

### core (unitless) [1-1]
```{r}
plotCol(chronTS,ind = 1)
```

### depth_uncorrected (unitless) [1-1]
```{r}
plotCol(chronTS,ind = 2)
```

### error (unitless) [1-1]
```{r}
plotCol(chronTS,ind = 5)
```

### age (yr BP) [2-1]
```{r}
plotCol(chronTS,ind = 7)
```

### depth (cm) [2-1]
```{r}
plotCol(chronTS,ind = 9)
```

### ID (unitless) [2-1]
```{r}
plotCol(chronTS,ind = 6)
```

### error (yr) [2-1]
```{r}
plotCol(chronTS,ind = 8)
```

### reservoir (yr) [2-1]
```{r}
plotCol(chronTS,ind = 10)
```

### SD_error (yr) [2-1]
```{r}
plotCol(chronTS,ind = 11)
```
