---
title: "P178-15P.Tierney.2015"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 660
thisTS <- TS[which(udsn[i] == dsn)]
```
#P178-15P.Tierney.2015

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](P178-15P.Tierney.2015.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/P178-15P.Tierney.2015.lpd)
            

[Download paleoData only (csv)](P178-15P.Tierney.2015.csv)
            

[Download chronData only (csv)](P178-15P.Tierney.2015-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Tierney, Jessica E."), list(name = "Pausata, Francesco S. R."), list(name = "deMenocal, Peter"))
<p style="margin-left: 10px"><strong>citeKey: </strong>tierney2015deglacialindianmonsoonfai
<p style="margin-left: 10px"><strong>journal: </strong>Nature Geoscience
<p style="margin-left: 10px"><strong>volume: </strong>9
<p style="margin-left: 10px"><strong>title: </strong>Deglacial Indian monsoon failure and North Atlantic stadials linked by Indian Ocean surface cooling
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>11.955
<p style="margin-left: 0px"><strong>longitude: </strong>44.3
<p style="margin-left: 0px"><strong>elevation: </strong>-869
<p style="margin-left: 0px"><strong>siteName: </strong>P178-15P
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Rsm7za5cJrY
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R23MzD6YM7k
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RuPjCrdmNGr
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD13ec3942
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Sonzogni et al. 1997 Quaternary Research
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>NAm2kHydro111
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Tierney and Tingley 2015 Scientific Data
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDce0e7640
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>New multivariate calibration developed for this study; see Supplementary Information
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableDetailOriginal: </strong>SST
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Uk37 (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH40a0964a
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>TEX86 (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH5172eadb
<p style="margin-left: 10px"><strong>variableName: </strong>TEX86
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>Mg/Ca (mmol/mol)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>GH7d708cb7
<p style="margin-left: 10px"><strong>variableName: </strong>Mg/Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>NAm2kHydro031
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD87f9c656
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>top
</details>
<details style="margin-left: 10px">
<summary>labCode ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd737d3bd
<p style="margin-left: 10px"><strong>variableName: </strong>labCode
</details>
<details style="margin-left: 10px">
<summary>depth_2 (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDb3822f97
<p style="margin-left: 10px"><strong>variableName: </strong>depth_2
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>bottom
</details>
<details style="margin-left: 10px">
<summary>MaterialDated ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDb7ac9881
<p style="margin-left: 10px"><strong>variableName: </strong>MaterialDated
<p style="margin-left: 10px"><strong>description: </strong>planktonic foraminifera
</details>
<details style="margin-left: 10px">
<summary>age14C ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe7708f4b
<p style="margin-left: 10px"><strong>variableName: </strong>age14C
</details>
<details style="margin-left: 10px">
<summary>age14Cuncertainty ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1cc72e30
<p style="margin-left: 10px"><strong>variableName: </strong>age14Cuncertainty
</details>
<details style="margin-left: 10px">
<summary>datemeth ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9979b697
<p style="margin-left: 10px"><strong>variableName: </strong>datemeth
</details>
<details style="margin-left: 10px">
<summary>resevoirCorr ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD257214a7
<p style="margin-left: 10px"><strong>variableName: </strong>resevoirCorr
</details>
<details style="margin-left: 10px">
<summary>delta_R ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD80155fb9
<p style="margin-left: 10px"><strong>variableName: </strong>delta_R
</details>
<details style="margin-left: 10px">
<summary>delta_Rsig ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe86e42a4
<p style="margin-left: 10px"><strong>variableName: </strong>delta_Rsig
</details>
<details style="margin-left: 10px">
<summary>calib_14Cage ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD3x82ylur
<p style="margin-left: 10px"><strong>variableName: </strong>calib_14Cage
</details>
<details style="margin-left: 10px">
<summary>calib_14Cage_1sig ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDzp38wlxd
<p style="margin-left: 10px"><strong>variableName: </strong>calib_14Cage_1sig
</details>
<details style="margin-left: 10px">
<summary>calib_method ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDw2in4ajx
<p style="margin-left: 10px"><strong>variableName: </strong>calib_method
</details>
<details style="margin-left: 10px">
<summary>rejected ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDkdyxrfdk
<p style="margin-left: 10px"><strong>variableName: </strong>rejected
</details>
<details style="margin-left: 10px">
<summary>notes ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDk9l5fc9g
<p style="margin-left: 10px"><strong>variableName: </strong>notes
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 8)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 9)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 10)
```

### Uk37 (missing)
```{r}
plotCol(thisTS,ind = 1)
```

### TEX86 (missing)
```{r}
plotCol(thisTS,ind = 5)
```

### Mg/Ca (mmol/mol)
```{r}
plotCol(thisTS,ind = 6)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 7)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### labCode ()
```{r}
plotCol(chronTS,ind = 1)
```

### depth_2 (cm)
```{r}
plotCol(chronTS,ind = 3)
```

### MaterialDated ()
```{r}
plotCol(chronTS,ind = 4)
```

### age14C ()
```{r}
plotCol(chronTS,ind = 5)
```

### age14Cuncertainty ()
```{r}
plotCol(chronTS,ind = 6)
```

### datemeth ()
```{r}
plotCol(chronTS,ind = 7)
```

### resevoirCorr ()
```{r}
plotCol(chronTS,ind = 8)
```

### delta_R ()
```{r}
plotCol(chronTS,ind = 9)
```

### delta_Rsig ()
```{r}
plotCol(chronTS,ind = 10)
```

### calib_14Cage ()
```{r}
plotCol(chronTS,ind = 11)
```

### calib_14Cage_1sig ()
```{r}
plotCol(chronTS,ind = 12)
```

### calib_method ()
```{r}
plotCol(chronTS,ind = 13)
```

### rejected ()
```{r}
plotCol(chronTS,ind = 14)
```

### notes ()
```{r}
plotCol(chronTS,ind = 15)
```
