---
title: "Sofular.Fleitmann.2009"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 764
thisTS <- TS[which(udsn[i] == dsn)]
```
#Sofular.Fleitmann.2009

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](Sofular.Fleitmann.2009.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/Sofular.Fleitmann.2009.lpd)
            

[Download paleoData only (csv)](Sofular.Fleitmann.2009.csv)
            

[Download chronData only (csv)](Sofular.Fleitmann.2009-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>Speleothem
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/8637
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Fleitmann, D."), list(name = "Cheng, H."), list(name = "Badertscher, S."), list(name = "Edwards, R. L."), list(name = "Mudelsee, M."), list(name = "Goektuerk, O. M."), list(name = "Fankhauser, A."), list(name = "Pickering, R."), list(name = "Raible, C. C."), list(name = "Matter, A."), list(name = "Kramers, J."), list(name = "Tueysuez, O."))
<p style="margin-left: 10px"><strong>citeKey: </strong>needs0needsatitle
<p style="margin-left: 10px"><strong>journal: </strong>Geophysical Research Letters
<p style="margin-left: 10px"><strong>volume: </strong>36
<p style="margin-left: 10px"><strong>title: </strong>Timing and climatic impact of Greenland interstadials recorded in stalagmites from northern Turkey
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>41.4167
<p style="margin-left: 0px"><strong>longitude: </strong>31.9333
<p style="margin-left: 0px"><strong>elevation: </strong>700
<p style="margin-left: 0px"><strong>siteName: </strong>Sofular
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RfKNNpATe7R
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RzcH5qa2Qyr
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>d18O (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD38727801
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>M
<p style="margin-left: 20px"><strong>variableDetail: </strong>monsoon
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d13C (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD6a56b896
<p style="margin-left: 10px"><strong>variableName: </strong>d13C
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>description: </strong>Stable isotope (carbon and oxygen) of stalagmite So-1 from Sofular Cave, Northern Turkey. 230Th dating of stalagmite So-1 was made on a multi-collector inductively coupled plasma mass spectrometer (MC-ICP-MS, Thermo-Finnigan-Neptune) at the Minnesota Isotope Laboratory, University of Minnesota (auxiliary material Table A1). Further 230Th dating on all stalagmites was done on a Nu Instruments MC-ICP-MS at the Geological Institute, University of Bern. Stable isotope analyses were performed on a Finnigan Delta V Advantage mass spectrometer equipped with an automated carbonate preparation system (Gas Bench-II) at the Institute of Geological Sciences, University of Bern. Precision of d13C and d18O measurements is 0.06     and 0.07     (1s-error) respectively.
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (mm) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDb77df97e
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>age (kyr BP) [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDbd27c3a4
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>kyr BP
</details>
<details style="margin-left: 10px">
<summary>sample () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf03dc5de
<p style="margin-left: 10px"><strong>variableName: </strong>sample
</details>
<details style="margin-left: 10px">
<summary>238U () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDc879552b
<p style="margin-left: 10px"><strong>variableName: </strong>238U
</details>
<details style="margin-left: 10px">
<summary>238err () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD6902fbeb
<p style="margin-left: 10px"><strong>variableName: </strong>238err
</details>
<details style="margin-left: 10px">
<summary>232TH () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD89864ee7
<p style="margin-left: 10px"><strong>variableName: </strong>232TH
</details>
<details style="margin-left: 10px">
<summary>232err () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD77c07caa
<p style="margin-left: 10px"><strong>variableName: </strong>232err
</details>
<details style="margin-left: 10px">
<summary>230TH/232Th () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDc73e9bd9
<p style="margin-left: 10px"><strong>variableName: </strong>230TH/232Th
</details>
<details style="margin-left: 10px">
<summary>230TH/232Th_err () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD69a0b04b
<p style="margin-left: 10px"><strong>variableName: </strong>230TH/232Th_err
</details>
<details style="margin-left: 10px">
<summary>d234U () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7036bc40
<p style="margin-left: 10px"><strong>variableName: </strong>d234U
</details>
<details style="margin-left: 10px">
<summary>d234U_err () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf7264792
<p style="margin-left: 10px"><strong>variableName: </strong>d234U_err
</details>
<details style="margin-left: 10px">
<summary>230Th/238U () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD082e762d
<p style="margin-left: 10px"><strong>variableName: </strong>230Th/238U
</details>
<details style="margin-left: 10px">
<summary>230Th/238U_err () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd15a2565
<p style="margin-left: 10px"><strong>variableName: </strong>230Th/238U_err
</details>
<details style="margin-left: 10px">
<summary>age_uncorrected () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe23f7b13
<p style="margin-left: 10px"><strong>variableName: </strong>age_uncorrected
</details>
<details style="margin-left: 10px">
<summary>age_uncorrected_err () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD75f9242b
<p style="margin-left: 10px"><strong>variableName: </strong>age_uncorrected_err
</details>
<details style="margin-left: 10px">
<summary>err () [1-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa5f4a279
<p style="margin-left: 10px"><strong>variableName: </strong>err
</details>
<details style="margin-left: 10px">
<summary>depth (mm) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD539b712a
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>mm
</details>
<details style="margin-left: 10px">
<summary>age (kyr BP) [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDe1bb2f34
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>kyr BP
</details>
<details style="margin-left: 10px">
<summary>sample () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD18469f04
<p style="margin-left: 10px"><strong>variableName: </strong>sample
</details>
<details style="margin-left: 10px">
<summary>c(Th) () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5dfb0b5c
<p style="margin-left: 10px"><strong>variableName: </strong>c(Th)
</details>
<details style="margin-left: 10px">
<summary>c(Th)_err () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD292c3327
<p style="margin-left: 10px"><strong>variableName: </strong>c(Th)_err
</details>
<details style="margin-left: 10px">
<summary>c(U) () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd8717af6
<p style="margin-left: 10px"><strong>variableName: </strong>c(U)
</details>
<details style="margin-left: 10px">
<summary>c(U)_err () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD14fdbbfe
<p style="margin-left: 10px"><strong>variableName: </strong>c(U)_err
</details>
<details style="margin-left: 10px">
<summary>234U/238U () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9ec9d258
<p style="margin-left: 10px"><strong>variableName: </strong>234U/238U
</details>
<details style="margin-left: 10px">
<summary>234U/238U_err () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD64e5d3d5
<p style="margin-left: 10px"><strong>variableName: </strong>234U/238U_err
</details>
<details style="margin-left: 10px">
<summary>230Th/232Th () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD066de475
<p style="margin-left: 10px"><strong>variableName: </strong>230Th/232Th
</details>
<details style="margin-left: 10px">
<summary>230Th/232Th_err () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD8ba1eb72
<p style="margin-left: 10px"><strong>variableName: </strong>230Th/232Th_err
</details>
<details style="margin-left: 10px">
<summary>230Th/234U () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7077168d
<p style="margin-left: 10px"><strong>variableName: </strong>230Th/234U
</details>
<details style="margin-left: 10px">
<summary>230Th/234U_err () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDbbd45f21
<p style="margin-left: 10px"><strong>variableName: </strong>230Th/234U_err
</details>
<details style="margin-left: 10px">
<summary>err () [2-1]</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD84b7b15e
<p style="margin-left: 10px"><strong>variableName: </strong>err
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O (missing)
```{r}
plotCol(thisTS,ind = 4)
```

### d13C (missing)
```{r}
plotCol(thisTS,ind = 1)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (mm) [1-1]
```{r}
plotCol(chronTS,ind = 2)
```

### age (kyr BP) [1-1]
```{r}
plotCol(chronTS,ind = 15)
```

### sample () [1-1]
```{r}
plotCol(chronTS,ind = 1)
```

### 238U () [1-1]
```{r}
plotCol(chronTS,ind = 3)
```

### 238err () [1-1]
```{r}
plotCol(chronTS,ind = 4)
```

### 232TH () [1-1]
```{r}
plotCol(chronTS,ind = 5)
```

### 232err () [1-1]
```{r}
plotCol(chronTS,ind = 6)
```

### 230TH/232Th () [1-1]
```{r}
plotCol(chronTS,ind = 7)
```

### 230TH/232Th_err () [1-1]
```{r}
plotCol(chronTS,ind = 8)
```

### d234U () [1-1]
```{r}
plotCol(chronTS,ind = 9)
```

### d234U_err () [1-1]
```{r}
plotCol(chronTS,ind = 10)
```

### 230Th/238U () [1-1]
```{r}
plotCol(chronTS,ind = 11)
```

### 230Th/238U_err () [1-1]
```{r}
plotCol(chronTS,ind = 12)
```

### age_uncorrected () [1-1]
```{r}
plotCol(chronTS,ind = 13)
```

### age_uncorrected_err () [1-1]
```{r}
plotCol(chronTS,ind = 14)
```

### err () [1-1]
```{r}
plotCol(chronTS,ind = 16)
```

### depth (mm) [2-1]
```{r}
plotCol(chronTS,ind = 18)
```

### age (kyr BP) [2-1]
```{r}
plotCol(chronTS,ind = 29)
```

### sample () [2-1]
```{r}
plotCol(chronTS,ind = 17)
```

### c(Th) () [2-1]
```{r}
plotCol(chronTS,ind = 19)
```

### c(Th)_err () [2-1]
```{r}
plotCol(chronTS,ind = 20)
```

### c(U) () [2-1]
```{r}
plotCol(chronTS,ind = 21)
```

### c(U)_err () [2-1]
```{r}
plotCol(chronTS,ind = 22)
```

### 234U/238U () [2-1]
```{r}
plotCol(chronTS,ind = 23)
```

### 234U/238U_err () [2-1]
```{r}
plotCol(chronTS,ind = 24)
```

### 230Th/232Th () [2-1]
```{r}
plotCol(chronTS,ind = 25)
```

### 230Th/232Th_err () [2-1]
```{r}
plotCol(chronTS,ind = 26)
```

### 230Th/234U () [2-1]
```{r}
plotCol(chronTS,ind = 27)
```

### 230Th/234U_err () [2-1]
```{r}
plotCol(chronTS,ind = 28)
```

### err () [2-1]
```{r}
plotCol(chronTS,ind = 30)
```
