---
title: "WhitePond.Krause.2019"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 864
thisTS <- TS[which(udsn[i] == dsn)]
```
#WhitePond.Krause.2019

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](WhitePond.Krause.2019.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/WhitePond.Krause.2019.lpd)
            

[Download paleoData only (csv)](WhitePond.Krause.2019.csv)
            

[Download chronData only (csv)](WhitePond.Krause.2019-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>LakeSediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Krause, Teresa R."), list(name = "Russell, James M."), list(name = "Zhang, Rui"), list(name = "Williams, John W."), list(name = "Jackson, Stephen T."))
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary Research
<p style="margin-left: 10px"><strong>volume: </strong>91
<p style="margin-left: 10px"><strong>pages: </strong>861-880
<p style="margin-left: 10px"><strong>title: </strong>Late Quaternary vegetation, climate, and fire history of the Southeast Atlantic Coastal Plain based on a 30,000-yr multi-proxy record from White Pond, South Carolina, USA
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>34.168
<p style="margin-left: 0px"><strong>longitude: </strong>-80.7767
<p style="margin-left: 0px"><strong>elevation: </strong>1.5
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB0c66b35b
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB879b43f4
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
</details>
<details style="margin-left: 10px">
<summary>soilTemp (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB7ed46879
<p style="margin-left: 10px"><strong>variableName: </strong>soilTemp
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>soil@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MBT_temp (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1f75199d
<p style="margin-left: 10px"><strong>variableName: </strong>MBT_temp
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>brGDGT (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB01d81cae
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGT
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>description: </strong>m/z 1292
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGTIIIa (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB8f6b7fbe
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGTIIIa
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGTIIIb (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB6e9ae6d9
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGTIIIb
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGT (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB7df5f154
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGT
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGTIia (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB18a35b4b
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGTIia
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGTIib (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB29094b2a
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGTIib
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGT (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBb544332e
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGT
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGTIa (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB00b8ca8d
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGTIa
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGTIb (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBda8d7b6b
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGTIb
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>brGDGT (peak area)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB2de78c22
<p style="margin-left: 10px"><strong>variableName: </strong>brGDGT
<p style="margin-left: 10px"><strong>units: </strong>peak area
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>BIT (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBc05e76b2
<p style="margin-left: 10px"><strong>variableName: </strong>BIT
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MBT (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB28096758
<p style="margin-left: 10px"><strong>variableName: </strong>MBT
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>MBT' (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB556eb778
<p style="margin-left: 10px"><strong>variableName: </strong>MBT'
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>CBT (missing)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB37d64008
<p style="margin-left: 10px"><strong>variableName: </strong>CBT
<p style="margin-left: 10px"><strong>units: </strong>missing
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details style="margin-left: 10px">
<summary>pH (pH)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBceaccb17
<p style="margin-left: 10px"><strong>variableName: </strong>pH
<p style="margin-left: 10px"><strong>units: </strong>pH
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBcb0ef664
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
</details>
<details style="margin-left: 10px">
<summary>age (yr bp)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB4275f484
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr bp
</details>
<details style="margin-left: 10px">
<summary>error (yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB539c4f88
<p style="margin-left: 10px"><strong>variableName: </strong>error
<p style="margin-left: 10px"><strong>units: </strong>yr
</details>
<details style="margin-left: 10px">
<summary>labId (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEB1b240a7c
<p style="margin-left: 10px"><strong>variableName: </strong>labId
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>material (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>WEBec47cdfc
<p style="margin-left: 10px"><strong>variableName: </strong>material
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### soilTemp (degC)
```{r}
plotCol(thisTS,ind = 17)
```

### MBT_temp (degC)
```{r}
plotCol(thisTS,ind = 18)
```

### brGDGT (peak area)
```{r}
plotCol(thisTS,ind = 3)
```

### brGDGTIIIa (peak area)
```{r}
plotCol(thisTS,ind = 4)
```

### brGDGTIIIb (peak area)
```{r}
plotCol(thisTS,ind = 5)
```

### brGDGT (peak area)
```{r}
plotCol(thisTS,ind = 6)
```

### brGDGTIia (peak area)
```{r}
plotCol(thisTS,ind = 7)
```

### brGDGTIib (peak area)
```{r}
plotCol(thisTS,ind = 8)
```

### brGDGT (peak area)
```{r}
plotCol(thisTS,ind = 9)
```

### brGDGTIa (peak area)
```{r}
plotCol(thisTS,ind = 10)
```

### brGDGTIb (peak area)
```{r}
plotCol(thisTS,ind = 11)
```

### brGDGT (peak area)
```{r}
plotCol(thisTS,ind = 12)
```

### BIT (missing)
```{r}
plotCol(thisTS,ind = 13)
```

### MBT (missing)
```{r}
plotCol(thisTS,ind = 14)
```

### MBT' (missing)
```{r}
plotCol(thisTS,ind = 15)
```

### CBT (missing)
```{r}
plotCol(thisTS,ind = 16)
```

### pH (pH)
```{r}
plotCol(thisTS,ind = 19)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth (cm)
```{r}
plotCol(chronTS,ind = 1)
```

### age (yr bp)
```{r}
plotCol(chronTS,ind = 2)
```

### error (yr)
```{r}
plotCol(chronTS,ind = 3)
```

### labId (unitless)
```{r}
plotCol(chronTS,ind = 4)
```

### material (unitless)
```{r}
plotCol(chronTS,ind = 5)
```
