---
title: "YakYakumo.Leipe.2013"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 869
thisTS <- TS[which(udsn[i] == dsn)]
```
#YakYakumo.Leipe.2013

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](YakYakumo.Leipe.2013.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/globalHolocene/0_25_5/YakYakumo.Leipe.2013.lpd)
            

[Download paleoData only (csv)](YakYakumo.Leipe.2013.csv)
            

[Download chronData only (csv)](YakYakumo.Leipe.2013-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>LakeSediment
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://doi.org/10.1594/PANGAEA.785354
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Leipe, Christian"), list(name = "Kito, Norio"), list(name = "Sakaguchi, Yumi"), list(name = "Tarasov, Pavel E."))
<p style="margin-left: 10px"><strong>citeKey: </strong>needs0needsatitle
<p style="margin-left: 10px"><strong>journal: </strong>Quaternary International
<p style="margin-left: 10px"><strong>volume: </strong>290-291
<p style="margin-left: 10px"><strong>title: </strong>Vegetation and climate history of northern Japan inferred from the 5500-year pollen record from the Oshima Peninsula, SW Hokkaido
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = NA))
</details>
</details>
<details>
<summary>funding</summary>
<details style="margin-left: 10px">
<summary>funding1</summary>
<p style="margin-left: 10px"><strong>agency: </strong>Funding Agency
<p style="margin-left: 10px"><strong>grant: </strong>Grant name or number
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>42.2842
<p style="margin-left: 0px"><strong>longitude: </strong>140.2594
<p style="margin-left: 0px"><strong>elevation: </strong>0
<p style="margin-left: 0px"><strong>siteName: </strong>Yak Yakumo
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RdAj8eit3pF
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RGw8PLfQTHy
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Years before present (1950) BP
</details>
<details style="margin-left: 10px">
<summary>depth (m)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RnhcafXi4AQ
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>m
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>WMTmin (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5c7dbad2
<p style="margin-left: 10px"><strong>variableName: </strong>WMTmin
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, warmest month, minimum [   C] (WMT min) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>warmest
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>WMT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD274a3399
<p style="margin-left: 10px"><strong>variableName: </strong>WMT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, warmest month [   C] (WMT) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>warmest
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>WMTmax (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDffbd62c9
<p style="margin-left: 10px"><strong>variableName: </strong>WMTmax
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, warmest month, maximum [   C] (WMT max) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>warmest
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>CMTmin (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDfcf2b497
<p style="margin-left: 10px"><strong>variableName: </strong>CMTmin
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, coldest month, minimum [   C] (CMT min) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>coldest
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>CMT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7e71c684
<p style="margin-left: 10px"><strong>variableName: </strong>CMT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, coldest month [   C] (CMT) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>coldest
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>CMTmax (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9d98e500
<p style="margin-left: 10px"><strong>variableName: </strong>CMTmax
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, coldest month, maximum [   C] (CMT max) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>coldest
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MATmin (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDcfb4b1ec
<p style="margin-left: 10px"><strong>variableName: </strong>MATmin
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, annual mean, minimum [   C] (MAT min) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MAT (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD27f34021
<p style="margin-left: 10px"><strong>variableName: </strong>MAT
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, annual mean [   C] (MAT) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>MATmax (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDb18c1a76
<p style="margin-left: 10px"><strong>variableName: </strong>MATmax
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>Temperature, annual mean, maximum [   C] (MAT max) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>variableDetail: </strong>air@surface
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD9f23e117
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, Apr-Sep, minimum [mm] (Precip (4-9) min) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD016736e6
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, Apr-Sep [mm] (Precip (4-9)) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD735df7eb
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, Apr-Sep, maximum [mm] (Precip (4-9) max) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>Summer
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD20c83aad
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, Oct-Mar, minimum [mm] (Precip (10-3) min) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD55404d27
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, Oct-Mar [mm] (Precip (10-3)) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD1df53edc
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, Oct-Mar, maximum [mm] (Precip (10-3) max) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>winter
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm/yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD8777d218
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm/yr
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean, minimum [mm] (MAP min) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm/yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD72217804
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm/yr
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean [mm] (MAP) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>precipitation (mm/yr)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD50ad7cf7
<p style="margin-left: 10px"><strong>variableName: </strong>precipitation
<p style="margin-left: 10px"><strong>units: </strong>mm/yr
<p style="margin-left: 10px"><strong>description: </strong>Precipitation, annual mean, maximum [mm] (MAP max) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>M
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Analogues# (#)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf733bfd6
<p style="margin-left: 10px"><strong>variableName: </strong>Analogues#
<p style="margin-left: 10px"><strong>units: </strong>#
<p style="margin-left: 10px"><strong>description: </strong>Number of analogues [#] (Analogues) * PI: Tarasov, Pavel E (ptarasov@zedat.fu-berlin.de, http://www.geo.fu-berlin.de/geol/fachrichtungen/pal/mitarbeiter/tarasov/index.html) * METHOD: Modern analog technique (MAT)
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>FALSE
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>age ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf7b869a3
<p style="margin-left: 10px"><strong>variableName: </strong>age
</details>
<details style="margin-left: 10px">
<summary>dummy2 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7fef9670
<p style="margin-left: 10px"><strong>variableName: </strong>dummy2
</details>
<details style="margin-left: 10px">
<summary>dummy3 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD5c97ef87
<p style="margin-left: 10px"><strong>variableName: </strong>dummy3
</details>
<details style="margin-left: 10px">
<summary>dummy4 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDc2db7577
<p style="margin-left: 10px"><strong>variableName: </strong>dummy4
</details>
<details style="margin-left: 10px">
<summary>dummy5 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD303fc074
<p style="margin-left: 10px"><strong>variableName: </strong>dummy5
</details>
<details style="margin-left: 10px">
<summary>dummy6 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD870d83fe
<p style="margin-left: 10px"><strong>variableName: </strong>dummy6
</details>
<details style="margin-left: 10px">
<summary>dummy7 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD96ee0145
<p style="margin-left: 10px"><strong>variableName: </strong>dummy7
</details>
<details style="margin-left: 10px">
<summary>dummy8 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDd04b1d27
<p style="margin-left: 10px"><strong>variableName: </strong>dummy8
</details>
<details style="margin-left: 10px">
<summary>dummy9 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD47f2d890
<p style="margin-left: 10px"><strong>variableName: </strong>dummy9
</details>
<details style="margin-left: 10px">
<summary>dummy10 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD8b7f8018
<p style="margin-left: 10px"><strong>variableName: </strong>dummy10
</details>
<details style="margin-left: 10px">
<summary>dummy11 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD27911017
<p style="margin-left: 10px"><strong>variableName: </strong>dummy11
</details>
<details style="margin-left: 10px">
<summary>dummy12 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7d4d60b2
<p style="margin-left: 10px"><strong>variableName: </strong>dummy12
</details>
<details style="margin-left: 10px">
<summary>dummy13 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD07ca5727
<p style="margin-left: 10px"><strong>variableName: </strong>dummy13
</details>
<details style="margin-left: 10px">
<summary>dummy14 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD3a637241
<p style="margin-left: 10px"><strong>variableName: </strong>dummy14
</details>
<details style="margin-left: 10px">
<summary>dummy15 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD6d969952
<p style="margin-left: 10px"><strong>variableName: </strong>dummy15
</details>
<details style="margin-left: 10px">
<summary>dummy16 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDf8f7ec80
<p style="margin-left: 10px"><strong>variableName: </strong>dummy16
</details>
<details style="margin-left: 10px">
<summary>dummy17 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD47ee97d6
<p style="margin-left: 10px"><strong>variableName: </strong>dummy17
</details>
<details style="margin-left: 10px">
<summary>dummy18 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDa52707f3
<p style="margin-left: 10px"><strong>variableName: </strong>dummy18
</details>
<details style="margin-left: 10px">
<summary>dummy19 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD076fab18
<p style="margin-left: 10px"><strong>variableName: </strong>dummy19
</details>
<details style="margin-left: 10px">
<summary>dummy20 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPDea75fb56
<p style="margin-left: 10px"><strong>variableName: </strong>dummy20
</details>
<details style="margin-left: 10px">
<summary>dummy21 ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LPD7b69fd64
<p style="margin-left: 10px"><strong>variableName: </strong>dummy21
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### WMTmin (degC)
```{r}
plotCol(thisTS,ind = 1)
```

### WMT (degC)
```{r}
plotCol(thisTS,ind = 5)
```

### WMTmax (degC)
```{r}
plotCol(thisTS,ind = 6)
```

### CMTmin (degC)
```{r}
plotCol(thisTS,ind = 7)
```

### CMT (degC)
```{r}
plotCol(thisTS,ind = 8)
```

### CMTmax (degC)
```{r}
plotCol(thisTS,ind = 9)
```

### MATmin (degC)
```{r}
plotCol(thisTS,ind = 10)
```

### MAT (degC)
```{r}
plotCol(thisTS,ind = 11)
```

### MATmax (degC)
```{r}
plotCol(thisTS,ind = 12)
```

### precipitation (mm)
```{r}
plotCol(thisTS,ind = 13)
```

### precipitation (mm)
```{r}
plotCol(thisTS,ind = 14)
```

### precipitation (mm)
```{r}
plotCol(thisTS,ind = 15)
```

### precipitation (mm)
```{r}
plotCol(thisTS,ind = 16)
```

### precipitation (mm)
```{r}
plotCol(thisTS,ind = 17)
```

### precipitation (mm)
```{r}
plotCol(thisTS,ind = 18)
```

### precipitation (mm/yr)
```{r}
plotCol(thisTS,ind = 19)
```

### precipitation (mm/yr)
```{r}
plotCol(thisTS,ind = 20)
```

### precipitation (mm/yr)
```{r}
plotCol(thisTS,ind = 21)
```

### Analogues# (#)
```{r}
plotCol(thisTS,ind = 22)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### age ()
```{r}
plotCol(chronTS,ind = 1)
```

### dummy2 ()
```{r}
plotCol(chronTS,ind = 2)
```

### dummy3 ()
```{r}
plotCol(chronTS,ind = 3)
```

### dummy4 ()
```{r}
plotCol(chronTS,ind = 4)
```

### dummy5 ()
```{r}
plotCol(chronTS,ind = 5)
```

### dummy6 ()
```{r}
plotCol(chronTS,ind = 6)
```

### dummy7 ()
```{r}
plotCol(chronTS,ind = 7)
```

### dummy8 ()
```{r}
plotCol(chronTS,ind = 8)
```

### dummy9 ()
```{r}
plotCol(chronTS,ind = 9)
```

### dummy10 ()
```{r}
plotCol(chronTS,ind = 10)
```

### dummy11 ()
```{r}
plotCol(chronTS,ind = 11)
```

### dummy12 ()
```{r}
plotCol(chronTS,ind = 12)
```

### dummy13 ()
```{r}
plotCol(chronTS,ind = 13)
```

### dummy14 ()
```{r}
plotCol(chronTS,ind = 14)
```

### dummy15 ()
```{r}
plotCol(chronTS,ind = 15)
```

### dummy16 ()
```{r}
plotCol(chronTS,ind = 16)
```

### dummy17 ()
```{r}
plotCol(chronTS,ind = 17)
```

### dummy18 ()
```{r}
plotCol(chronTS,ind = 18)
```

### dummy19 ()
```{r}
plotCol(chronTS,ind = 19)
```

### dummy20 ()
```{r}
plotCol(chronTS,ind = 20)
```

### dummy21 ()
```{r}
plotCol(chronTS,ind = 21)
```
