---
title: "LS06TIST"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 275
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS06TIST

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS06TIST.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/iso2kv0_11_0/LS06TIST.lpd)
            

[Download data only (csv)](LS06TIST.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Tian, Jian , Nelson, David M. , Hu, Feng Sheng
<p style="margin-left: 10px"><strong>journal: </strong>Geophys. Res. Lett.
<p style="margin-left: 10px"><strong>volume: </strong>33
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Possible linkages of late-Holocene drought in the North American midcontinent to Pacific Decadal Oscillation and solar activity
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2006GL028169
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>46
<p style="margin-left: 0px"><strong>longitude: </strong>-94.7
<p style="margin-left: 0px"><strong>elevation: </strong>415
<p style="margin-left: 0px"><strong>siteName: </strong>Steel
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATf47550ae7d
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATf6335d8d19
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS06TIST
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The d18O record of the past 3100 years reveals that droughts of greater severity and duration than during the 20th century occurred repeatedly, especially prior to 300 AD. Drought variability was anomalously low during the 20th century; 90% of the variability values during the last 3100 years were greater than the 20th-century average. d18O is strongly correlated with the index of the Pacific Decadal Oscillation (PDO) during the past 100 years, and periodicities of the late- Holocene d18O record are similar to those of the PDO. Furthermore, time series of d18O and atmospheric D14C are generally coherent after 700 AD. Both the Pacific climate and solar irradiance probably played a role in drought occurrence, but their effects were non-stationary through the late Holocene.;a highly significant, positive correlation (r = 0.63, n = 32, p < 0.0001) exists between d18O and the PDO. This pattern can be explained by the negative correlation of the PDO with measured winter (r = 0.44, n = 103, p < 0.001) and summer (r = 0.35, n = 103, p < 0.001) precipitation near Steel Lake. Dry winters likely decrease the proportion of 18O-depleted winter precipitation entering the lake, and dry summers enhance evaporative 18O-enrichment of lake watea highly significant, positive correlation (r = 0.63, n = 32, p < 0.0001) exists between d18O and the PDO. This pattern can be explained by the negative correlation of the PDO with measured winter (r = 0.44, n = 103, p < 0.001) and summer (r = 0.35, n = 103, p < 0.001) precipitation near Steel Lake. Dry winters likely decrease the proportion of 18O-depleted winter precipitation entering the lake, and dry summers enhance evaporative 18O-enrichment of lake wate
<p style="margin-left: 20px"><strong>interpDirection: </strong>positive
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variable: </strong>PDO
<p style="margin-left: 20px"><strong>variableDetail: </strong>lake water
<p style="margin-left: 20px"><strong>direction: </strong>positive
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>However, two lines of evidence indicate that at Steel Lake, evaporative 18O enrichment related to aridity was the dominant control. First, the d18O values of water samples from the epilimnion and hypolimnion of Steel Lake were 8.7 and 10.7%, respectively, in July 2001 (Figure 1d). The elevated d18O value of the epilimnetic water resulted from evaporative 18O enrichment, suggesting that Steel  Lake is sensitive to evaporation;In particular, the most severe historic drought events in north-central Minnesota, the 1988 drought [Trenberth et al., 1988] and 1930s Dust Bowl [Worster, 1979], are recorded by the heaviest d18O values at Steel Lake
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>lake water
<p style="margin-left: 20px"><strong>integrationTime: </strong>5
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>varve counts
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>sampling resoluton
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>P_E
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O (permil)
```{r}
plotCol(thisTS,ind = 1)
```
