---
title: "LS13WASU"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 323
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS13WASU

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS13WASU.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/iso2kv0_11_0/LS13WASU.lpd)
            

[Download data only (csv)](LS13WASU.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Wang, Z. , Liu, W. , Liu, Z. , Wang, H. , He, Y. , Zhang, F.
<p style="margin-left: 10px"><strong>journal: </strong>The Holocene
<p style="margin-left: 10px"><strong>volume: </strong>23
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>A 1700-year n-alkanes hydrogen isotope record of moisture changes in sediments from Lake Sugan in the Qaidam Basin, northeastern Tibetan Plateau
<p style="margin-left: 10px"><strong>DOI: </strong>10.1177/0959683613486941
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>38.8667
<p style="margin-left: 0px"><strong>longitude: </strong>93.95
<p style="margin-left: 0px"><strong>elevation: </strong>2800
<p style="margin-left: 0px"><strong>siteName: </strong>Lake Sugan
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT7cbe87ad3a
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT0bb768872a
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS13WASU01B
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The effective moisture (ratio of precipitation to evaporation) is considered as the main factor controlling the ?D values of lipid n-alkanes in terrestrial plants (Polissar and Freeman, 2010). In a previous study, the ?D record from a loess profile in the Chinese Loess Plateau displayed a strong correlation to changes in the magnetic susceptibility (MS) over the past 130 ka, and the isoto- pic variation was thought to be strongly affected by aridity (Liu and Huang, 2005). Furthermore, a humidity control experiment in the field verified the correlation between D enrichment and rela- tive humidity (McInerney et al., 2011). A study of lipids from the Santa Barbara Basin from the past 1400 years also revealed the ?D of mid-chain acids to be partially correlated with existing data of drought severity (Li et al., 2011).
<p style="margin-left: 20px"><strong>interpDirection: </strong>increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season? (not stated)
<p style="margin-left: 20px"><strong>variable: </strong>P/E
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
<p style="margin-left: 20px"><strong>direction: </strong>increase
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The effective moisture (ratio of precipitation to evaporation) is considered as the main factor controlling the ?D values of lipid n-alkanes in terrestrial plants (Polissar and Freeman, 2010). In a previous study, the ?D record from a loess profile in the Chinese Loess Plateau displayed a strong correlation to changes in the magnetic susceptibility (MS) over the past 130 ka, and the isoto- pic variation was thought to be strongly affected by aridity (Liu and Huang, 2005). Furthermore, a humidity control experiment in the field verified the correlation between D enrichment and rela- tive humidity (McInerney et al., 2011). A study of lipids from the Santa Barbara Basin from the past 1400 years also revealed the ?D of mid-chain acids to be partially correlated with existing data of drought severity (Li et al., 2011).
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season? (not stated)
<p style="margin-left: 20px"><strong>variable: </strong>P_E
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Therefore, we suggest that the variation in vegetation type (shrubs and grass) is also the predominant factor influencing the [d2H of leaf waxes in] sediments of Lake Sugan, because of the ?D values of Chenopodiceae shrubs are higher than those of grasses. We can still discuss the moisture history using the hydrogen-isotope record, at least quantitatively, because the vegetation type would be consistent with hydrological condition. [i.e., Chenopodiaceae shrubs tend to be more abundant in dry climates, and Chenopodiaceae shrubs have a smaller apparent fractionation, so dry climates would not only cause greater evaporative enrichment of plant source water, but more leaf waxes with relatively enriched d2H would be produced by Chenopodiaceae shrubs.]
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season? (not stated)
<p style="margin-left: 20px"><strong>variable: </strong>vegetation type (Chenopodiaceae shrub abundance)
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS13WASU01A
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The effective moisture (ratio of precipitation to evaporation) is considered as the main factor controlling the ?D values of lipid n-alkanes in terrestrial plants (Polissar and Freeman, 2010). In a previous study, the ?D record from a loess profile in the Chinese Loess Plateau displayed a strong correlation to changes in the magnetic susceptibility (MS) over the past 130 ka, and the isoto- pic variation was thought to be strongly affected by aridity (Liu and Huang, 2005). Furthermore, a humidity control experiment in the field verified the correlation between D enrichment and rela- tive humidity (McInerney et al., 2011). A study of lipids from the Santa Barbara Basin from the past 1400 years also revealed the ?D of mid-chain acids to be partially correlated with existing data of drought severity (Li et al., 2011).
<p style="margin-left: 20px"><strong>interpDirection: </strong>increase
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season? (not stated)
<p style="margin-left: 20px"><strong>variable: </strong>P/E
<p style="margin-left: 20px"><strong>variableDetail: </strong>air
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>The effective moisture (ratio of precipitation to evaporation) is considered as the main factor controlling the ?D values of lipid n-alkanes in terrestrial plants (Polissar and Freeman, 2010). In a previous study, the ?D record from a loess profile in the Chinese Loess Plateau displayed a strong correlation to changes in the magnetic susceptibility (MS) over the past 130 ka, and the isoto- pic variation was thought to be strongly affected by aridity (Liu and Huang, 2005). Furthermore, a humidity control experiment in the field verified the correlation between D enrichment and rela- tive humidity (McInerney et al., 2011). A study of lipids from the Santa Barbara Basin from the past 1400 years also revealed the ?D of mid-chain acids to be partially correlated with existing data of drought severity (Li et al., 2011).
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season? (not stated)
<p style="margin-left: 20px"><strong>variable: </strong>P_E
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Therefore, we suggest that the variation in vegetation type (shrubs and grass) is also the predominant factor influencing the [d2H of leaf waxes in] sediments of Lake Sugan, because of the ?D values of Chenopodiceae shrubs are higher than those of grasses. We can still discuss the moisture history using the hydrogen-isotope record, at least quantitatively, because the vegetation type would be consistent with hydrological condition. [i.e., Chenopodiaceae shrubs tend to be more abundant in dry climates, and Chenopodiaceae shrubs have a smaller apparent fractionation, so dry climates would not only cause greater evaporative enrichment of plant source water, but more leaf waxes with relatively enriched d2H would be produced by Chenopodiaceae shrubs.]
<p style="margin-left: 20px"><strong>direction: </strong>increase
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>growing season? (not stated)
<p style="margin-left: 20px"><strong>variable: </strong>vegetation type (Chenopodiaceae shrub abundance)
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD (permil)
```{r}
plotCol(thisTS,ind = 1)
```

### dD (permil)
```{r}
plotCol(thisTS,ind = 4)
```
