---
title: "LS14FOTI"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 327
thisTS <- TS[which(udsn[i] == dsn)]
```
#LS14FOTI

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](LS14FOTI.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/iso2kv0_11_0/LS14FOTI.lpd)
            

[Download data only (csv)](LS14FOTI.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>lake sediment
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Fornace, Kyrstin L. , Hughen, Konrad A. , Shanahan, Timothy M. , Fritz, Sherilyn C. , Baker, Paul A. , Sylva, Sean P.
<p style="margin-left: 10px"><strong>journal: </strong>Earth and Planetary Science Letters
<p style="margin-left: 10px"><strong>volume: </strong>408
<p style="margin-left: 10px"><strong>pages: </strong>-8
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>A 60,000-year record of hydrologic variability in the Central Andes from the hydrogen isotopic composition of leaf waxes in Lake Titicaca sediments
<p style="margin-left: 10px"><strong>DOI: </strong>10.1016/j.epsl.2014.10.024
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>-16.14
<p style="margin-left: 0px"><strong>longitude: </strong>-69.15
<p style="margin-left: 0px"><strong>elevation: </strong>3810
<p style="margin-left: 0px"><strong>siteName: </strong>Lake Titicaca
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT24a1c7baff
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MATa2cbe1b687
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>depth
</details>
<details style="margin-left: 10px">
<summary>dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FOTI01B
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>SASM precipitation that falls on the Altiplano is ultimately derived from Atlantic Ocean moisture that has been transported across the Amazon Basin and lifted over the eastern cordillera of the Andes. Altiplano ?Dp thus integrates upstream effects including rainout and moisture recycling over the Amazon Basin, altitude effects associated with upslope moisture transport, and local effects such as the intensity of precipitation (?amount effect?) (Dansgaard, 1964). ... "Increased rainout along this trajectory, as well as increased local precipitation in the Andes, results in more depleted ?Dp, consistent with the continentality and amount effects that dominate ?Dp variability throughout most of tropical South America (Vuille et al., 2003). Accordingly, the intensity of the SASM is significantly negatively correlated with ?18O (and correspondingly ?D) of modern precipitation in the Cen- tral Andes, as well as throughout much of southern tropical South America (Vuille and Werner, 2005).
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>SH summer
<p style="margin-left: 20px"><strong>variable: </strong>South American Summer Monsoon precipitation intensity
<p style="margin-left: 20px"><strong>direction: </strong>decrease
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Results from both observational and modeling studies suggest that the dominant control on modern interannual Andean ?Dp variability is Rayleigh-type fractionation during rainout along the trajectory of moist air masses across the Amazon Basin up to the Andes (e.g., Rozanski et al., 1993; Hoffmann et al., 2003; Vimeux et al., 2005; Vuille and Werner, 2005). Increased rainout along this trajectory, as well as increased local precipitation in the Andes, results in more depleted ?Dp, consistent with the continentality and amount effects that dominate ?Dp variability throughout most of tropical South America (Vuille et al., 2003).
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>SH summer
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Results from both observational and modeling studies suggest that the dominant control on modern interannual Andean ?Dp variability is Rayleigh-type fractionation during rainout along the trajectory of moist air masses across the Amazon Basin up to the Andes (e.g., Rozanski et al., 1993; Hoffmann et al., 2003; Vimeux et al., 2005; Vuille and Werner, 2005). Increased rainout along this trajectory, as well as increased local precipitation in the Andes, results in more depleted ?Dp, consistent with the continentality and amount effects that dominate ?Dp variability throughout most of tropical South America (Vuille et al., 2003).
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>SH summer
<p style="margin-left: 20px"><strong>variable: </strong>continental effect
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>basis: </strong>While the isotopic composition of precipitation appears to be the primary control on the structure of the LT ?Dwax record, it is clear that secondary effects also contribute to this signal. Most notably, the much larger range at LT (102h) than at Illimani (58h) over the past 19 kyr suggests the influence of compounding effects on LT ?Dwax, such as decreased regional precipitation, resulting in a more enriched ?Dp, and low local humidity, which would tend to further enrich plant source water by soil water evaporation and/or leaf transpiration. Since such local evapotranspiration feedbacks would be expected to act in step with ?Dp changes, this would serve to amplify the ?Dwax signal and increase its sensitivity to ?Dp variability.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>soil water evapotranspiration
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>dD (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>LS14FOTI01A
<p style="margin-left: 10px"><strong>variableName: </strong>dD
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>terrestrial biomarker
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>SASM precipitation that falls on the Altiplano is ultimately derived from Atlantic Ocean moisture that has been transported across the Amazon Basin and lifted over the eastern cordillera of the Andes. Altiplano ?Dp thus integrates upstream effects including rainout and moisture recycling over the Amazon Basin, altitude effects associated with upslope moisture transport, and local effects such as the intensity of precipitation (?amount effect?) (Dansgaard, 1964). ... "Increased rainout along this trajectory, as well as increased local precipitation in the Andes, results in more depleted ?Dp, consistent with the continentality and amount effects that dominate ?Dp variability throughout most of tropical South America (Vuille et al., 2003). Accordingly, the intensity of the SASM is significantly negatively correlated with ?18O (and correspondingly ?D) of modern precipitation in the Cen- tral Andes, as well as throughout much of southern tropical South America (Vuille and Werner, 2005).
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>SH summer
<p style="margin-left: 20px"><strong>variable: </strong>South American Summer Monsoon precipitation intensity
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Results from both observational and modeling studies suggest that the dominant control on modern interannual Andean ?Dp variability is Rayleigh-type fractionation during rainout along the trajectory of moist air masses across the Amazon Basin up to the Andes (e.g., Rozanski et al., 1993; Hoffmann et al., 2003; Vimeux et al., 2005; Vuille and Werner, 2005). Increased rainout along this trajectory, as well as increased local precipitation in the Andes, results in more depleted ?Dp, consistent with the continentality and amount effects that dominate ?Dp variability throughout most of tropical South America (Vuille et al., 2003).
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>SH summer
<p style="margin-left: 20px"><strong>variable: </strong>P_isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Results from both observational and modeling studies suggest that the dominant control on modern interannual Andean ?Dp variability is Rayleigh-type fractionation during rainout along the trajectory of moist air masses across the Amazon Basin up to the Andes (e.g., Rozanski et al., 1993; Hoffmann et al., 2003; Vimeux et al., 2005; Vuille and Werner, 2005). Increased rainout along this trajectory, as well as increased local precipitation in the Andes, results in more depleted ?Dp, consistent with the continentality and amount effects that dominate ?Dp variability throughout most of tropical South America (Vuille et al., 2003).
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>SH summer
<p style="margin-left: 20px"><strong>variable: </strong>continental effect
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>basis: </strong>While the isotopic composition of precipitation appears to be the primary control on the structure of the LT ?Dwax record, it is clear that secondary effects also contribute to this signal. Most notably, the much larger range at LT (102h) than at Illimani (58h) over the past 19 kyr suggests the influence of compounding effects on LT ?Dwax, such as decreased regional precipitation, resulting in a more enriched ?Dp, and low local humidity, which would tend to further enrich plant source water by soil water evaporation and/or leaf transpiration. Since such local evapotranspiration feedbacks would be expected to act in step with ?Dp changes, this would serve to amplify the ?Dwax signal and increase its sensitivity to ?Dp variability.
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>soil water evapotranspiration
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### dD (permil)
```{r}
plotCol(thisTS,ind = 1)
```

### dD (permil)
```{r}
plotCol(thisTS,ind = 4)
```
