---
title: "SS05ROES"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 464
thisTS <- TS[which(udsn[i] == dsn)]
```
#SS05ROES

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](SS05ROES.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/iso2kv0_11_0/SS05ROES.lpd)
            

[Download data only (csv)](SS05ROES.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>sclerosponge
<p style="margin-left: 0px"><strong>originalDataURL: </strong>https://www.ncdc.noaa.gov/paleo/study/1920
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
<p style="margin-left: 0px"><strong>dataContributor: </strong>KHK
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Rosenheim, Brad E.
<p style="margin-left: 10px"><strong>citeKey: </strong>rosenheim2005salinity
<p style="margin-left: 10px"><strong>journal: </strong>Geophys. Res. Lett.
<p style="margin-left: 10px"><strong>volume: </strong>32
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Salinity change in the subtropical Atlantic: Secular increase and teleconnections to the North Atlantic Oscillation
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2004GL021499
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>author: </strong>Rosenheim, B.
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>title: </strong>Ocean2kHR-AtlanticBahamasExumaRosenheim2005
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>23.766
<p style="margin-left: 0px"><strong>longitude: </strong>-76.053
<p style="margin-left: 0px"><strong>elevation: </strong>-136
<p style="margin-left: 0px"><strong>siteName: </strong>Tongue of the Ocean, Exuma Sound Bahamas
<p style="margin-left: 0px"><strong>pages2kRegion: </strong>Ocean
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT2569a32240
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_112
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>d18O of carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>we find secular salinity increases of 0.35 ± 0.34 psu in Exuma Sound and 0.5 ± 0.35 psu in TOTO that must happen coevally with the secular temperature increases to explain the discrepancies between Sr/Ca and d18Oaragonite linear temperature trends. It is evident from (4) that our reconstruction is sensitive to the gradient d18Osw/S (0.54 %psu1). Despite the significant cumulative residual error from equations (1)–(3) (auxiliary material), our data clearly identify salinity variation in the subsurface waters of both Exuma Sound and TOTO during the last 100 years.
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>temperature and salinity
<p style="margin-left: 20px"><strong>variableDetail: </strong>subsurface, 136 m
<p style="margin-left: 20px"><strong>direction: </strong>decrease
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>bohm 2000 10.1016/S0016-7037(99)00408-1
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>mode of skeleton formation of Ceratoporella nicholsoni suggest that these sponges precipitate aragonite close to isotopic equilibrium (bohm, 2000).
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>sclerosponges were dated using U/Th radiometric techniques and then analyzed using high resolution micromilling for oxygen isotope analysis via isotope ratio mass spectrometry and laser ablation sampling for Sr/Ca analysis via ICP-MS. Constant-growth age models constructed from U/Th dating indicate growth rates of 145 mmy1 for the Exuma sclerosponge and 172 mmy1 for the TOTO sclerosponge (auxiliary material1). The radiometric age model of the TOTO sclerosponge was tuned to annual Sr/ Ca variations after Swart et al. [2002], however because tuned age models and constant growth models are within 5% [Swart et al., 2002], the U/Th constant growth model was used for the Exuma sclerosponge.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>subannual samples averaged to annual for archived data
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>U/Th dating and Sr/Ca for annual cycles to define chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_water
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>basis: </strong>Oxygen isotope values (d18O) are measured in %VPDB for aragonite and % SMOW for water. Ratios of Sr/Ca are measured in mmolmol1, temperature (T) is in C, and salinity (S) is in psu. Equation (3) is constructed from surface waters (<50 m) of the return flow of the N. Atlantic Gyre between 45N and 31N. During transport between these latitudes, this water mass begins adopting the properties of the SMW [Krauss, 1986; Ottens, 1991]. By combining and rearranging these equations to reconstruct the salinity record preserved in Bahamas sclerosponges,
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>equilibriumEvidence: </strong>mode of skeleton formation of Ceratoporella nicholsoni suggest that these sponges precipitate aragonite close to isotopic equilibrium (bohm, 2000).
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeBasis: </strong>sclerosponges were dated using U/Th radiometric techniques and then analyzed using high resolution micromilling for oxygen isotope analysis via isotope ratio mass spectrometry and laser ablation sampling for Sr/Ca analysis via ICP-MS. Constant-growth age models constructed from U/Th dating indicate growth rates of 145 mmy1 for the Exuma sclerosponge and 172 mmy1 for the TOTO sclerosponge (auxiliary material1). The radiometric age model of the TOTO sclerosponge was tuned to annual Sr/ Ca variations after Swart et al. [2002], however because tuned age models and constant growth models are within 5% [Swart et al., 2002], the U/Th constant growth model was used for the Exuma sclerosponge.
<p style="margin-left: 20px"><strong>integrationTimeUncertainty: </strong>subannual samples averaged to annual for archived data
<p style="margin-left: 20px"><strong>integrationTimeUncertaintyType: </strong>U/Th dating and Sr/Ca for annual cycles to define chronology
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>year
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>salinity_seawater
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>Sr_Ca (mmol/mol)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>Ocean2kHR_113
<p style="margin-left: 10px"><strong>variableName: </strong>Sr_Ca
<p style="margin-left: 10px"><strong>units: </strong>mmol/mol
<p style="margin-left: 10px"><strong>description: </strong>carbonate
<p style="margin-left: 10px"><strong>useInGlobalTemperatureAnalysis: </strong>TRUE
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>interpDirection: </strong>decrease
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variable: </strong>temperature
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea_surface
<p style="margin-left: 20px"><strong>direction: </strong>decrease
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>seawater
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>rank: </strong>NA
<p style="margin-left: 20px"><strong>scope: </strong>isotope
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O (permil)
```{r}
plotCol(thisTS,ind = 1)
```

### Sr_Ca (mmol/mol)
```{r}
plotCol(thisTS,ind = 3)
```
