---
title: "TR12SAMU"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)

#read functions
source("../../functions.R")


load("../../temp.Rdata")

#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]


#All datasets
dsn <- sapply(TS,"[[","dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- as.numeric(sapply(TS,"[[","geo_latitude")[ui])
lon <- as.numeric(sapply(TS,"[[","geo_longitude")[ui])
#elev <- sapply(TS,"[[","geo_elevation")[ui]
archiveType <- sapply(TS,"[[","archiveType")[ui]
link <- paste0(udsn,".html") %>% 
  str_replace_all("'","_")

#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 483
thisTS <- TS[which(udsn[i] == dsn)]
```
#TR12SAMU

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](TR12SAMU.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/iso2kv0_11_0/TR12SAMU.lpd)
            

[Download data only (csv)](TR12SAMU.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>wood
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>Sano M.
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
<p style="margin-left: 10px"><strong>DOI: </strong>10.1029/2012JD017749
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
<p style="margin-left: 10px"><strong>pubYear: </strong>NA
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>21.67
<p style="margin-left: 0px"><strong>longitude: </strong>104.1
<p style="margin-left: 0px"><strong>elevation: </strong>1850
<p style="margin-left: 0px"><strong>siteName: </strong>Mu Cang Chai, Northern Vietnam
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>year (AD)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>MAT1f7cb77c97
<p style="margin-left: 10px"><strong>variableName: </strong>year
<p style="margin-left: 10px"><strong>units: </strong>AD
<p style="margin-left: 10px"><strong>description: </strong>Year AD
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>TR12SAMU06
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>cellulose
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>May, June, July, August, September, October
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>Seasonal
<p style="margin-left: 20px"><strong>direction: </strong>negative
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched 18O in tree rings. Moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor. Although the mechanisms underlying variations in tree- ring d18O can generally be attributed to d18O of source water and evaporative enrichment of 18O leaf water, in pluvial monsoon regions these effects seem to be well represented by the PDSI.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>inferredMaterial: </strong>soil water
<p style="margin-left: 20px"><strong>integrationTime: </strong>1
<p style="margin-left: 20px"><strong>integrationTimeUnits: </strong>years
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>Linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>P_E
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation_amount
<p style="margin-left: 20px"><strong>basis: </strong>calibration with instrumental record
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>variable: </strong>T_air
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>TR12SAMU01
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>cellulose
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>May, June, July, August, September, October
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>Seasonal
<p style="margin-left: 20px"><strong>direction: </strong>negative
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched 18O in tree rings. Moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor. Although the mechanisms underlying variations in tree- ring d18O can generally be attributed to d18O of source water and evaporative enrichment of 18O leaf water, in pluvial monsoon regions these effects seem to be well represented by the PDSI.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>Linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>basis: </strong>calibration with instrumental record
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation_amount
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>T_air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>TR12SAMU02
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>cellulose
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>May, June, July, August, September, October
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>Seasonal
<p style="margin-left: 20px"><strong>direction: </strong>negative
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched 18O in tree rings. Moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor. Although the mechanisms underlying variations in tree- ring d18O can generally be attributed to d18O of source water and evaporative enrichment of 18O leaf water, in pluvial monsoon regions these effects seem to be well represented by the PDSI.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>Linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>basis: </strong>calibration with instrumental record
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation_amount
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>T_air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>TR12SAMU03
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>cellulose
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>May, June, July, August, September, October
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>Seasonal
<p style="margin-left: 20px"><strong>direction: </strong>negative
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched 18O in tree rings. Moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor. Although the mechanisms underlying variations in tree- ring d18O can generally be attributed to d18O of source water and evaporative enrichment of 18O leaf water, in pluvial monsoon regions these effects seem to be well represented by the PDSI.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>Linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>basis: </strong>calibration with instrumental record
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation_amount
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>T_air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>TR12SAMU04
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>cellulose
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>May, June, July, August, September, October
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>Seasonal
<p style="margin-left: 20px"><strong>direction: </strong>negative
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched 18O in tree rings. Moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor. Although the mechanisms underlying variations in tree- ring d18O can generally be attributed to d18O of source water and evaporative enrichment of 18O leaf water, in pluvial monsoon regions these effects seem to be well represented by the PDSI.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>Linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>basis: </strong>calibration with instrumental record
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation_amount
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>T_air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18O (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>TR12SAMU05
<p style="margin-left: 10px"><strong>variableName: </strong>d18O
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>cellulose
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>May, June, July, August, September, October
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>Seasonal
<p style="margin-left: 20px"><strong>direction: </strong>negative
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched 18O in tree rings. Moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor. Although the mechanisms underlying variations in tree- ring d18O can generally be attributed to d18O of source water and evaporative enrichment of 18O leaf water, in pluvial monsoon regions these effects seem to be well represented by the PDSI.
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>Linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>variable: </strong>P_E
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>basis: </strong>calibration with instrumental record
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>Precipitation_amount
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>linear
<p style="margin-left: 20px"><strong>seasonality: </strong>May-October
<p style="margin-left: 20px"><strong>variable: </strong>T_air
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>z-score (permil)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>TR12SAMU00
<p style="margin-left: 10px"><strong>variableName: </strong>z-score
<p style="margin-left: 10px"><strong>units: </strong>permil
<p style="margin-left: 10px"><strong>description: </strong>normalised d18O of tree cellulose (z-score)
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>interpDirection: </strong>negative
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>seasonality: </strong>May to October
<p style="margin-left: 20px"><strong>variable: </strong>PDSI
<p style="margin-left: 20px"><strong>variableDetail: </strong>soil moisture
</details>
<details style="margin-left: 20px">
<summary>2</summary>
<p style="margin-left: 20px"><strong>basis: </strong>As recorded in the meteorological data from the monsoon season, higher temperatures usually correlate with lower precipitation, and relative humidity levels, both of which lead to enriched d18O in tree rings?..moreover, as climate parameters are significantly correlated with one another, it is difficult to identify a dominant factor...Although the mechanisms underlying variations in tree ring d18O can generally be attributed to d18O of source water and evaporative enrichment of leaf water d18O, in pluvial monsoon regions these effects seem to be well represented by the PDSI,
<p style="margin-left: 20px"><strong>coefficient: </strong>-0.66
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>fraction: </strong>0.44
<p style="margin-left: 20px"><strong>mathematicalRelation: </strong>Linear
<p style="margin-left: 20px"><strong>rank: </strong>1
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>seasonality: </strong>May to October
</details>
<details style="margin-left: 20px">
<summary>3</summary>
<p style="margin-left: 20px"><strong>direction: </strong>negative
<p style="margin-left: 20px"><strong>rank: </strong>2
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
<details style="margin-left: 20px">
<summary>4</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>rank: </strong>3
<p style="margin-left: 20px"><strong>scope: </strong>isotope
<p style="margin-left: 20px"><strong>coefficient: </strong>NA
<p style="margin-left: 20px"><strong>fraction: </strong>NA
</details>
</details>
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```

### Search the LiPDverse (Beta! doesn't work well yet)
```{r}
#Add google search bar
htmltools::includeHTML("../../googleSearchChunk.html")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### d18O (permil)
```{r}
plotCol(thisTS,ind = 1)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 3)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 4)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 5)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 6)
```

### d18O (permil)
```{r}
plotCol(thisTS,ind = 7)
```

### z-score (permil)
```{r}
plotCol(thisTS,ind = 8)
```
